### ISSUE TITLE
How to Track Animals in Urban Areas

### ISSUE THREAD

**Issue by defarm** [chihacknight/breakout-groups#102]
### About the group
Mapping the population of animals in urban areas, tracking their migrations, and working on our complex relationship (for the better!).

### Group leaders
David E. Farmilant

### Who we're looking for
Brainstormers!
TBD

### Tools
Flow charts!
TBD

### Relevant Links
http://www.wikihow.com/Brainstorm

### Where we meet
In a room with a whiteboard, or the library if we're beat to one...

**Comment by WesThorburn** [comment]
Hi Defarm, I'm interested. I'll be at Chi Hack Night tomorrow night, I'll keep an eye out for this group's introduction at the start!

**Comment by defarm** [comment]
I'm running late. I'll be there a little after 6.

**Comment by bburns632** [comment]
Check out [MyTraps](http://spensatech.com/mytraps.html) and [OpenScout](http://spensatech.com/openscout.html) from Spensa.  This company appears to have the same goal as this breakout group.  They have hardware, software, and analysis. They started as a [Purdue Project](https://www.purdue.edu/newsroom/releases/2013/Q1/super-app-helps-agricultural-growers,-consultants-track-insect-populations-in-multiple-geographic-regions.html) in 2013.

**Comment by atenn** [comment]
Lincoln Park Zoo also has Chicago Wildlife Watch:
http://chicagotonight.wttw.com/2017/03/27/urban-wildlife-monitoring-program-expanded-lincoln-park-zoo
https://www.zooniverse.org/projects/zooniverse/chicago-wildlife-watch

**Comment by WesThorburn** [comment]
Spensa's two apps combined with Lincoln Park Zoo's wildlife watch program makes this project idea fairly redundant. Although, I'm still happy to help out if there are any other ideas that haven't already been implemented.

**Comment by defarm** [comment]
I think it's safe to say that putting this project on an indefinite hold is the wise thing to do.  My initial expectation for this project was to be able to reach out to communities of people without access to technology.  Humanitarian Open Street Map has been doing a great job at mapping out disease carrying animals and insects in countries where they are active; I agree that this, on all levels of completion, would be redundant.

**Comment by WesThorburn** [comment]
We better close this issue for now then. Just so they don't keep reading it out to everyone at Hack Night. It can be reopened at any point later on if we decide to resume.

**Comment by defarm** [comment]
Yes. If anyone is interested in HOT, here's a Facebook link to their page.  https://www.facebook.com/hotosm/?hc_ref=NEWSFEED&fref=nf
