### ISSUE TITLE
Block Club Coalition

### ISSUE THREAD

**Issue by easherma** [chihacknight/breakout-groups#103]
### About the group
Group of people getting together about Block Clubs 

### Group leaders
Group leader, email 

### Who we're looking for
People who run block clubs, people who know what's already out there , web developers 

### Tools
Email, Facebook groups 

### Relevant Links
Slack 
City Bureau
 

### Where we meet
Where in the Braintree office do you meet? Flipping Tables? The cafeteria?

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by stevevance** [comment]
Does this include multi-block block clubs, like "BARR Neighbors" ("West side of Racine, north side of Belmont, east side of Ashland to southside of Roscoe (west of Southport) and both sides of Newport (east of Southport)"), or exclusively single-block block clubs, which seem to be more present on the South Side?

**Comment by derekeder** [comment]
sounds like this group hasn't met in a while. closing for now
