### ISSUE TITLE
[On hold until May 2018; Meanwhile, feel free to ping on CHN Slack - #CD2BIT channel] Chicago Deaf and DeafBlind in Tech / CD2BIT

### ISSUE THREAD

**Issue by nickttng** [chihacknight/breakout-groups#104]
### About the group (and How Can We Help You?)
CD2BIT pronounced as _Cee Dee Two Bit_

Using technology and inclusive design, we’re a mixed of d/Deaf and Hard-of-Hearing (HoH) designers, developers, technologists and non- working to improve social, educational and economic well-being of d/Deaf and HOH communities in the Chicago area.

Currently, we’re trying to solve:

- Breaking down silos within deaf community (racial, age, etc.), which has been identified by Chicago Chapter of [Illinois Association of the Deaf](http://www.iadeaf.org/) (CCIAD). Using [DeafChi](https://github.com/deafchi/deafchi.github.io) as a tool, it’ll be centralized place online for deaf events, orgs, etc. and make it easy to know what’s happening. **[on hold]**
- Helping people find technology conferences that are accessible and accommodating through [Confa11y](https://www.confa11y.com/), enabling not only deaf, but also those with other needs, to learn and grow professionally. (Led by @nickttng) 
- Search for STEM (Science, Technology, Engineering, Math) signs made easy. In a field where new technologies are always emerging, [SignsFive](https://github.com/deafchi/opensigns-web) (Formerly known as OpenSIgns) will be a place where d/Deaf/HoH, interpreters and ASL students can find ASL signs for STEM terms. (Led by @meltedspork)

Also, we are open to other app/web ideas that help disabled community; for instance, better accessibility for Chicago Transit Authority (CTA) or a tool tracking Illinois bills that affect deaf/hoh people. We welcome new projects on rolling basis.

**If you’re looking for accessibility help for your website, app, and/or product, happy to chat more.** 

### Group Facilitators
Melissa Manak, co-facilitator - [melissa.manak@gmail.com](mailto:melissamanak@gmail.com) / @msmanak
Nick Ng, co-facilitator - [hello@nickng.co](mailto:hello@nickng.co) / @nickttng / [DM @nickttng on Twitter](https://twitter.com/nickttng) 

For sign language and/or interpreting questions, ping in #asl channel on [ChiHackNight Slack](http://slackme.chihacknight.org/).

### Who We're Looking For
Anyone who's interested in accessibility, inclusive design, and/or getting to know the deaf community and its current problems they're facing.

### Tools
Depends on each project, the tools we often use are:

- Google Drive
- Slack ([deafpros.com](https://www.deafpros.com/) [deaf/hoh only] and [ChiHackNight](http://slackme.chihacknight.org/))
- GitHub

Design: Sketch and Adobe Creative Suite, UX Design

Technology: HTML + CSS, JavaScript libraries, Sass, Jekyll, etc.

### Where We Meet
Usually in one of the meeting rooms; if not there, we will be in the cafeteria. It's easy to spot us. ;)

### Questions You May Have Re: Communication Barriers

**Do I need to know American Sign Language (ASL) to be involved?**
No, but willing to learn is a plus. If you want to learn how, just approach us anytime.

**If I don’t know ASL, what is a good way(s) to communicate with you?**

- If an ASL interpreter is on site, they will be able to interpret for both of us
- If there is no ASL interpreter on site, we prefer to communicate through written text via Notes app, Google Doc, Slack, etc. To talk with those who are hard-of-hearing, they may be open to speaking orally, but best if taking place in a quiet setting i.e. not the cafeteria.

**I have an idea that I’d like to share with you?**
Great! Feel free to come to us, email the co-leaders, or ping us at #cd2bit on [ChiHackNight](http://slackme.chihacknight.org/).

_Have questions? Comment here in this issue._

**Comment by nickttng** [comment]
@derekeder per group's request to be reflected more accurately, can these labels be added? Thx.

- Beginner friendly
- Data analysis
- Dev
- Javascript
- Ruby

**Comment by derekeder** [comment]
Done!

**Comment by nickttng** [comment]
@derekeder Because of several of us are in life transitions, CD2BIT will be on hold until May. Is it okay to close this issue for now until we start up again in several weeks?

While the breakout group is on hold, few of us may be attending here and there.
