### ISSUE TITLE
[not meeting this week] Data-Driven Nature Journalism w/ South Side Weekly

### ISSUE THREAD

**Issue by jmithani** [chihacknight/breakout-groups#105]
### About the group
For the [South Side Weekly's](http://southsideweekly.com) second annual Nature Issue, we are looking for ideas and collaborators to help us with a data-driven, digital project about a topic relating to environmental justice, ecosystems, wildlife, biking, etc. on or relevant to the South Side. The issue will be released on May 31st, and we will be at every ChiHack leading up to then. We hope to maintain this working group after the release of the nature issue, so if you are interested in civic journalism please come speak to us -- no experience required!

The South Side Weekly is a nonprofit newsprint magazine dedicated to supporting cultural and civic engagement on the South Side, and to providing educational opportunities for developing journalists, writers, and artists.

### Group leaders
Baci Weiler, Director of Staff Support (baci.weiler@southsideweekly.com)
Emily Lipstein, Social Media Editor/Nature Issue Coordinator (emily.lipstein@southsideweekly.com)
Jasmine Mithani, Data Visualization (jazzmithani@gmail.com)
Sam Stecklow, Social Media Editor (sam.stecklow@southsideweekly.com)

### Who we're looking for
Anyone is welcome! We want to hear your ideas for a story. We are looking for this to be a data-driven project, so anyone with the relevant skills would be especially appreciated. We may also have opportunities for writing.

### Tools
Our website is hosted on WordPress, and we've used Carto, MapBox, d3, and QGIS for other stories in the past. We're open to using anything that will get the job done!

### Relevant Links
Website: http://southsideweekly.com
Current pitches for our 2017 Nature Issue: http://bit.ly/2nRdsrL
Nature Issue 2016: https://issuu.com/southsideweekly/docs/ssw_5-25-16_web

### Where we meet
Focus 01

### Chi Hack Night slack channel
Find us and introduce yourself at #south-side-weekly!

**Comment by jmithani** [comment]
@derekeder Could we add a few tags?
Mapping / GIS / Data Analysis / Data Visualization / Beginner Friendly (that's our aim)

**Comment by derekeder** [comment]
Done!

**Comment by derekeder** [comment]
@jmithani is this group still meeting?

**Comment by derekeder** [comment]
Closing for now. Feel free to re-open if you're planning on pitching this at hack night next week.
