### ISSUE TITLE
State of IL: Department of Human Services

### ISSUE THREAD

**Issue by CPecaut** [chihacknight/breakout-groups#11]
## August 23rd: Mob Programming in R: Session 5

Pass through the glass doors, to the right of the front podium, into the room where the food and drinks are served. Pass through this room, past the ping pong table, and opposite a wall with many coloured chalk you will find the lounge seats wherein we learn R and analyze public assistance in the state of Illinois.

Each session yield new insights, and new techniques. All skill levels -- from total beginner, to data scientist, are welcome. 

## August 15th: Mob Programming in R: Session 4

Come on down to the video game room, to learn more about employment prospects across the state for citizens receiving public assistance. Every week has unique challenges.

## August 8th: Mob Programming in R: Session 3

Join us again this week for learning R, open source statistical software, at the same time as trying to figure out ways to analyze and improve employment prospects in the state of Illinois. This week we will be attempting to learn how to compare different time series of data.

Come on down to the video game room, which is a little bit father into the room where the food and drinks were served, and take a spin at running the programming for 5 minutes with the group.

## August 1st: Mob Programming in R: Session 2

Learn the statistical package R, while learning about current policy issues regarding the SNAP (food stamp) program in Illinois, along with metrics about how employment is obtained across the state.

## July 26th: One-Month-Redux: Data Treasure Hunt, Mob R Programming, Data Policy Thinking

Come learn more about data and policy at in the IL social safety net. After lingering in the front room to determine a rough number of participants, we may retire back by the food and the video games where we were last week.

## July 18th: Data Science Help needed for Food Stamps (SNAP) Analysis

If you had 8 years of monthly data on these data fields, encompassing ~2m families:
http://www.dhs.state.il.us/page.aspx?Item=21112

What patterns, indicators, or trends might you look for that would assist people in guiding policy to help people achieve their economic and life goals? Come help think through how to make the social safety net in IL work better.

Come learn about how metrics are utilize in guiding policy for the state provision of social services -- and help think through how you, or others could improve this process in the future.

--

### Ever seen the great Open Data Portal for the City of Chicago?

No such single location exists for all the open data sets available from the State of Illinois, Department of Human Services. Tonight, come by and help find them.

Illinois Department of Human Services: http://www.dhs.state.il.us/page.aspx?

We can compile the data sets, we find them, in the following Google Doc:
https://docs.google.com/document/d/1CDyhJcg4NRzN6ydYm2mvmN7N7QZHHyE4Gajat4jgJEY/edit?usp=sharing

Part of the challenge is that I cannot point you to any single place or method to begin this search -- because it does not currently exist, as far as I have so far discerned. Search, also, can return surprising historical results.

A small, dedicated team is currently reviewing the website, and looking to transform it -- so your suggestions could directly contribute to improving the website. Please join us.

---

## # **June 28th: Child Care Subsidies**

Come help improve the social safety net in the City of Chicago, and across Illinois. We are provide services to Illinois residents in poverty (Food Stamps, TANF) , facing other economic challenges, or have a variety of disabilities or health challenges (Mental Health / Substance Abuse). We are the largest agency in the state, with 14,057 employees.

Tonight, I will be outlining the challenges the state faces in providing child care subsidies in Illinois. We currently provide child care grants for more than 100,000 Illinois children each month -- and are looking to expand awareness of eligibility and better selection amongst qualified child care providers by the public. 

Group leaders: Chris.Pecaut@illinois.gov

We are looking for help thinking through how to improve the availability or efficiency of the services we provide. We are also looking for partnerships with non-profit groups, technologists, and others interested in learning more or offering a helping hand. 

We will meet in the main room, or in one of the breakout rooms once we put together a team.

**Comment by tomschenkjr** [comment]
Let Me Get That Data for You http://lmgtdfy.usopendata.org/

**Comment by dportnoy** [comment]
@CPecaut, I'd be interested in getting a tour of the gDoc from July 12th: Data Set Treasure Hunt

**Comment by derekeder** [comment]
Haven't met in a few weeks - closing for now

**Comment by derekeder** [comment]
closing for now
