### ISSUE TITLE
Aquahack

### ISSUE THREAD

**Issue by sbeslow** [chihacknight/breakout-groups#110]
[Aquahack](https://aquahacking.com/en/) is an international hackathon across several months.  This year is focused on Harmful Algae blooms in Lake Erie.  A Chicago team is forming that is focusing on predictive modeling, but the data is a mess.  This team will focus on 3 things.

1. **Scraping and aggregating data**.  Currently, [the data](https://2017.aquahacking.com/en/challenge/#data) is across many different websites and in different formats.  Can we organize this nicely, maybe create an API?

2. **Predictive Modeling**.  Can we predict when a Harmful Algae Bloom will rock Toledo or Cleveland, like [this one in Toledo, that caused a two-day ban on drinking tap water](https://www.nrdc.org/media/2015/150731).

3. **A fancy, schmancy dashboard** to see this data all combined.

Points of contact: @sbeslow, @jayqi, Adam Hecktman

**Comment by DGalt** [comment]
Repo for this group can be found at: https://github.com/open-city/aquahacking

We also have a channel in the Chi Hacknight slack: #aquahack
