### ISSUE TITLE
Unieros MultiEthnic Social App

### ISSUE THREAD

**Issue by chitech** [chihacknight/breakout-groups#112]
### About the group
Chicago is very diverse with more than 55 ethnicities represented. Racially its made of approximately 1/3 white, 1/3 blacks, 1/3 Hispanics. The problem is we often socialize in the homogeneous groups and miss out on getting to know more people outside our social networks. Since 2009, Unieros multicultural events have provided fun themed social events to connect people across ethnic groups, neighborhoods, racial and social backgrounds. 

Tonight, May 16 we are participating in On the Table and will discuss building bridges across diverse groups. 

In the future, we will work on a mobile app and improve our web experience to facilitate connections and event experience.

### Group leaders
Christine Brown, web developer and founder of Unieros

### Who we're looking for
Seeking people interested in connecting with diverse people socially. Developers with UI/UX, front-end map and data experience. We have a website and demo application that we are currently improving to facilitate connections and events.

### Tools
We are using Javascript, AngularJS for the app and PHP, HTML and CSS for the WordPress site. 

### Relevant Links
www.unieros.com

### Where we meet
TBD

**Comment by derekeder** [comment]
Is this group still meeting at Chi Hack Night on a regular basis?

**Comment by chitech** [comment]
We are not meeting on a regular basis but will create let you know when we are in attendance.

**Comment by derekeder** [comment]
OK going to close until you come back.
