### ISSUE TITLE
Emergency notification and instant crowd recruitment strategy for the prevention of street crimes

### ISSUE THREAD

**Issue by khinami** [chihacknight/breakout-groups#113]
### About the group
A high level overview of your breakout group. What problem are you trying to solve? Make this simple and jargon-free. Links are good too!

### Group leaders
Names and contact info for the people running this group.

### Who we're looking for
Describe the kinds of people who would be good for your group. Include the skills, domain knowledge and interests that will help make your project succeed.

### Tools
Describe the tools that you are using.

### Relevant Links
Any relevant links, e.g. a github repo, a demo site

### Where we meet
Where in the Braintree office do you meet? Flipping Tables? The cafeteria?

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
Are you planning on pitching this project next hack night?

**Comment by khinami** [comment]
Derek, I would like to try pitching it once more. This coming Tuesday? Thanks.
Keiki

**Comment by derekeder** [comment]
Yup! Sounds good!

**Comment by npwinkler** [comment]
Has anything happened with this group?

**Comment by khinami** [comment]
I was able to connect with a startup on-demand rideshare company to explore
collaborative solutions. I am hoping to exhaust the possibilities from this
partnership before coming back to Hack Night, but will be happy to report
back on progress as requested. Thank you!
Keiki

**Comment by derekeder** [comment]
@khinami thanks for the update! We'll close this for now. We can re-open when you come back.
