### ISSUE TITLE
Open Data Pledge for Illinois Governor Candidates

### ISSUE THREAD

**Issue by dachartier** [chihacknight/breakout-groups#115]
### About the group
This pledge builds on the success of the open data pledge created for Cook County State's Attorney's Office. It's directed at the candidates running for Governor of Illinois.

**Current Draft: [2018 Illinois Governor Race - Open Data Pledge](https://docs.google.com/document/d/1wsN8Qrh-OqlzAUQi0pCyplNLf5Xtyeblauw1qAuGdVw/edit)** Feedback requested!

### Group leaders
Don Chartier, dchartier@hourvoice.com, 312 532 7320. @donchartier

### Who we're looking for
-Understanding of open data issues
-Writing skills
-Public Policy skills
-No technical skills required
-Works and plays well with others

### Tools
Low, low tech -- Google Docs.

### Relevant Links
Workplan: https://docs.google.com/spreadsheets/d/16UzczzgFsr74D2oRBrv694Itc1gob1a0jQfu-d83ZfY/edit?usp=sharing

In-Progress Pledge -- Feel free to comment, edit: https://docs.google.com/document/d/1G7e1iKu5VsvIJenH4ILRcICm6VT4FJLpPu37hHIcYGg/edit?usp=sharing

State's Attorney Pledge --Feel free to comment: https://docs.google.com/document/d/1SbxbvzV-rqU8AUiIjq2Zcw6-yJ-9zfbhVJLT-mmCgYQ/edit?usp=sharing

### Where we meet
Cafeteria, or (optionally) nearest bar.

### Chi Hack Night slack channel
#opendatapledge

**Comment by derekeder** [comment]
The pledge has been written and published! https://chihacknight.org/blog/2017/10/03/open-data-pledge-for-illinois-governor.html

Closing this group.

But, sometime later, in a time of need, the open data pledge will return.

**Comment by dachartier** [comment]
Just turn on the Bat Signal!
