### ISSUE TITLE
Bridges from School to Work Virtual Mentor

### ISSUE THREAD

**Issue by cnwalker** [chihacknight/breakout-groups#116]
### About the group
[Bridges from School to Work](http://www.bridgestowork.org/) is a non-profit organization that matches students with disabilities with employers. We are building a virtual mentor to help Bridges participants in their day-to-day jobs. The app currently supports FAQs with a recommendation algorithm like Quora. 

We have some pretty cool [anonymized datasets](https://drive.google.com/drive/folders/0B6pof92cN6Oba0ZiaHRKNk1kZjA?usp=sharing), that'll hopefully let us do things like:

- Have targeted push notifications (i.e based on our data most people have received a raise after working for x employer as long as you have, you should ask for a raise and here's how). 

- Determine based on app activity which things are interesting to which kinds of bridges participants

### Group leaders
Christopher Walker
Email: christophernathanielwalker@gmail.com

### Who we're looking for

- People who have opinions on how mobile apps should look and feel

- People who are interested in coming up with metrics from some anonymized datasets

- People who have experience with React Native/creating mobile frontends

- Anyone who thinks the project is interesting and would like to learn something new

### Tools

- React Native for the app itself

- For the server we are using Django, specifically Django rest framework

### Relevant Links
[Google drive folder w/ designs, project specs, and technical plans](https://drive.google.com/drive/folders/0B6pof92cN6ObOGcxbF9GLW9RNDA?usp=sharing)

[Mobile app github repo](https://github.com/uchicagotechteam/bridges-app)

[Server github repo](https://github.com/uchicagotechteam/bridges-server)

[API site](https://bridgesapi-skypath.rhcloud.com/admin/login/?next=/admin/)

### Where we meet
TBD - if there are no rooms available probably the cafeteria

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
Is this group still meeting at Chi Hack Night on a regular basis?

**Comment by cnwalker** [comment]
Nope I don't think anyone from the project will be back in town until the fall. Should I close this issue?

**Comment by derekeder** [comment]
Yup - lets close for now. You can reopen when you return. Thanks!
