### ISSUE TITLE
Grassroots Research Group

### ISSUE THREAD

**Issue by justgosh** [chihacknight/breakout-groups#117]
Survey Blurb:

Welcome!
Thank you for participating in the Grass Roots Research Project’s Digital Resistance Survey. GRRP is an
all-volunteer organization that was created to research and build a data model that will translate the
collective voice of the movement into a language elected officials and politicians understand: data.
Your survey responses will contain no personal identifying information. This data will be used
anonymously to develop a comprehensive, statewide picture of We The People—who we are, what we
want, and what we need—that politicians NEED to understand.
Thank you for lending your voice to the voices of so many others and speaking truth to power. If We
The People all speak up together, we cannot be ignored.

Who is the Grass Roots Research Project?
The Grass Roots Research Project is an all-volunteer nonprofit organization led by data analysts, digital
survey experts, UX designers, digital privacy advocates, and grassroots activists.

We have a simple mission: to do the research necessary to speak truth to power.
Each of has been engaged in Resistance groups and activities following the November 2016 Election and
feel a personal responsibility to get involved. Our goal is to develop a better understanding of the
explosion of citizen engagement in our state and ensure that the voices of activists and concerned
citizens are heard by elected officials and party leaders.

To do that, we must speak in a language that politicians understand: data.
We will use your survey responses (which contain no personal identifying information about you) to
build a data model that will show our elected officials how you feel, what you care about, and what you
want them to do.
(headshots and bios)

Why is GRRP interested in what I have to say?
Democracy is based on the idea that everyone’s voice matters—and so is GRRP. Our goal is to add your
voice to the multitude calling for change in a constructive, positive way. GRRP will use survey responses
to build a data model that will be publicly shared with elected officials and party leaders. It is 100%
anonymous and GRRP collects no personal identifying information. Our goal is not to gather
information about you personally, but about the activist movement generally.

Why should I take the survey and make my voice heard?
If you’re here, you’re engaged your voice is important. GRRP needs your perspective in order to make
politicians understand what We The People think and what we want from our elected officials.

How can I take the survey?
Click here(link) to take the survey and add your voice!

**Comment by derekeder** [comment]
Is this group still meeting?

**Comment by justgosh** [comment]
We are.  The team has small needs sporadically.  I'm the pitch man and I've
also been coming sporadically.
