### ISSUE TITLE
@realTrumpyBot -- preserving the public record through presidential memes

### ISSUE THREAD

**Issue by csethna** [chihacknight/breakout-groups#118]
### About the group
About the group: Twitter has become an integral part of the public discourse. The @realTrumpyBot project serves to preserve the public record by creating a real-time mirror of the President's personal twitter handle. The @realTrumpyBot reminds its audience of the gravitas of these special tweets by generating Executive Order memes fit for display in the. future DJT presidential library.

![image](https://user-images.githubusercontent.com/20688659/27094832-26f7eae6-5031-11e7-89f5-f51c33746097.png)

### Group leaders
Cyrus Sethna, csethna@gmail.com
Ryan Koch, inbox@ryanakoch.com

### Who we're looking for
Aiming to create context manager functionality that enables bot to reply to @mentions with contextually-appropriate copy. Endow bot with capability to discern register in natural language text functionality.

### Tools
Python3; Tweepy, Python Image Library, Textblob.

### Relevant Links
https://twitter.com/realTrumpyBot
https://github.com/Ryan-Koch/RumpTwitterBot

### Where we meet
Mess Hall

### Chi Hack Night slack channel
#realtrumpybot

**Comment by derekeder** [comment]
Is this group still meeting at Chi Hack Night on a regular basis?
