### ISSUE TITLE
What I'd Like to See on the Mayor's web site - Review in Slack Channel

### ISSUE THREAD

**Issue by tutormentor** [chihacknight/breakout-groups#119]
If you lead a social justice or  youth serving organization you're constantly looking for resources or help. 
When leaders,like the Mayor, talk about making the city a better place, don't  you some times say, "I wish this were what he was saying."  I created a video in 2011 to show what I wish the new Mayor of Chicago would say in his speeches and on his web site.  

A few weeks ago I listened to Jean and Alex describe how they created the Chance for Mayor web site and said, "What if a team of volunteers created new version of the video I created in 2011, imagining Mayor Rahm Emmanual outlining a strategy for helping kids in Chicago move through school and into careers!" I posted the idea on the [Slack channel](https://chihacknight.slack.com/messages/C61HWKKJ7/) and was encouraged to "start a breakout group".  

So, here I am.

I'm looking for creative people who might build a template that would make it easy for the Mayor, or any other celebrity, to deliver the same message, over and over.  I don't know what this would be, but hope to spark some imagination.  View the video and blog links I've posted below, then reach out to me on Slack if you'd like to talk about this.

### Group leaders
Dan Bassill, founder of Tutor/Mentor Connection (1993) and Tutor/Mentor Institute, LLC (2011)

### Who we're looking for
People with ability to look at an idea and see many different ways to communicate the idea more effectively.  People who already share the same goals of helping inner city youth and want to devote some time and talent to help build and share strategies that get others involved in more ways.  

### Tools
Volunteers who decide to work on this will decide what tools are needed.

### Relevant Links
View the video on Vialogues with my comments. https://vialogues.com/vialogues/play/36834/
Original video on YouTube - https://youtu.be/FMs-i418RJQ
View strategy map from the video - http://tutormentor.blogspot.com/2017/07/helping-youth-shared-vision-needed.html
Tutor/Mentor Institute, LLC web site - www.tutormentorexchange.net

### Where we meet
I hope to do most work using Slack, Twitter and/or Skype to interact.  For instance, this [Tutor/Mentor Program Locator ](http://www.tutormentorprogramlocator.net/InteractiveMap.aspx)interactive map space was created in 2008-9 by team from India, coordinated by team-leader in Baltimore. We never met in person but only communicated via email and phone.  

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here! Here's [MessagefromMayor channel](https://chihacknight.slack.com/messages/C61HWKKJ7/)

**Comment by tutormentor** [comment]
This same presentation could be created by the Governor, a candidate for office, or a business leader to show support for the same goals and process.

**Comment by tutormentor** [comment]
I posted a blog article yesterday (7/18) with the strategy map included in the video I created in 2011, with the invitation that many leaders create their own versions, showing their commitment to a shared vision.  http://tutormentor.blogspot.com/2017/07/helping-youth-shared-vision-needed.html

I'm hoping #chihacknight volunteers will innovate a way to create an easy to use template, which would enable many leaders to create versions of the map, showing their own commitment.

**Comment by derekeder** [comment]
This group hasn't met in a while. Unless you are planning to meet next week, I'd like to close this

**Comment by tutormentor** [comment]
Go ahead.

On Aug 8, 2017 11:00 PM, "Derek Eder" <notifications@github.com> wrote:

This group hasn't met in a while. Unless you are planning to meet next
week, I'd like to close this

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chihacknight/breakout-groups/issues/119#issuecomment-321146323>,
or mute the thread
