### ISSUE TITLE
Governor's Race Donations Analysis

### ISSUE THREAD

**Issue by skirmer** [chihacknight/breakout-groups#120]
### About the group
We are interested in creating public-facing data visualizations and easily accessible resources about the financial contributions that are going into the Illinois 2018 governor's race. 

### Group leaders
Stephanie Kirmer, Andy Moon, Lilian Huang

### Who we're looking for
One of our major goals is to build a shiny app that is easy to use, easy to update, and publicly accessible so people can see where contributions are coming from/going. Anyone who likes web scraping, data cleaning, and building visuals is welcome!

### Tools
We plan to mostly work in R, Shiny, and possibly D3. 

### Relevant Links
The major data source is https://www.elections.il.gov. We haven't really started yet, besides coming up with the idea!

### Where we meet
Cafeteria for now.

**Comment by ziegegeist** [comment]
It might be easier to take stuff from here https://www.illinoissunshine.org

This is a great project idea!

**Comment by derekeder** [comment]
FYI bulk downloads and an API are available for working with this data: https://www.illinoissunshine.org/about/#api

You can see how it all works as the code is open source on GitHub: https://github.com/Illinois-Campaign-for-Political-Reform/illinois-sunshine

**Comment by jelias1** [comment]
Hello, I am new to Chi Hack Night and will be attending my first one tonight. Will anyone be working on this tonight? I have created a few shiny apps before and would love to talk about this project with someone!

**Comment by skirmer** [comment]
Hi all- we have settled on working in R, so if you are looking for Python projects I'm afraid we can't help- sorry!

**Comment by Nishantkumark** [comment]
Hi I would love to know more about this project. Where should I meet you guys ? Can someone set  up a call and explain me few things related to this project ?

**Comment by derekeder** [comment]
is this breakout group still active? if not, let's close it for now

**Comment by easherma** [comment]
@skirmer is this project still active? We'd love an update, and let us know if you have any problems we can help address!
