### ISSUE TITLE
Urban Rivers Trashbot and River Ranger

### ISSUE THREAD

**Issue by nkwsy** [chihacknight/breakout-groups#121]
### About the group
Creating tools to clean and monitor our river. 

Currently we are working on creating a front end for trashbot, a robot which cleans the Chicago River. 

We are also building a platform to monitor plants, animals and other residents on the Chicago River

### Group leaders
Nick Wesley, nick@urbanriv.org

### Who we're looking for
Frontend Dev's 
People farmiliar with webRTC
Java, Python, Ruby JS
BONUS... People familiar with ubiquiti equipment

### Tools
Whatever's free

### Relevant Links
DriveTrashBot.com
ranger.urbanriv.org

### Where we meet
Cafeteria,

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
@nkwsy please edit and add some more detail to your original post when you get a chance!

**Comment by derekeder** [comment]
Haven't seen this group meet in a while. Closing until they come back.

**Comment by nkwsy** [comment]
Can I reopen this?

**Comment by derekeder** [comment]
Yes, allow me!

**Comment by derekeder** [comment]
Closing for now just to keep the list up to date. Feel free to reopen when you come back!
