### ISSUE TITLE
Time Lapse Chicago - Not meeting 10/24

### ISSUE THREAD

**Issue by wgaylord** [chihacknight/breakout-groups#122]
### About the group
Using publicly available camera's to make time lapses of Chicago.
Ex. http://abc7chicago.com/weather/cams/

Later usage of http://istheresewageinthechicagoriver.com/ data could be displayed with the time lapse to show storms as they roll thru chicago.

### Group leaders
William Gaylord @chibill

### Who we're looking for
People who use python and also are interested in using python for video creation from still images.
Also people who are generally interested in time lapses.

### Tools
Python
imageio (Python lib)

### Relevant Links
A few places for camera images.
http://abc7chicago.com/weather/cams/
http://wgntv.com/weather/webcams/

https://pypi.python.org/pypi/imageio (Used to make the videos.)

### Where we meet
The cafeteria? Depending on how many groups are there already.

### Chi Hack Night slack channel
the channel name is #timelapse

**Comment by chibill** [comment]
We will be meeting tomorrow. I will also be discussing my plans to try and time lapse / record the eclipse.

**Comment by chibill** [comment]
Going to hopefully be meeting tomorrow. 
Had some recent server problems but this project is back running. 

Still have the problems of the large amount of space all the files take up.

**Comment by chibill** [comment]
Meeting today. Also have some samples of what we the end goal is.

**Comment by derekeder** [comment]
@wgaylord meeting tonight?
