### ISSUE TITLE
Mapping City TIF Data With Vigor! 

### ISSUE THREAD

**Issue by easherma** [chihacknight/breakout-groups#123]
### About the group
Lets say you have some data in a csv or Google Sheet that you know can be put on a map, but it has no inherent geography?

Watch me go through some GIS basics manipulating some data and publishing it to the web using Leaflet

https://docs.google.com/spreadsheets/d/1HSkbPP7XJ4L2ytePLmAk4yU95KKrtxLf1a1ckXmuSbc/edit?ts=59aaf28e#gid=301742965

**Comment by stevevance** [comment]
The document is editable by anyone who has the link (which could be abused).

**Comment by easherma** [comment]
https://osgisomg.com/tifmap/

DONE
