### ISSUE TITLE
Help Survivors of Hurricane Irma with #IrmaResponse

### ISSUE THREAD

**Issue by csethna** [chihacknight/breakout-groups#124]
### About the group
Opportunities for coders and non-technical folks. Marketing, design, data entry, we are a group of 300+ volunteers distributed around the country with a keen interest in supporting survivors of Hurricane Irma. As of today we are supporting relief efforts in six states. [Join the Irma Response Network on Slack](https://irma-response-slack.herokuapp.com)

### Group leaders
- Cyrus Sethna @ Chi Hack Night
- 300+ volunteers distributed across the country

### Who we're looking for
Devs, marketers, anyone who speaks Spanish, Haitian-Creole, people who like to look stuff up on the Internet. People with experience making maps, doing API stuff. It's a big project so there's room for all types of skills and abilities.

### Tools
We are coordinating primarily through our [Slack Channel](https://irma-response-slack.herokuapp.com). I'm `@csethna` on the Chi Hack Night Slack if you can't find me IRL.

Using `#IrmaResponse` and `#HurricaneIrma` on Twitter.

We coordinate our working materials with GitHub and Google Drive.

### Relevant Links
- [Getting Started: Irma Response Onboarding](https://www.google.com/url?q=https%3A%2F%2Firma-response.slack.com%2Ffiles%2FU6Y39Q5J5%2FF6YRBQX53%2Firma_get_started_doc&sa=D&sntz=1&usg=AFQjCNETr3C9AFeGMGR51EsdbGxnsExzkw)
- [irmaresponse.org](https://www.irmaresponse.org/)
- [irmashelters.org](https://www.irmaresponse.org/)

### Where we meet
Let's grab some space in the mess.

### Chi Hack Night slack channel
We are `#IrmaResponse` on the [Chi Hack Night Slack](http://slackme.chihacknight.org/).

**Comment by stevevance** [comment]
Have you done anything with the OpenStreetMap Humanitarian OpenStreetMap Team (OSM HOT) tasking manager? It lists priority mapping tasks, with tasks for beginners and experts. 

Much of the work is tracing lines over roads, tagging them as roads, and then uploading your work. Other tasks include drawing rectangles over buildings, tagging them as buildings, and then uploading your work. Experts can take on more involved tasks like verifying others' work, and correcting errors identifying by validation programs. 

[Here are the tasks for Hurricane Irma-affected areas](http://tasks.hotosm.org/?sort_by=priority&direction=asc&search=hurricane+irma).
