### ISSUE TITLE
Let's do more Satellite Chi Hack Night Events!

### ISSUE THREAD

**Issue by easherma** [chihacknight/breakout-groups#125]
### About the group
Leadership @ Chi Hack Night has been talking about doing satellite events for awhile. We had the pleasure of partnering with Smart Chicago to do some last March.

They went well! Let's do more. 

### Group leaders
Myself and Andra Roxana Stanciu, a recent acquaintance of mine, will be discussing the purpose, format, and logistical details of horizontally scaling this meetup. 

### Who we're looking for
Anyone interested in learning how this group is run, sharing feedback/ideas, or hosting your own satellite event!
### Tools
Brains & brawn for now!

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by csethna** [comment]
Hey I want to get in on this. Is there a slack channel?

**Comment by roxanaOm** [comment]
Hello @csethna . #satelite_events is the Slack channel. Feel free to join us there and discuss more.
