### ISSUE TITLE
UpWorld Inc. Learning Management System

### ISSUE THREAD

**Issue by bmbejcek** [chihacknight/breakout-groups#126]
### About the group
UpWorld Inc. provides a two-year education and mentorship program to at-risk youth from 14-24 years old. They've been keeping track of students with an Excel spreadsheet and are working to build a better solution that allows administration to make data-driven decisions, teachers to input education data, and students to track personal progress.

### Group leaders
Tim McGovern @herdingbats
Melvin Hayes @upworldinc

### Who we're looking for
We are looking for passionate people who want to help build something cool. If you have any experience with database management, backend development, or front end development, we would love to have you.

### Tools
Google Firebase, HTML, CSS, Javascript

### Relevant Links
www.upworldinc.org

### Where we meet
We will announce where we meet at every hacknight.

### Chi Hack Night slack channel
Under the [Chi Hack Night Slack](http://slackme.chihacknight.org/), we have a channel called upworld.

**Comment by tedpope3000** [comment]
Hi, it's Ted Pope. I can't make it tonight but I'm hoping to be there next Tuesday.

**Comment by easherma** [comment]
@bmbejcek  is this project still active? We'd love an update, and let us know if you have any problems we can help address!
