### ISSUE TITLE
Bureaucracy Busters

### ISSUE THREAD

**Issue by csethna** [chihacknight/breakout-groups#127]
# Bureaucracy Busters (closed)
### Purpose
__***A learning group***__: we are here as members of the civic technology community, to apply our skills and knowledge from government service as private citizens, in support of civic technology projects in our communities. It is our goal to serve as a public sector consultancy at Chi Hack Night and provide a resource to civic hacktivists.

### Who are we?
We are a network of over 500 public sector employees in Chicago. Organized through [Young Government Leaders: Chicago](http://chigov.space), we represent government entities at the municipal, state, and federal levels. If you are a govie, check us out. We have contacts at most agencies with a presence in Chicago and are always looking for ways to be more inclusive.
- I'm `@csethna` on Slack.

### How we can work together (Hackers + Govies)
- You want to practice presenting your project to real, live, breathing government employees.
- You are stymied by bureaucracy: i.e. which form do I fill out?
- You are wondering about navigating inter (or intra) agency structures: i.e. am I taking the best approach to identifying a government partner?
- You need information: i.e. how do I complete a FOIA request?
- You have a question about government agency culture.
- You are fretting about how to communicate with the government.
- You are thinking about other things (we really do like to help).

### How you can find us
- We like to hang out in a group.
- We have a [YGL Logo](http://chigov.space/email/images/chihacknight.png) printed on a piece of paper nearby.
- We like to be in the mess hall or in the comfy chairs in the back/ sides of the presentation area.
- We are on the [Chi Hack Night Slack](https://chihacknight.slack.me) in the `#bureaucracy-busters` channel. DM `@csethna` if you have trouble locating us.

**Comment by csethna** [comment]
Hey @easherma can you reopen for this week? Thanks 😊

**Comment by derekeder** [comment]
I got ya

**Comment by csethna** [comment]
Thanks!

Cyrus Sethna
about.csethna.com

**Comment by csethna** [comment]
# Lessons Learned from Bureaucracy Busters
## A collaboration with Young Government Leaders [(YGL Chicago)](https://yglchicago.github.io)

### Purpose
The purpose of Bureaucracy Busters was twofold:
1. encourage civic technologists to work together with partners in public service,
- support the [with not for](https://medium.com/organizer-sandbox/building-technology-with-not-for-communities-an-engagement-guide-for-civic-tech-b8880982e65a) principle of civic tech,
2. create a space where government employees feel empowered to attend civic hack nights,
3. serve as a living resource to civic technology projects stymied by red tape.

### Weekly pitch to Chi Hack night
Bureaucracy Busters is a consortium of government employees who strive to support the _with not for_ principle of civic tech.

Please come find us if you're interested in finding a government partner, moving things forward with your government partner, filing a FOIA request, or furthering any interaction with public servants.

### Successes and lessons learned
The breakout group achieved moderate success with at least one curious learner each week since inception. On one occasion, we were able to draw a total of 3 federal employees, a Code for America staffer, an Army veteran, and a curious citizen. While consistently attended, the group never achieved its goal of enabling existing Chi Hack Night breakout groups to have deeper and more meaningful government interactions.

This could have occurred for a variety of reasons:
- breakout groups did not feel sufficiently engaged by Bureaucracy Busters
- breakout groups did not fully understand the role of public service partners in building civic tech projects
- Bureaucracy Busters did not adequately learn about and adapt its purpose to the evolving needs of breakout groups.

Furthermore, government employees were notoriously difficult to engage. In tapping the vast 600+ network of public servants built and maintained by YGL, Bureaucracy Busters was able to generate meaningful interest among 10-15 individuals. Of this group about 3-4 people ever attended Chi Hack Night and none of them returned for a second time.

There are a number of factors which could have contributed to low government partnerships:
- Bureaucracy Busters outreach to membership was not crafted in a way which was accessible to government employees. Email bulletin statistics indicate a higher-than-average open and click-through rate for all emails sent out on behalf of Bureaucracy Busters when compared to general group correspondence.
- Government employees did not feel sufficiently engaged nor motivated to come to a "working event" after work hours.
- civic tech is not perceived as a hobby in the public service community
- "what is civic tech" is still not clear to public servants.

### Moving forward
Bureaucracy Busters is sunsetting for now. The principle organizer, [@csethna](https://github.com/csethna) will be relocating away from Chicago to continue his career in public service in Washington, D.C. While this summary marks the end of Bureaucracy Busters for the time being, I hope to continue efforts to bring career public servants into the civic technology movement. In the future, if Chi Hack Night, or another member of the CfA Brigade Network seeks to address the engagement gap between volunteer technologists and volunteer public servants in our movement, I look forward to collaborating. You can reach me on Slack as *@csethna* or on [Twitter](https://twitter.com/c_sethna).

**Comment by easherma** [comment]
This is a great re-cap, very much appreciated! Sorry to hear you will be
departing our fine city, but looking forward to all the busting you will be
doing in DC!

**Comment by derekeder** [comment]
Thank you for all you do @csethna! 

Godspeed and ... 
![godspeed-gif-10](https://user-images.githubusercontent.com/919583/35014519-6c5e7ef6-fad6-11e7-809a-6ceb72291fd9.gif)
