### ISSUE TITLE
(NOT MEETING THIS WEEK) Magnets how do they work?

### ISSUE THREAD

**Issue by wontruefree** [chihacknight/breakout-groups#128]
### About the group
I am interested in what information we can get from the speakers that come to ChiHackNight and what content we can take from their talk and turn into actions.

### Group leaders
Jack Thorne - @sparrow / @wontruefree

### Who we're looking for
People who are interested in the talk and that came her for the talk or know something about the talk.  Their is no technical requirements but if you are technical we would like to have you to inform the technical possibilities.

### Tools
Brains !!!!

### Relevant Links
ChiHackNight.org

### Where we meet
Couches in the Cafeteria.

### Chi Hack Night slack channel
The [#magnets](http://slackme.chihacknight.org/magnets)

**Comment by wontruefree** [comment]
Not meeting the week of Halloween

**Comment by derekeder** [comment]
@wontruefree meeting tonight?

**Comment by wontruefree** [comment]
No. Does it still say not meeting ?


Cheers,
Jack

**Comment by derekeder** [comment]
I'm going to close it for now. You can re-open when you are meeting next time.
