### ISSUE TITLE
Zombie Datasets

### ISSUE THREAD

**Issue by csethna** [chihacknight/breakout-groups#129]
# Happy Halloween. Welcome to Zombie Datasets.

The goal of this breakout group is to identify **“walking dead”** datasets, defined as: _“publicly available datasets which have been accessed least recently with relation to their peer datasets from the same source.”_

In this exercise, we will be playing [Dr. Robert Neville](http://imlegend.wikia.com/wiki/Robert_Neville_(film)) and treating these datasets as hosts infected with the _Krippin Virus_. This means, unlike zombies from the Robert Kirkman (_Walking Dead_) or Max Brooks (_World War Z_) universes, these “zombie” datasets are capable of being rehabilitated, **with the right use case**.

Upon identification of a zombie dataset, the team will work quickly to administer [GA-series Serum 391, Compound 6](http://imlegend.wikia.com/wiki/Compound_6). This means devising a use case for which the dataset could provide meaningful insights and, time allowing, creating MVP in order to demonstrate a potential application for the data.

- [Least accessed **City of Chicago** public datasets](https://data.cityofchicago.org/browse?limitTo=datasets&page=17)
- [Least accessed **Federal Government** public datasets](https://catalog.data.gov/dataset?page=9899)

### Group leaders
- Cyrus Sethna, `@csethna` on [Slack](https://chihacknight.slack.com).
- We will be on `#zombie-data`.

### Tools
- I'm comfortable in **Python**, learning `Pandas` for this project.
- If you're comfortable with **something else**, that's cool too!
- If you're __completely new__ to data science, it's okay, I've got about 4 days on you. Pros & more experienced folks welcome!

### GitHub
- [Repo](https://github.com/csethna/zombie_data)

### Chi Hack Night slack channel
- Join the [Chi Hack Night Slack](http://slackme.chihacknight.org/) if you haven't already.

**Comment by csethna** [comment]
## Example Problem: The Library
### Discuss: Why is Chicago Public Library data so unpopular?
- [Libraries - 2017 Holds Filled by Location](https://data.cityofchicago.org/dataset/Libraries-2017-Holds-Filled-by-Location/nd85-5bga) --> 58 views
- [Libraries - 2017 Holds Placed by Location](https://data.cityofchicago.org/dataset/Libraries-2017-Holds-Placed-by-Location/m5e9-5598) --> 72 views
- [Libraries - 2017 Computer Sessions by Location](https://data.cityofchicago.org/dataset/Libraries-2017-Computer-Sessions-by-Location/8xex-yi9w) --> 101 views
- [Libraries - 2017 Wi Fi Usage](https://data.cityofchicago.org/dataset/Libraries-2017-Wi-Fi-Usage/5jne-48sf) --> 102 views
- [Libraries - 2017 Circulation by Location](https://data.cityofchicago.org/dataset/Libraries-2017-Circulation-by-Location/ifsu-hcvf) --> 168 views
- [Libraries - 2017 Visitors by Location](https://data.cityofchicago.org/dataset/Libraries-2017-Visitors-by-Location/bk6j-nu5x) --> 211 views
#### Data Science - Can we determine:
##### Beginner
- How many total wi-fi sessions have occurred across all branches so far in 2017?
- Where do most patrons go to use the Internet, _excluding Harold Washington_?
##### Intermediate
- When is the busiest time of year, averaged across all branches?
- How many people place holds but don't pick them up?
- Which branch has the most holds placed that are never retrieved?
##### Advanced
- Based on [2016 wi-fi connection data](https://data.cityofchicago.org/dataset/Libraries-2016-Wi-Fi-Usage/i5v5-n2p5), how many connections might occur in November & December 2017?
- Building upon earlier questions, can we make a visualization of the busiest branches based on aggregate patronage (holds, wi-fi usage, computer sessions, circulation). This can be a graph, chart, map, or word cloud, depending on your interest.

**Comment by csethna** [comment]
# Findings
In this one-time edition of `Zombie Datasets`, we examined two under utilized City of Chicago datasets.
### Datasets examined
1. Chicago Public Library data
2. Chicago Park District - summer movies data
#### Summary
We determined that Chicago Public Library data is underutilized, not because it isn't useful, but because the frequency of updates-- monthly. We also determined that the dataset of movies is very small each year and due to the availability of the movies from other outlets, the use case for individual datasets could be perceived as limited.
#### Use Cases
##### Library
- Looking at `frequency of computer sessions per branch` could determine which branches get more traffic, but is also influenced by other factors such as location, square footage, and availability of public access terminals. A more useful way of examining this data is aggregating it over the course of several years and determining the statistically "busiest" months of the year for computer use. Fields exist to enable determination of peak computer use times by branch. This information is relevant in determining whether or not additional funding should be allocated for more terminals (seeing average capacity compared against maximum capacity). It could also be useful in determining when are the best/ worst times to update software or hardware which might inconvenience the fewest number of patrons.
- Other interesting data available are the `number of holds placed per branch` and the `number of holds fulfilled per branch`. The availability of this data allows us to determine which branches have the highest "flake out" rate among patrons. Using GIS, it is possible to search for a geographic pattern in regards to flakiness, though other factors could contribute to the phenomenon.
##### Movies
- A "what to do in the summer" Twitter bot that pulls movie titles, ratings, and locations from the dataset.
- An analysis of repeated titles over-time. What films to Park District employees most enjoy showing?
- Which parks have shows the most films?
- Is there a geographic bias to which parks are selected for film screenings?
#### Conclusion
The City of Chicago has considerable "zombie data." However, our group was able to determine that even the most underutilized data is not completely useless. In the future, "rehabilitation" of these lesser-accessed datasets could be an interesting project which raises awareness of the breadth of information available on the data portal and showcases the powerful applications and inferences able to be drawn from the application of analysis.

**Comment by stevevance** [comment]
The way I think of zombie datasets is looking at which datasets haven't been updated in a while, and not which ones were accessed the least.

**Comment by csethna** [comment]
Great idea!

Cyrus Sethna
about.csethna.com
