### ISSUE TITLE
SoQL Learning Group

### ISSUE THREAD

**Issue by vingkan** [chihacknight/breakout-groups#132]
## Overview
The Socrata Query Language (SoQL) is a powerful way to find answers to questions you have about the information in open datasets. In this learning group, we play fun games to learn how to use SoQL and explore open datasets from Chicago and beyond!

Every dataset on the city data portal supports SoQL queries. We created a simple interface to let you make requests. Once you get your feet wet with SoQL and open data, you'll have a valuable skill set for any civic tech project!

Everyone is welcome to join our sessions. We usually use a Mob Programming format, so that everyone who attends can participate in the discussion and write whatever amount of code they feel comfortable with.

## Links
* [Chicago City Data Portal](https://data.cityofchicago.org/)
* [What is the Socrata Query Language (SoQL)?](https://dev.socrata.com/docs/queries/)
* [SoQL Query Runner](https://vingkan.github.io/soql/)

## Facilitators
* Vinesh @vingkan (v@hawk.iit.edu)
* Pat @pjsier

**Comment by vingkan** [comment]
To see the first SoQL learning activity, check out the one-time Ghostbusters breakout group (#130) from the ChiHackNight Halloween party!

**Comment by vingkan** [comment]
_Tuesday, November 7th_
## Two Truths and a Lie with the COPA Dataset
The new [COPA Dataset](https://data.cityofchicago.org/Public-Safety/COPA-Cases-Summary/mft5-nfa8/) details complaints received by the Civilian Office of Police Accountability and its predecessor agency. In today's activity, we will pose two truths and one lie about the dataset to the group and use SoQL queries to figure out which is which!

**Comment by vingkan** [comment]
_Tuesday, November 14th_
## Shuffleboard with the Cook County Sweetened Beverage Distributors Dataset
Skills you learn in this learning group transfer to any data portal that uses Socrata! This week, we'll check out the Cook County data portal with the [Sweetened Beverage Distributors Dataset](https://datacatalog.cookcountyil.gov/Finance-Administration/Sweetened-Beverage-Distributors-Registered-with-th/fk38-788k). In today's activity, we'll play a game of shuffleboard... played with Socrata location queries instead of discs. In each round, there is a sweet spot number of distributors and we will work as a group to "capture" those points in one query.

> Round 1: Select 23 McDonald's locations, using the Merchandise Mart as a center point.

> Round 2: Select 17 distributors located on Cermak Road.

> Round 3: Select 5 distributors in Skokie and 3 distributors in Evanston with no distributors from other cities.

You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by stevevance** [comment]
Your SoQL query tester and submitter tool is awesome!

**Comment by vingkan** [comment]
_Tuesday, November 18th_
## Graph Attack with the Potholes Dataset
This week we'll play with data about everyone's favorite urban obstacle: potholes! You can find the [Potholes Dataset](https://data.cityofchicago.org/Service-Requests/311-Service-Requests-Pot-Holes-Reported/7as2-ds3y) on the City of Chicago data portal. In today's activity, we will learn how to write SoQL queries that provide the data for different kinds of graphs. You can do this to create quick visualizations for any dataset on Socrata!

> Round 1: Create a pie chart of recent actions taken on pothole requests from October 2017.

![chart 1](https://user-images.githubusercontent.com/11896652/33343529-3bb5c590-d44b-11e7-90e0-3251d88faffa.png)

> Round 2: Create a line chart of the number of potholes filled by creation date in October 2017.

![chart 2](https://user-images.githubusercontent.com/11896652/33343981-e20cf52a-d44c-11e7-81ba-dea9f3d26401.png)


You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by vingkan** [comment]
_Tuesday, December 5th_
## 20 Questions with the Crimes Dataset
This week we'll play 20 Questions! I'm thinking of a specific case from the city's [dataset of crimes](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2). The records go all the way back to 2001, so you will have to explore the dataset, ask interesting questions, and work together to figure out which one it is. Here are the rules:
1. Only questions with a yes or no answer are allowed.
2. The group must edit and run their query before asking another question.
3. After each question, the person controlling the keyboard rotates.
You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by loudmouse** [comment]
Hey Vinesh!

I got stuck late at the office and couldn’t make the Meetup tonight. Hope you all make some cool stuff! I will def be at the next one. Stay warm and see you then!

**Comment by derekeder** [comment]
this group hasn't met in a while. closing for now.

**Comment by vingkan** [comment]
_Tuesday, May 8th_
## 20 Questions with the Food Inspections Dataset
Aaaaaand we're back for ChiHackNight's 300th episode! This week we'll play 20 Questions! I'm thinking of a specific record from the city's [dataset of food inspections](https://data.cityofchicago.org/Health-Human-Services/Food-Inspections/4ijn-s7e5). As of today, there are over 160,000 entries in this dataset, so you will have to explore the dataset, ask interesting questions, and work together to figure out which one it is. Here are the rules:

1. Only questions with a yes or no answer are allowed.
1. Only four questions can be asked about each column of the dataset.
1. The group must edit and run their query before asking another question.
1. After each question, the person controlling the keyboard rotates.

You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by derekeder** [comment]
Closing for now as its inactive

**Comment by vingkan** [comment]
_Tuesday, February 26th_

## 20 Questions with the Traffic Crashes Dataset

This week we'll play 20 Questions! The topic will be the City of Chicago's open dataset of traffic crashes, released this past summer. I'm thinking of a specific crash from [main traffic crashes dataset](https://data.cityofchicago.org/Transportation/Traffic-Crashes-Crashes/85ca-t3if). As of today, there are over 272,000 entries in this dataset, so you will have to explore the dataset, ask interesting questions, and work together to figure out which one it is. Here are the rules:

1. Only questions with a yes or no answer are allowed.
1. Only four questions can be asked about each column of the dataset.
1. The group must edit and run their query before asking another question.
1. After each question, the person controlling the keyboard rotates.

You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by vingkan** [comment]
_Tuesday, March 12th_
## Two Truths and a Lie with the West Nile Virus (WNV) Mosquito Test Results Dataset
Since this week's ChiHackNight is about public health in Chicago, we will explore the [West Nile Virus (WNV) Mosquito Test Results Dataset](https://data.cityofchicago.org/Health-Human-Services/West-Nile-Virus-WNV-Mosquito-Test-Results/jqe8-8r6s)! The City remains vigilant in the fight against diseases and this dataset provides a look into one under-appreciated initiative in that vein. In today's activity, we will pose two truths and one lie about the dataset to the group and use SoQL queries to figure out which is which. Come see what the buzz is all about!

> "The City has not found mosquitoes that tested positive for West Nile Virus since September 2018."

> "In 2016, most mosquitoes trapped by the City belonged to the species _Culex restuans_."

> "Mosquitoes testing positive for West Nile Virus are most commonly found in the summer."

You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by vingkan** [comment]
I will be gone for the next two weeks. If someone else would like to run this group, please send me an email at v@hawk.iit.edu and I can get you up to speed. It requires a very small time commitment to prepare for each meeting.

I will be back on April 2nd!

**Comment by vingkan** [comment]
_Tuesday, April 2nd_

## Chicago Energy Benchmarking Dataset

This week's activity will explore the [Chicago Energy Benchmarking Dataset](https://data.cityofchicago.org/Environment-Sustainable-Development/Chicago-Energy-Benchmarking/xq83-jr8c), which includes data about energy usage and efficiency of city buildings larger than 50,000 square feet. Although the buildings in this dataset represent less than 1% of all buildings in Chicago, they add up to roughly 20% of the total energy used by the city's buildings. Maybe your school, workplace, or residence is in the dataset!

> Activity to be revealed...

You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by vingkan** [comment]
Not meeting tonight.

If someone else would like to facilitate a session, feel free to send me an email at v@hawk.iit.edu and I can get you up to speed! It requires a very small time commitment to prepare for each meeting.

I will be back on April 16th!

**Comment by vingkan** [comment]
We are gonna play some games to explore the new [rideshare](https://www.chicago.gov/city/en/depts/mayor/press_room/press_releases/2019/april/TransportationNetworkProviderData.html) datasets this week!

**Comment by vingkan** [comment]
_Tuesday, April 23rd_

## Two Truths and a Lie with the Cook County Assessor's Modeling Data

Last week, the Cook County Assessor's Office (CCAO) announced the release of the data and code they use to estimate property values. [This narrative](https://datacatalog.cookcountyil.gov/stories/s/p2kt-hk36) provides more background about the datasets. The dataset called [Modeling Data](https://datacatalog.cookcountyil.gov/Property-Taxation/Cook-County-Assessor-s-Modeling-Data/5pge-nu6u) contains 101,000 records of property sales in Chicago, which the CCAO uses to inform their model's estimates.

We will explore the dataset by figuring out which of these three statements are truthful. There may be more than one lie!

> The only properties with 10 or more full bathrooms are apartments.

> On average, properties designed from an architect's plan sold for twice as much as properties designed from a stock plan.

> Most properties sold for $1 were large lots.

You can start writing queries [here!](https://vingkan.github.io/soql/)

**Comment by vingkan** [comment]
I am not able to run this group because I am no longer in Chicago, but this page lists all of the previous activities for future use. Feel free to reach me at vingkan@gmail.com if you have any questions or want to restart the learning group!
