### ISSUE TITLE
Alderman Coordination Group

### ISSUE THREAD

**Issue by derekeder** [chihacknight/breakout-groups#133]
### About the group
We should be working on projects with the alderman on stuff that is important.

### Group leaders
Asa
Levi
Pavan

### Who we're looking for
At least 1 Alderman
Community Leaders
Constituents
Civic Tech Gurus

### Tools
Brains

**Comment by kwritenow** [comment]
Do yall have any alderman interested in this yet?

**Comment by easherma** [comment]
Appears stale, closing for now.
