### ISSUE TITLE
🎉🎉🎉 The Fun Congress 🎉🎉🎉 

### ISSUE THREAD

**Issue by drevets** [chihacknight/breakout-groups#134]
The Fun Congress plans events for the people of ChiHackNight! 

Several different folks contribute at The Fun Congress. Some regulars include: 

- Scott Garlinger 
- Katie O'Shea
- Isaiah LastName
- Emily Drevets

We need people who like getting other people together to look at each other in the face and HAVE FUN. Note: Non-fun people are welcome to join! 

Help us plan our fun summer! 

You can join us on Slack at #the-fun-congress. 🎊

[Check out the agenda here. ](https://docs.google.com/document/d/1N7urL7Hh5u7vRNSVaMniJegZEwYTyyxfE8aqHdhFn64/edit?usp=sharing)

**Comment by derekeder** [comment]
@drevets this group hasn't met in a while. do you want to keep it open?

**Comment by drevets** [comment]
I think we can close it. The fun, however, will live on. Just not as a
breakout group.

**Comment by derekeder** [comment]
Word!
