### ISSUE TITLE
The Kola Nut Collaborative - Mapping Social Economy Thru Timebanking

### ISSUE THREAD

**Issue by aomuse** [chihacknight/breakout-groups#135]
### About the group
The Kola Nut Collaborative (KNC) is a mutual network of people engaged in reciprocal exchange of services, skills, and goods through a timebank where the currency is an hour of time for everyone.

Through membership in the Kola Nut Collaborative people: create and strengthen community bonds, create economic freedom by providing an alternative means to get needs and desires met, and encourage creativity in redefining self-sufficiency, interdependence and valuation of time.

The Kola Nut Collaborative introduces a paradigm where members reflect on the available resources in their lives moving from a perception of scarcity and lack to abundance and wholeness.

Our timebank was recently established in southeast Chicago with primary objective of promoting and sustaining a robust timebanking infrastructure which supports non-monetary transactions amongst individuals and organizations allowing a greater sum of the realized value of work for be retained and shared within local communities.

We envision that helping communities to map their local assets and take inventory of unmet needs will allow them to make social infrastructure more visible and use a decentralized social matchmaking approach to pair existing assets with unmet needs.

Example:

Problem: Many seniors in our community have decided to age in place in our community. How do we ensure they are not subject to isolation or diminished social engagement?
Solution: Let us organize a senior game night. What are our resources? People? Space? Who is the point of contact that might be able to take inventory of seniors and engage their participation.

The timebank would serve as a central resource where anyone would be able to take stock of the resources which exist in their community and marshal those resources to address issues that exist.

### Group leaders
Mike Strode
connect@kolanutcollab.org

### Who we're looking for
Social Economists, Defenders of Social Commons, Alternative P2P Economic Exchange, Collaborative/Circular Economy Curious, Community Builders, Storytellers

### Tools
Wordpress
Mailchimp
Slack
Law of Two Feet
Time and Talents/Hourworld (exchange platform)

### Relevant Links
Primary Landing Site for Timebank
http://www.kolanutcollab.org

Exchange Platform for Timebank hosted with Hourworld
http://exchange.kolanutcollab.org

[Green Book Half Page wo Offer.pdf](https://github.com/chihacknight/breakout-groups/files/1503810/Green.Book.Half.Page.wo.Offer.pdf)

[Kola Nut Collab One Sheet.pdf](https://github.com/chihacknight/breakout-groups/files/1503811/Kola.Nut.Collab.One.Sheet.pdf)

### Where we meet
Main Room

### Chi Hack Night slack channel
Find us at #kolanutcollab

**Comment by aomuse** [comment]
Although I am generating this breakout group in advance of the November 28th session, I have another engagement for that date and will not be in attendance at the session. Interested parties who wished to hear from the breakout can anticipate my attendance a the following Chi Hack Night or reach out via email for more information.

**Comment by derekeder** [comment]
@aomuse is this group planning on meeting next week? If not, lets close it until you're back

**Comment by aomuse** [comment]
@derekeder Group met last night as well as the week prior. We were also in the breakout announcements for both weeks.

**Comment by derekeder** [comment]
Ah - sorry I must have missed it! Carry on!

**Comment by derekeder** [comment]
hi @aomuse  - is this breakout group still active & meeting at Chi Hack Night?

**Comment by derekeder** [comment]
Closing for now as we haven't seen you in a while to keep the list up to date. Feel free to reopen if you think this is a mistake or when you come back!
