### ISSUE TITLE
World's Fair 2018 ~ Hack Utopia

### ISSUE THREAD

**Issue by performtransform** [chihacknight/breakout-groups#136]
### About the group
PERFORM/TRANSFORM: the World's Fair brings people together to build utopia in 2018. Hackers, artists, organizers, teachers, and lovers of all kinds are invited to share ideas and submit project proposals. The fair launches January 13th and culminates with a Utopia Expo in June. 

### Group leaders
Sasha Tycko 
Plus Sign
Contact us at nomoneynoborders@gmail.com

### Who we're looking for
Anyone interested in: art, entertainment, technology, & community organizing, creative tools for resource-sharing and community infrastructure, or building utopia! And anyone interested in submitting a project proposal for the World's Fair Expo in June. 

An example of projects already underway are #10Gardens: an initiative by Chicago Patchwork Farms & Cooperation Operation to provide 10 new community gardens with funding & support, and #100Venues: a proposal by F12Network and OurMusicMyBody to bring comprehensive sexual violence prevention programming to 100 venues in 2018.

### Tools
We don't have a lot of programming experience and are looking to connect with people who do!

### Relevant Links
www.nomoneynoborders.com (a more robust version of the website will launch January 13th)
[World's Fair application](https://goo.gl/forms/WRCdY8Vr4UnLIOq93)
Search #nomoneynoborders on all social media sites

### Where we meet
The cafeteria

### Slack channel
worlds-fair-2018

**Comment by stevevance** [comment]
Where is the world's fair?

**Comment by performtransform** [comment]
Various locations in Chicago!

**Comment by kwritenow** [comment]
Heya! What exactly is happening on the 13th? 

There are probably a good number of existing hack night projects that might be relevant, and if I know a bit more about how they might jump in, I could put you in touch.

**Comment by performtransform** [comment]
@kwritenow Hiya! So two things happen on the 13th: 
-There is a launch party/fundraiser event at [DFBRL8R gallery](https://dfbrl8r.org/) for the World's Fair called the Utopia Ball, which will include a "Designing Utopia" panel discussion followed by music & dancing. Details are [here](https://www.nomoneynoborders.com/utopia-ball) and the FB event is [here](https://www.facebook.com/events/1966571626947233/). 
-Applications for the six-month fair open on the website (www.nomoneynoborders.com)! The fair culminates in a week-long Utopian Expo in June. We definitely encourage folks who are already working on community building-oriented projects to apply. 

Hope that answers your question! After January 13th there will be a lot more info and ways to interact on the website. People can also get in touch via nomoneynoborders@gmail.com :)

**Comment by derekeder** [comment]
this event has happened. closing
