### ISSUE TITLE
SECURE ALL THE THINGS

### ISSUE THREAD

**Issue by activechild** [chihacknight/breakout-groups#138]
### About the group
We are a group of security professionals that want to help you consider security vulnerabilities for your project and help more mature projects create security policies and, if you want, a confidential and passive security test of your applications. FOR FREE

### Group leaders
Jeremiah Tillman @jeremiahtillman on Twitter

### Who we're looking for
Anyone who wants to learn more about securing themselves and their projects in ways that won’t break the bank or inconvenience anyone.

### Tools
We mainly use Kali Linux and security onion. And libreoffice for documentation.

### Relevant Links
Walk on in if you see that we’re lonely or schedule some time with us at securitay.jeremiahtillman.com

### Where we meet
Where in the Braintree office do you meet? Hopefully we can meet in one of the meeting rooms. :)

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/Securitay

**Comment by easherma** [comment]
@activechild  is this project still active? We'd love an update, and let us know if you have any problems we can help address!
