### ISSUE TITLE
Compassion It!

### ISSUE THREAD

**Issue by BPCompassion** [chihacknight/breakout-groups#141]
### About the group
Compassion It is a 501(c)3 nonprofit organization and global movement whose mission is to inspire daily compassionate actions and attitudes. We envision a day when compassion is practiced by every person, for every person, on every day. We would like to inspire compassion in Chicago. 

https://compassionit.com/compassion-it-chicago/

### Group leaders
Burrell Poe
Director of Compassion It Chicago (volunteer)
burrellpoe@compassionit.com

### Who we're looking for
We need coders who can develop a prototype of a very simple way to track compassionate actions. We would like people interested in a social movement.

### Tools
None

### Relevant Links
https://compassionit.com/compassion-it-chicago/

### Where we meet
The cafeteria

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by easherma** [comment]
@BPCompassion is this project still active? We'd love an update, and let us know if you have any problems we can help address!
