### ISSUE TITLE
In2It Chicago

### ISSUE THREAD

**Issue by lydiajessup** [chihacknight/breakout-groups#142]
### About the group
**Problem:** Despite the desire that many people have to contribute to the (civic) life of their community, they sometimes aren’t sure how. 

**Solution:** We believe civic technology tools can enable people to more easily and more effectively engage with civic life - and help all of us work together to make our democracy vibrant, active, just and truly representative. So we are creating a platform (app or website TBD) to encourage active and informed civic engagement. People will be able to search for civic events using filters, read info on them, and commit to attending. The next phase of the project will add other functionality such as community pages and a “civic health tracker” so that people will also be able see their personal calendars, past activity and stats, and set their personal interests and goals.

**Inspiration for the name + project:** The name was inspired by part of President Barack Obama's Farewell address:

_“Ultimately, that’s what our democracy demands. It needs you. Not just when there’s an election, not just when your own narrow interest is at stake, but over the full span of a lifetime. If you’re tired of arguing with strangers on the Internet, try to talk with one in real life. If something needs fixing, lace up your shoes and do some organizing. If you’re disappointed by your elected officials, grab a **clipboard**, get some signatures, and run for office yourself. Show up. Dive in. Persevere.”_ 

**We are currently collecting information on civic engagement through a survey. You can take the survey here: http://bit.ly/clipboardsurvey** 

### Group leaders
Lydia Jessup

### Who we're looking for
People who like/are interested in/good at:
- web scraping in Python
- website and/or app development in Django 
- UX/UI
- engaging with community groups and organizations
- knowledgeable about social science theory and literature on civic engagement/participation, behavioral economics, sociology (especially collective efficacy)
- care about civic engagement/community participation (which hopefully is everyone at Chi Hack Night 😄 )

### Tools
Currently using Python for web scraping and Django for website development

### Relevant Links
Coming soon...

### Where we meet
Cafeteria/Flipping tables room

### Chi Hack Night slack channel
You can find us at "the-clipboard-project" and "clipboard-tech" for the dev side

**Comment by WesThorburn** [comment]
Hey, I'm a software developer and I'd like to get involved. I'll keep an eye out for this group's introduction this evening!

**Comment by lydiajessup** [comment]
Hi Wes - Great! Looking forward to meeting you tonight!

**Comment by WesThorburn** [comment]
I'm so sorry to do this, but I can't make hack night tonight. Count me in for the 20th though!

**Comment by WesThorburn** [comment]
Repo link for contributors: https://github.com/ClipboardProject/ClipboardApp

**Comment by jwilliamsciv** [comment]
Thanks for letting me listen in tonight on the work being done.  As I listened more, I understood better that an academic definition of 'civic engagement' might not be necessary or interesting (i.e. you might be using Potter Stewart's method of identifying civic engagement...).  Still, if it would be helpful:

- Robert Putnam's book "Bowling Alone" cites a survey of American civic engagement.  Take a look at questions 1 - 3 in section III [here](http://bowlingalone.com/?page_id=7).
- A team of established nonprofits created a report on Chicago's civic engagement health in 2010, found [here](https://ncoc.org/wp-content/uploads/2015/04/2010ChicagoCHI.pdf).
- An earlier study from 2002, containing a checklist of examples of civic engagement.  Look particularly at page 7 for a list of activities, [here](https://www.civicyouth.org/research/products/Civic_Political_Health.pdf).  The authors sometimes exhibit a reactionary/traditional slant but their research is thorough

**Comment by geneorama** [comment]
Hey, there is a gallery in Chicago called Intuit. It’s a little confusing having a group with the same name. 

https://www.art.org/

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
