### ISSUE TITLE
Jobs by Neighborhood

### ISSUE THREAD

**Issue by aleenaagrawal** [chihacknight/breakout-groups#143]
### About the group
The goal of this group is to create a map-based platform to quantify and locate entry-level jobs for each of Chicago's 77 neighborhoods, in order to boost access to local jobs and allow civic leaders to understand hyper-local economic development opportunities. 

### Group leaders
Aleena - feel free to Slack me! 

### Who we're looking for
We're looking for those that can help develop this map, identify databases of entry-level jobs we can utilize, and define the characteristics we want to quantify per neighborhood. Developers, designers, and thinkers of all industries are welcome! 

### Tools
TBD

### Relevant Links
Great sites to guide our decision-making: 
http://siteselector.worldbusinesschicago.com/
https://maps.cookcountyil.gov/connecttocook/

### Where we meet
TBD

### Chi Hack Night slack channel
#jobs-by-neighborhood

**Comment by easherma** [comment]
This group pivoted away a bit from scraping existing sources of jobs data to creating a platform for people to post jobs in their neighborhood via partnering with local chambers of commerce.

**Comment by easherma** [comment]
Still working towards a basic MVP with a map and way to post jobs.

**Comment by easherma** [comment]
Scraping data was considered, but data quality is a concern as well as acceptable sources.

**Comment by jamienj89** [comment]
Hey there- is this idea still active? Really interested in it!

**Comment by derekeder** [comment]
hi @jamienj89  - is this breakout group still active & meeting at Chi Hack Night?
