### ISSUE TITLE
we all live here 

### ISSUE THREAD

**Issue by wealllivehere** [chihacknight/breakout-groups#144]
we all live here (wealllivehereproject.com) uses art, community, and technology to remind people to get along and help each other succeed. Our ACT program works with schools, parks, libraries, and community groups to make public art using our positive and inclusive phrase as a theme.

Specifically we are looking to develop a web-based mobile complement to this project in the West Loop:

http://wgntv.com/2017/09/19/community-art-project-sets-out-to-make-massive-mural-one-pixel-at-a-time/

Rich Alapack, founder
rich@wealllivehereproject.com
773.322.6851

Broadly speaking, we are creating a platform for people to work with schools using their own superpowers. This will give students the chance to see people that love what they do in action. Our projects are different at each place we work and we want people who are curious to see how their mastery of technology can be applied to make the projects that much more interesting for kids k-12. 

Specifically, we have a project in the West Loop where we are looking to enhance a community produced mural (already built) with a digital complement.

http://wgntv.com/2017/09/19/community-art-project-sets-out-to-make-massive-mural-one-pixel-at-a-time/

We are looking for a mobile optimized web based site (unless your expertise tells us otherwise) so that this mural can be experienced and interacted with globally. What I mean by that, is we want people walking by to be able to pull out their phone, visit a site, spin the digitally rendered planet, stop it, and then add their name and home town so that the planet starts to gain a population. Uptake will then help us analyze the data to show when our planet gets people from each continent, country, city, etc. 

Microsoft and Uptake are partners for this initiative.

Let’s get to know each other in the Braintree Cafeteria tonight. Beyond tonight we will likely meet in our space at 625 N. Kingsbury where we share space with some amazing civic non-profits like Archeworks and The Chicago Public Housing Museum. Alternatively we could also meet at UI Labs.

### Chi Hack Night slack channel
how do I set this up?

**Comment by easherma** [comment]
@wealllivehere is this project still active? We'd love an update, and let us know if you have any problems we can help address!

**Comment by wealllivehere** [comment]
I think I screwed up the offering for this. I do still need help but I didn’t know if this was published or not. What’s a more effective way for me to drum up interest?

Rich Alapack
rich@weallivehereproject.com
773.322.6851
