### ISSUE TITLE
CCSAO Open Data Discussion Group

### ISSUE THREAD

**Issue by msaniie** [chihacknight/breakout-groups#145]
### About the group
This is a discussion group to meet and discuss the data that the Cook County State's Attorney is planning to release and get into the weeds about how to use it. 

### Group leaders
Matthew Saniie - Matthew.Saniie@cookcountyil.gov

### Who we're looking for
We are looking for people interested in open data and criminal justice.

### Tools
We will be using our brains and our mouths. Matthew will provide a print out of the draft data dictionary.

### Relevant Links
N/A

### Where we meet
TBD

### Chi Hack Night slack channel
None

**Comment by easherma** [comment]
Closing for now, feel free to update us if/when the project is still active or if you need any help!
