### ISSUE TITLE
Learn Data Science for Social Good

### ISSUE THREAD

**Issue by TananK** [chihacknight/breakout-groups#147]
### About the group

We are a group of data enthusiasts who want enhance skills in data science, analytics, visualization, and mining by working on publicly-available data in order to understand and take actions on issues in the community of Chicago.  There are three topics that we discuss in each meeting:

- Social issues that can be tackled using open data
- Current data science competitions to participate
- Online resources to enhance skills in data science 

After a round of introduction and a general discussion around the three topics, we may break into sub-group to focus on each topic of interest such as; finding open data that could be used to tackle public issues, working on data science competition as a team, or learning new data science technologies or method together. 

Relevant links for each topics are as followed:

#### Open / Public Data
data.cityofchicago.org
datacatalog.cookcountyil.gov
www.data.gov
www.census.gov
datausa.io
www.usa.gov
www.healthdata.gov

#### Data Science Competitions
www.kaggle.com
www.drivendata.org
www.olgatsubiks.com/data-for-a-cause
www.datakind.org/
www.dataanalystsforsocialgood.com/

#### Online Learning Resource
www.coursera.org
www.lynda.com
www.fast.ai
www.edx.org
www.udemy.com
www.datasciencecentral.com/

### Tools
Jupyter notebook, R studio, Python

### Facebook Group
https://www.facebook.com/groups/1796524403986276/

### Where we meet
In the cafeteria

### Chi Hack Night slack channel
#data-sci-competition

### Group leaders
Tanan Kesornbua - mrxstudio10@gmail.com
Mak Hozo - makhozo@gmail.com

**Comment by derekeder** [comment]
Closing for now as we haven't seen you in a while to keep the list up to date. Feel free to reopen if you think this is a mistake or when you come back!
