### ISSUE TITLE
Panacea Fintech

### ISSUE THREAD

**Issue by lyndonbjackson** [chihacknight/breakout-groups#149]
### About the group
Mobile app that allows EBT (Electronic Benefit Transfer) users to check their balance and transaction history on their smartphones.

### Group leaders
Lyndon Jackson email: lyndon@panacea-company.com

### Who we're looking for
Developers, people who have experience scraping, data analysts, designers welcome too.  
### Tools
We've scraped the state's food stamp website to build the first version of the app. 

### Relevant Links
panacea-company.com

https://www.wired.com/story/startups-are-finally-taking-on-food-stamps/###
 Where we meet
The cafeteria. 

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by easherma** [comment]
@lyndonbjackson is this project still active? We'd love an update, and let us know if you have any problems we can help address!
