### ISSUE TITLE
Mapping the Demand for Better Transit

### ISSUE THREAD

**Issue by ChicagoStreetcar** [chihacknight/breakout-groups#15]
We’re mapping the density of people sitting on buses throughout the city in order to show where there’s enough riders per mile to warrant upgrading from buses stuck in traffic to something better—like a bus lane, bus rapid transit, or light rail.

The premise is that **transit service upgrades are warranted where (a) ridership is highest, (b) congestion is worst, and (c) the percentage of street users on transit is highest**. So other factors we're mapping include traffic congestion (to determine how much transit riders are being delayed by car traffic) and car counts (to determine the "mode share" of transit riders vs. drivers) for every street segment that has a bus route.

The purpose is to provide a data-based background for public policy decisions regarding the configuration of streets. Where congestion is bad, it's important to configure the streets to optimize the flow of people, which may mean prioritizing space-efficient transit over cars in a few key places. We're trying to identify the low-hanging fruit of public investment in transit upgrades: **where can an improvement save the most people the most time, and do the most to expand the capacity of our congested transportation infrastructure?**

Group leaders:
**John Krause** (organizer): jck@chicagostreetcar.com, slack: @johnkrause
**Tristan Crockett** (programming): tristan.h.crockett@gmail.com, slack: @thcrock

Who we're looking for | Tools we're using:
Open Source Routing Machine for snapping GPS data to OpenStreetMap.
GTFS shapefiles (transit operating plan and route data).
GIS for mapping data.
Leaflet or other online mapping.
Graphics and visual communications.
Web developer
Urban planning, transit planning, traffic planning

**Comment by ChicagoStreetcar** [comment]
Why???

John Krause, Executive Director
Chicago Streetcar Renaissance
3440 N Lake Shore Drive  No 10G
Chicago, IL  60657
+1 312 810 1525
chicagostreetcar.com

**Comment by derekeder** [comment]
@ChicagoStreetcar your group was closed because no one from it was meeting tonight. Next time your group meets, you can reopen the group.

**Comment by ChicagoStreetcar** [comment]
Between now and then people will go to the website to learn about the breakout groups and find the project I invited them to work on is now closed. Just keep it open please. Let us close it if we decide to abandon the project.

John Krause, Executive Director
Chicago Streetcar Renaissance
3440 N Lake Shore Drive  No 10G
Chicago, IL  60657
+1 312 810 1525
chicagostreetcar.com

**Comment by derekeder** [comment]
@ChicagoStreetcar the goal of this policy is to show an up-to-date list of the breakout groups that are happening at the current hack night. no one said they were working on this group, so it was closed. are you sending people to this page in contexts outside of Chi Hack Night?

**Comment by ChicagoStreetcar** [comment]
Yes, of course. I often invite people I meet to come to Hack Night. I got an email a couple weeks ago from someone saying they went to the site but couldn't find the breakout group I told them about. Look, there are a lot of us working on that project outside of Hack Night now. We come to Hack Night to get advice from others, meet new people, etc. but almost all the work is done outside. I'm talking especially about Tristan. Closing the group when we don't meet misses the larger benefit of ChiHackNight as a launch pad, or maybe a tethering point, for projects that go way beyond Tuesday night.

John Krause, Executive Director
Chicago Streetcar Renaissance
3440 N Lake Shore Drive  No 10G
Chicago, IL  60657
+1 312 810 1525
chicagostreetcar.com

**Comment by derekeder** [comment]
Ok, I hear that. I would suggest you document your project using another platform like Google Docs, GitHub, your own website and point people there between hack nights. Other groups also have additional pages like this, and it seems to help with on-boarding quite a bit.

I'll reiterate that this list is for the in-person event and for listing the breakout groups that are meeting that night. We apply the same policy to all groups. 

We'll take your feedback into consideration. This is new way of managing breakout groups is still experimental, and there are still some kinks with it. For example, the 'Closed' label is definetly not ideal for how we are using it and does give off the impression that the group has disbanded, when in fact it just means they didn't meet last week.

**Comment by ChicagoStreetcar** [comment]
I do link to Hack Night and to the project I started there on the Chicago Streetcar website: http://www.chicagostreetcar.com/#!mapping-the-demand/vpvb7

But I try to keep Hack Night and the streetcar project separate: one is about using civic tech to visualize data, the other is about rebuilding the city around rapid transit, safe cycling, and local shopping. I like sending people to the Hack Night website to get involved in civic tech without asking them to work on the streetcar project. In terms of the Tuesday night event, it's great to have a site where people can learn about all the different projects they can get involved in—not just the ones that met last week.

John Krause, Executive Director
Chicago Streetcar Renaissance
3440 N Lake Shore Drive  No 10G
Chicago, IL  60657
+1 312 810 1525
chicagostreetcar.com

**Comment by csethna** [comment]
Hey @ChicagoStreetcar, I checked out your website and am interested in learning more about how I can get involved with this project at the next Chi Hack Night!

**Comment by ChicagoStreetcar** [comment]
I’ll be out of town on vacation next week, Aug 2, but should be around for Tuesday the 9th.
Looking forward to meeting you.

John Krause, Executive Director
Chicago Streetcar Renaissance
3440 N Lake Shore Drive  No 10G
Chicago, IL  60657
+1 312 810 1525
chicagostreetcar.com <http://www.chicagostreetcar.com/>

**Comment by csethna** [comment]
Sounds wonderful! Thanks for the reply!

**Comment by derekeder** [comment]
haven't seen y'all in a while. will reopen next time we see you!

**Comment by ChicagoStreetcar** [comment]
No problem. Tristan is working on it on his own, with occasional input from others. Well come in an reopen when there's stuff for others to work on. 

John Krause
Executive Director
Chicago Streetcar Renaissance
chicagostreetcar.com

**Comment by derekeder** [comment]
Sounds good!
