### ISSUE TITLE
Competency Collection 

### ISSUE THREAD

**Issue by Woodenrings** [chihacknight/breakout-groups#150]
### About the group
A high level overview of your breakout group. What problem are you trying to solve? Make this simple and jargon-free. Links are good too!

I want to build a light, flexible, streamlined application to track competencies in non-traditional  educational spaces.

### Group leaders
Names and contact info for the people running this group.
Ramah Malebranche ramahjihan@gmail.com 773.899.6558

### Who we're looking for
Describe the kinds of people who would be good for your group. Include the skills, domain knowledge and interests that will help make your project succeed.
I seek other educators, full-stack application designers, web developers, and UX Designers

### Tools
Describe the tools that you are using.
So far, Google suite, Trello, and a dream.

### Relevant Links
Any relevant links, e.g. a github repo, a demo site

### Where we meet
Where in the Braintree office do you meet? Flipping Tables? The cafeteria?
We should meet in the "Focus Rooms 1-3."

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by easherma** [comment]
@Woodenrings  is this project still active? We'd love an update, and let us know if you have any problems we can help address!
