### ISSUE TITLE
Chicago Books to Women in Prison

### ISSUE THREAD

**Issue by isaacdtaylor** [chihacknight/breakout-groups#151]
### About the group
[Chicago Books to Women in Prison](https://chicagobwp.org/) is a nonprofit that matches donated books to specific requests from incarcerated women across the United States. Self-care, Fiction, Nonfiction, and Educational books are requested but other than what's on the shelves, there isn't much tracking or inventory optimization.

We are working to explore a database solution with combining an ISBN-database app in order to help match end-users with the right books and reduce shipping costs.

### Group leaders
Names and contact info for the people running this group.
Vicki White: vicki.white@gmail.com
Mieko Furuhashi: moc.mieko@okeim.com
Claire Micklin: claire.micklin@gmail.com

### Who we're looking for
Anyone is welcome to join! This is a very beginner friendly project for anyone who wants to learn.

### Tools
Google Sheets, Google App Scripts, HTML, CSS

### Relevant Links
[View our Google Group:](https://groups.google.com/forum/?hl=en#!forum/books-to-women-in-prison) 
[GitHub Repo:](https://github.com/chihacknight/books-to-women-in-prison)

### Where we meet
Focus 02

### Chi Hack Night slack channel
#bookstowomeninprison

**Comment by derekeder** [comment]
@miekof is this group still active at Chi Hack Night?

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
