### ISSUE TITLE
Urban Ag Resource Hub

### ISSUE THREAD

**Issue by AUAChicago** [chihacknight/breakout-groups#153]
### About the group
Chicago's urban farmers and gardeners lack a central platform for resource sharing. We are looking to develop a simple Craiglist/classified ad style website. The key functionality is that anyone can post opportunities to it. We know there's a lot of already made systems out there - just looking for insight on the best one!

### Group leaders
Nick Lucas, 847-849-3905, Advocates for Urban Agriculture
Katie Williams, Chicago Patchwork Farms

### Who we're looking for
Anyone with insight on what we're trying to develop

### Tools
Website?

### Relevant Links
This is an initiative of Advocates for Urban Agriculture (www.auachicago.org) and Patchwork Farms (www.chicagopatchworkfarms.com)
We found some good stuff when we googled "how do I make a simple Craigslist-style website."

### Where we meet
TBD

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by easherma** [comment]
AUA current assets:
listserv/google group
people go to jobs posting on AUA

con: 
no way to tag/filter
facebook page
way to migrate/scrape/translate listserv post

**Comment by AUAChicago** [comment]
The research continues!

**Comment by derekeder** [comment]
hi @AUAChicago  - is this breakout group still active & meeting at Chi Hack Night?

**Comment by derekeder** [comment]
closing for now. feel free to reopen!
