### ISSUE TITLE
Tech workers discussion group

### ISSUE THREAD

**Issue by meshulam** [chihacknight/breakout-groups#155]
### About the group
The Tech Workers Discussion Group is for developers, designers, support, and other tech-adjacent workers to come together and talk about their workplace conditions, current issues in the tech industry, and society at large.

We'll do this with a workers inquiry discussion, which allows workers to share their experiences and connect them to broader societal issues. We'll also discuss hot button tech workers issues such as data privacy, sexual harassment, and the gig economy. 

### Group leaders
Melissa McEwen (@melissamcewen on Slack)
Matt Meshulam (@meshulam on Slack)

### Who we're looking for
Tech workers or aspiring tech workers interested in talking about workplace conditions and the ethical implications of the products we build.

### Tools
Just our brains and voices. 

### Relevant Links
https://techworkerscoalition.org/
http://notesfrombelow.org/article/tech-workers-platform-workers-and-workers-inquiry

### Where we meet
Where in the Braintree office do you meet? Flipping Tables? The cafeteria?

### Chi Hack Night slack channel
The #tech-workers-talk channel on the [Chi Hack Night Slack](http://slackme.chihacknight.org/)

**Comment by derekeder** [comment]
hi @meshulam - is this breakout group still active & meeting at Chi Hack Night?

**Comment by meshulam** [comment]
We're not currently active, I'll close it for now.
