### ISSUE TITLE
How a Bill Becomes Law ( State Matters working group ) 

### ISSUE THREAD

**Issue by easherma** [chihacknight/breakout-groups#156]
### About the group

State Matters is an education tool that connects people to state and local government through simple communication and engaging content that helps people understand how state government works.

We’ll be covering topics such as how state budget works, the pension crisis, what the powers of the State Government are, and explaining (in non-partisan terms) the most impactful bills proposed during the Illinois legislative session.

As part of this, we want to make an interactive visualization about how bills become laws at the state level. We want to get creative with this content to make it relevant and fun: this can include making a game that users can play to learn more about the legislative process and get a feel for how it works. 

### Group leaders
Kacie Smith ~ kacie@statematters.org
Eric Sherman ~ ericandrewsherman@gmail.com

### Who we're looking for
Domain Knowledge experts, testers, everyday people who want to know more about the Illinois legislative process, game designers, makers, and players, and people who code or want to learn how to code!

### Tools
The upcoming website is built using Contentful and React, but we are open to a wide variety of options/tools for this project, with a preference for open source tools. 

### Relevant Links
https://github.com/state-matters/bills-to-laws <-- repo for project docs and output 
statematters.org <-- landing page for org (full site coming soon!)

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights.

State Matters also has a slack. Talk to Kacie for access!

**Comment by derekeder** [comment]
Related, Bob Dorough, who created [Schoolhouse Rock](https://www.youtube.com/watch?v=tyeJ55o3El0), died today.

https://www.cnn.com/2018/04/24/us/schoolhouse-rock-creator-died-trnd/index.html

**Comment by easherma** [comment]
Initial v1 will be a walkthrough of the bill process with little interactivity. We are cooking up some concepts for games, with the goal being to play test without writing any code first!

**Comment by easherma** [comment]
Hey, what good is an interactive visualization if you don't have a website to put it on?

We're working hard on https://github.com/state-matters , in advance of our launch party on the 27th!

**Comment by derekeder** [comment]
hi @easherma - is this breakout group still active & meeting at Chi Hack Night?

**Comment by derekeder** [comment]
closing for now. feel free to reopen!
