### ISSUE TITLE
Fundraising for Chi Hack Night!

### ISSUE THREAD

**Issue by easherma** [chihacknight/breakout-groups#157]
### About the group
We're about $14k short for funding for this year. To date, the vast majority of our funding is from corporate sponsors. Lets put our heads together and expand our pool of asks through personal relationships and other connections.

### Group leaders
Eric Sherman 
Derek Eder ( by proxy )

### Who we're looking for
Anyone! Our tools are primarily phone and email and elbow grease!

### Tools
Describe the tools that you are using.

### Relevant Links
Sponsorship overview document: [Chi Hack Night - 2018 Sponsorship Overview.pdf](https://github.com/chihacknight/breakout-groups/files/2010667/Chi.Hack.Night.-.2018.Sponsorship.Overview.pdf)

**Comment by stevevance** [comment]
Why are we short this year? Were there some sponsors from previous years that didn't renew? Or did some sponsors renew at lower levels?

**Comment by easherma** [comment]
Both.

**Comment by derekeder** [comment]
Here are some things that people can help out with for Chi Hack Night fundraising:

1. Join our `#fundraising-for-chn` Slack Channel (join our slack here: http://slackme.chihacknight.org/)

2. If you work for or have a personal contact at a company or organization that might be interested in being a Chi Hack Night sponsor, let us know about them in the `#fundraising-for-chn` Slack channel. You can also share our Sponsorship Overview: [Chi Hack Night - 2018 Sponsorship Overview.pdf](https://github.com/chihacknight/breakout-groups/files/2010667/Chi.Hack.Night.-.2018.Sponsorship.Overview.pdf)

3. If you have suggestions on ways we can make Chi Hack Night more attractive to potential sponsors, suggest them to us in the `#fundraising-for-chn` Slack channel.

**Comment by derekeder** [comment]
Closing this for now
