### ISSUE TITLE
Freedom Of Information Act

### ISSUE THREAD

**Issue by red-bin** [chihacknight/breakout-groups#158]
### About the group
A significant portion of the data that is used in data analytics within data civics comes from requests to our local government through the Freedom of Information Act.  This group hopes to teach and submit digitally-oriented FOIA requests.

### Group leaders
Matt Chapman - Free Our Info, NFP.

### Who we're looking for
Civic hackers, journalists, students, data folk.

### Tools
Muckrock.com, our own tools.

### Where we meet
Cafeteria

### Requesting database schemas from Chicago:
To expand the amount of data that is open to Chicago's civic data communities, it's essential to understand what data exists.  With most data existing in SQL databases or similar, a great way towards this understanding is through a database's schema.  With a database schema, it becomes possible to submit further FOIA requests using hand-crafted SQL, which vastly opens up the information available to the public. The advantage of specifically requesting information through SQL is that it can significantly ease the burden of governmental staff by limiting their requirements to review and redact information.

#### Status
1. Chicago has rejected a request for DBMS schemas by citing 5 ILCS 140/7(1)(o), which exempts "Technical information associated with automated data processing operations". 
2. A separate request for Chicago's "Metalicious" database, which includes the schemas of 13 other databases has been released. This shows that #1 can be requested, as metalicious's database is essentially an index of Chicago's database.
3. A request has been sent to Chicago's Department of Finance for a database schema of CANVAS, which is an Oracle 11g database for storing parking tickets and their associated financial information.

#### Todo
1. Draft request for database schemas again, but more formalized and with smaller scope.
2. Submit requests for data using database schemas from datadictionary.
3. Parse through Chicago's RFPs for database schemas info.

### Staff listing of Chicago using ldap query tools
We will be working on writing an ldapquery for requesting Chicago's staff list and their associated information (eg, phone numbers, title, leadership).

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) - #FOIA channel.

**Comment by derekeder** [comment]
@red-bin  Looks like this group is no longer active. Closing for now. Feel free to reopen if you want to start it back up again!
