### ISSUE TITLE
Equity Network

### ISSUE THREAD

**Issue by equitynetwork** [chihacknight/breakout-groups#159]
### About the group
My company Equity Network is creating a product that essentially leverages small businesses and nonprofits by streamlining their projects to professionals on our open source platform that is underlined by blockchain technology to validate skills and reward users for each project completed we then source the top tier users to corporate and executive partners for recruitment.  This platform is the beginning of a economic revolution where students, veterans, and even stay at home moms may find hidden talents and become a real life professional.

### Group leaders
Founder - Astin Simmons networkequity@gmail.com (708.646.8283)
Lead Front-End - Kevin Williams jr kwilliams@icstars.com (773.263.2735)

### Who we're looking for
We are looking for developers, UXUI Designers, graphic designers, community leaders, and more.

### Tools
Bring your laptops, bring your pen & paper, and a fresh mind full of ideas.

### Relevant Links
www.equitynetwork.co 

### Where we meet
In the Cafeteria on the BIG COMFY COUCH!

### Chi Hack Night slack channel
https://chihacknight.slack.com/messages/CANLS2MAB/

**Comment by derekeder** [comment]
hi @equitynetwork  - is this breakout group still active & meeting at Chi Hack Night?

**Comment by derekeder** [comment]
closing for now. feel free to reopen!
