### ISSUE TITLE
Chicago's Own Virtual Assistant - 311 Requests, Transit Arrival Times, and More

### ISSUE THREAD

**Issue by vidal-anguiano** [chihacknight/breakout-groups#160]
### About the group
Municipal governments are implementing virtual assistant (Alexa Skills, Google Assistant, Siri, etc.) 
applications for a number of city services including submitting 311 requests, requesting city attraction hours, and more. Just this past May, [Albuquerque soft-launched an Alexa Skill](https://www.kob.com/albuquerque-news/amazon-alexa-albuquerque-311-service/4922025/) that takes basic 311 service requests, freeing up call center agents to take more complex inquiries. There is no reason Chicago shouldn't have it's own. 

More than just ushering Chicago's city services into the 21st century, there is a real opportunity to help Chicago improve call center operational efficiencies, save Chicagoans time on otherwise burdensome processes, and offer a wide spectrum of functionalities that will improve the resident experience.

### Group leaders
**Vidal Anguiano**  - [Email](vidal.anguiano@gmail.com) - [LinkedIn](https://www.linkedin.com/in/vidalanguiano/)  
*Harris School of Public Policy, Masters in Computational Analysis and Public Policy '19*  

Seeking a partner with experience in product management, strategic partnership development, and/or software development management

### Who we're looking for
**Conversational UX Designer**
**Experienced Full-Stack Developer(s)** 
**Solutions Architect:** Someone who is able to explore and compare different tech solutions and devise the appropriate tech stack
**Everyday Chicago Residents:** There are many potential functionalities for a virtual assistant. Help us come up with ideas that will make Chicago a more inclusive and accessible place to live.

### Tools
Our [working prototype](http://chicago-311-agent.herokuapp.com/) was built using Google Cloud Platform's [DialogFlow](https://dialogflow.com/) and is integrated with Google Maps API, [City of Chicago Open 311](http://dev.cityofchicago.org/docs/open311/), a PostgreSQL database, all pulled together with a Python web application hosted on [Heroku](heroku.com).

### Relevant Links
Two classmates and I [developed a prototype](http://chicago-311-agent.herokuapp.com/) for a class project. Currently, it is purely text based, but can easily be integrated with voice functionality. It can handle 311 requests for potholes, street lights that are out, and rodent sightings. The repo for our class project can be found [here](https://github.com/civicchifecta/311-agent).

### Where we meet
I'll be introducing the project on June 12th, 2018 and again on June 19th. Meeting location within Braintree  is TBD.

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. Find us on the **#chivirtualassistant** channel!

**Comment by derekeder** [comment]
hi @vidal-anguiano  - is this breakout group still active & meeting at Chi Hack Night?

**Comment by vidal-anguiano** [comment]
Hi @derekeder, yes, we are active and meeting!

**Comment by derekeder** [comment]
Closing for now as we haven't seen you in a while to keep the list up to date. Feel free to reopen if you think this is a mistake or when you come back!
