### ISSUE TITLE
Open Source Ecology - Chicago Group

### ISSUE THREAD

**Issue by spencerbug** [chihacknight/breakout-groups#163]
### About the group
Have you ever heard of Open Source Ecology? I'm creating a group to start a Chicago presence.
Watch the Ted Talk!
https://www.ted.com/talks/marcin_jakubowski

The mission of Open Source Ecology (OSE) is to create the open source economy.
An open source, libre economy is an efficient economy which increases innovation by open collaboration. To get there, OSE is currently developing a set of open source blueprints for the Global Village Construction Set (GVCS) – a set of the 50 most important machines that it takes for modern life to exist – everything from a tractor, to an oven, to a circuit maker. In the process of creating the GVCS, OSE intends to develop a modular, scalable platform for documenting and developing open source, libre hardware – including blueprints for both physical artifacts and for related open enterprises.

The current practical implementation of the GVCS is a life size LEGO set of powerful, self-replicating production tools for distributed production. The Set includes fabrication and automated machines that make other machines. Through the GVCS, OSE intends to build not individual machines – but machine construction systems that can be used to build any machine whatsoever. Because new machines can be built from existing machines, the GVCS is intended to be a kernel for building infrastructures of modern civilization.

### Group leaders
Group Leader: Spencer Neilan spencer.neilan@gmail.com

### Who we're looking for
Collaborators of any technical level are welcome! For starters, we need to organize a sustainable group. Check this link out!
https://www.opensourceecology.org/development/

### Relevant Links
Collaborative development is done here!
https://wiki.opensourceecology.org/wiki/Main_Page

### Where we meet
Room 3

### Chi Hack Night slack channel
Go to the slack channel #opensourceecology at the [Chi Hack Night Slack](http://slackme.chihacknight.org/)

**Comment by derekeder** [comment]
hi @spencerbug  - is this breakout group still active & meeting at Chi Hack Night?

**Comment by spencerbug** [comment]
Yes! We will be meeting next week

**Comment by derekeder** [comment]
Great! thank you for the update

**Comment by derekeder** [comment]
Closing for now as we haven't seen you in a while to keep the list up to date. Feel free to reopen if you think this is a mistake or when you come back!
