### ISSUE TITLE
SOMOS - Secure & Anonymous Online Platform for Immigrants

### ISSUE THREAD

**Issue by sha-somos** [chihacknight/breakout-groups#165]
### About the group
SOMOS brings together community organizations and immigrants onto a secure, comprehensive platform, so that in turn you have informed, connected, and empowered immigrants. We could use help in development, UI/UX, and especially in cybersecurity.

### Group leaders
Serafina Ha, Founder & Executive Director 
Secure email address: sha_somos@protonmail.ch
LilnkedIn: https://www.linkedin.com/in/serafinaha/

Jason Shatz, Front-end Engineer
Secure email address: jshatz_somos@pronmail.ch

### Who we're looking for
- Anyone in cybersecurity, particularly the Blue Team
- Database engineer
- Any computer engineer or developer
- UI/UX designer

### Tools
- Tor browser
- Open source code which relies either mostly on PHP or Python (currently deciding which to use), NO JavaScript
- Tools for PHP or PHP coding
- BitBucket
- Slack

### Relevant Links
N/A

### Where we meet
The Atrium

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by jdshatz** [comment]
The protonmail.ch part of my address is misspelled - just so you know.

**Comment by derekeder** [comment]
hi @sha-somos  - is this breakout group still active & meeting at Chi Hack Night?

**Comment by jdshatz** [comment]
Alas, it is not.  The SOMOS project has been stalled since last month, when the leader/founder experienced some family and logistical issues.

**Comment by derekeder** [comment]
@jdshatz thanks for the update. let's close this for now. you are welcome to reopen at any time!

**Comment by sha-somos** [comment]
Thanks for asking, Derek!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
