### ISSUE TITLE
Web Scraping for Good

### ISSUE THREAD

**Issue by justgosh** [chihacknight/breakout-groups#166]
### About the group
Searching for events can be a drag and it takes time away from doing the thing we all love; going with cool people to ask for awesome things from the rad people that can give them to us.

### Group leaders
Eric justgosh@gmail.com

### Who we're looking for
If you are a programer with experience using web scrappers, Resistance Calendar, Spoke, Action Network, or Eventbrite and would like to contribute, we can use some advice.

### Tools
Crystal, Docker,

### Where we meet
The Kitchen and interwebs

### Slack channel
www.progcode.org #birddogalerts and #spoke

**Comment by derekeder** [comment]
hi @justgosh  - is this breakout group still active & meeting at Chi Hack Night?

**Comment by derekeder** [comment]
closing for now. feel free to reopen if you start this back up!
