### ISSUE TITLE
Chicago ticketing data: pandas and pythons and jupyter notebooks (oh my!)

### ISSUE THREAD

**Issue by Kat-Alo** [chihacknight/breakout-groups#168]
### About the group
ProPublica Illinois and WBEZ cleaned and released the records for all parking and vehicle compliance tickets in Chicago from Jan. 1, 2007 to May 14, 2018.

We will be working with a sample of that data to create a community resource: notebooks with analysis and visualization. We hope that this will open the door for others who want to explore the entire dataset, which includes over 28 million entries.

### Group leaders
David Eads, david.eads@propublica.org

### Who we're looking for
Folks who are interested in analyzing government data! Should be comfortable with GitHub, their command line and Python. 

### Tools
Jupyter Notebooks, Pandas (Python)

### Relevant Links
[https://github.com/propublica/il-tickets-notebooks](https://github.com/propublica/il-tickets-notebooks)

### Where we meet
TBD

**Comment by eads** [comment]
We're re-upping this for at least the next two weeks!

**Comment by mtjehl** [comment]
Hi @eads! Does this working group still exist? I attended Chi Hack Night for the first time tonight but there was no mention of your group. I'm a novice data analyst but I'd love to get involved. Thanks!

**Comment by derekeder** [comment]
Closing for now as we haven't seen you in a while to keep the list up to date. Feel free to reopen if you think this is a mistake or when you come back!
