### ISSUE TITLE
Smart Share - solving village commons problems with smart contracts and tokenization

### ISSUE THREAD

**Issue by akabaria** [chihacknight/breakout-groups#171]
### About the group
“If you’ve got a good idea to help us hold on to that Kerry James Marshall piece [in the Chicago Public Library West Side Legler Branch] I’d love it — love it,” Mayor Rahm Emanuel said in a phone interview this past week. “But you’re going to have to give me a solution to 45 years of social, educational, cultural and economic inequity to the West Side. You don't get to pick one side of that argument.”

This is a group to create and demo a potential solution to issues like the Kerry James Marshall art piece commissioned by the Chicago Public Library in 1995 and now worth $10 million (more in the links below), based on a smart contracts platform for asset tokenization and sharing. 

### Group leaders
Amy Kabaria 
(George Chikovani - Blockchain Working Group)

### Who we're looking for
Looking for blockchain coders, UIX designers, attorneys interested in smart contracts, and anyone interesting in blockchain technology or learning.

### Tools
Factom protocol 
C++, Python, JavaScript 

### Relevant Links
http://www.chicagotribune.com/entertainment/museums/ct-ent-kerry-james-marshall-painting-library-sale-1014-story.html

https://www.nytimes.com/2018/10/05/arts/design/kerry-james-marshall-painting-chicago-proposed-auction.html

### Where we meet
Braintree

**Comment by derekeder** [comment]
Closing for now as we haven't seen you in a while to keep the list up to date. Feel free to reopen if you think this is a mistake or when you come back!

**Comment by akabaria** [comment]
thanks! I think there might be an evolution of this!


Amy Kabaria
P: (+1) 276-701-5878
F: (+1) 312-276-4858
E: amyrkabaria@gmail.com


This communication, along with any documents, files or attachments, is
intended only for the use of the addressee and may contain legally
privileged and/or confidential information. If you are not the intended
recipient, you are hereby notified that any dissemination, distribution or
copying of any information contained in or attached to this communication
is strictly prohibited. If you have received this message in error, please
notify the sender immediately and destroy the original communication and
its attachments without reading, printing or saving it in any manner.
