### ISSUE TITLE
CTA Crime Analysis

### ISSUE THREAD

**Issue by datu925** [chihacknight/breakout-groups#178]
### About the group
Publicly available data from the Chicago Transit Authority and the Chicago Police Department shows that crime on the L has nearly doubled in the last 3 years, driven largely by pickpocketing and other minor thefts. Join us as we dig into the data, figure out the story it's telling us, and decide how to spread the word.

### Group leaders
Dan Turcza

### Who we're looking for
We are still in an exploratory stage and welcome folks with a variety of backgrounds: data analysis and data science, visualization, software and data engineering, project management, communications strategy, research, and more. We're beginner-friendly as well.

### Tools
* [Chicago Open Data](data.cityofchicago.org)
* Excel
* Most of our work so far is in the Python data ecosystem (e.g. pandas, matplotlib/seaborn, Jupyter notebooks), but you can use other languages and tools if you like

### Onboarding
You can find the public repository with the data and startup instructions on GitLab [here](https://gitlab.com/datu925/cta-crime). GitLab is very similar to GitHub if you're not familiar. Also be sure to join our slack channel at `cta-crime` on the [Chi Hack Night Slack](http://slackme.chihacknight.org/)!

### Where we meet
The Cafeteria

**Comment by derekeder** [comment]
@datu925 is this group still active at Chi Hack Night?

**Comment by datu925** [comment]
It is not, unfortunately. I was hoping to get a co-captain to take it over,
but it never happened.

It’s fine to close it; we’ll resuscitate if the circumstances allow it.

**Comment by derekeder** [comment]
Sounds good!
