### ISSUE TITLE
She Votes Illinois Website Development Project

### ISSUE THREAD

**Issue by SheVotesIllinois** [chihacknight/breakout-groups#179]
### About the group
She Votes Illinois is a statewide political action committee aimed at highlighting the importance of women’s voices in elections, government, and policymaking. 

### Group leaders
Kelsey Burgess and Sophia Madana

### Who we're looking for
We are looking for a volunteer developer(s) to redesign our current website. The site will need to be built from scratch to eliminate  current backend / functionality issues. We are looking for someone that has a strong understanding of various platforms and hosting services and can bring us recommendations and best practices..

### Tools
TBD

### Relevant Links
Current site: https://shevotesil.org/

### Where we meet
This is our first meeting! Looking forward to it!

**Comment by kostimarko** [comment]
is this still active? I'd love to join and work on some stuff with you all.

**Comment by derekeder** [comment]
@SheVotesIllinois Looks like this group is no longer active. Closing for now. Feel free to reopen if you want to start it back up again!
