### ISSUE TITLE
[probably not meeting 4/25] Computer Science for All lesson finder for new CS educators

### ISSUE THREAD

**Issue by andyras** [chihacknight/breakout-groups#18]
**[link](http://github.com/TeachTechTaskForce/edumap)**

**March 28, 2017**
We are on pause this week.

At our March 21 hack session, we got just about ready to make our site public-facing. We will be doing some housekeeping on the repo/site, including: hooking Heroku up to our new domain, cslessons.org, doing some text rebranding on the site, renaming the repo, etc.

**About the group** The Teach Tech Taskforce seeks to improve the quality of tech/CS/IT education in Chicago by connecting our educators with resources. **Edumap** is a CS curriculum discovery tool that allows teachers to search quickly by grade level, resources required, and educational standards. This work supports the [Computer Science for All initiative in Chicago](www.cs4all.io).

**Group leaders** Andy Rasmussen (andyras@gmail.com), Eve Tulbert, Vinesh Kannan

**Who we're looking for** Educators and developers who care about CS education!

**Tools** Rails, Javascript, PostgreSQL

**Relevant Links**
- [github](http://github.com/TeachTechTaskForce/edumap)
- [demo on Heroku](http://edumap2.herokuapp.com)

**Where we meet** (╯°□°）╯︵ ┻━┻ Flipping Tables (right next to the main meeting space)

**Comment by derekeder** [comment]
Please add additional details to this group following this guide! https://github.com/chihacknight/join-a-breakout#adding-your-breakout-group
