### ISSUE TITLE
Tech Month Chicago- A Technology Awareness Month for Chicago

### ISSUE THREAD

**Issue by TechMonthChicago** [chihacknight/breakout-groups#180]
Make sure to check out our [guide to starting a breakout group](https://docs.google.com/document/d/1B0AlFjXa7chUVQsQ_BPq2b3KkAWI3sM7h65RZH0NR4c/edit#)!

![tmc break out group at chi hack night- flyer 4](https://user-images.githubusercontent.com/47169351/51961538-ab200080-2422-11e9-9863-2bb11c68efed.jpg)

### About the group
Tech Month Chicago is an awareness month for technology for the Chicagoland area. The month is geared toward the general public. The website has a calendar of events for the month and room to grow pages for civic projects as well. 
More info: techmonthchicago.com @techmonth
Link to a talk given about Tech Month Chicago: https://youtu.be/WCiXUIDAh4U

### Group leaders
Melanie Adcock 312-259-0610 melanie@techmonthchicago.com 
Looking for more Group Leaders as well!! 

### Who we're looking for
People who can help us automate our processes for event submissions for our awareness month calendar and can use the tools below. Anyone who can help refine the look and feel of our website and help with cyber security would be super helpful! 

### Tools
Word Press
Zapier
Gravity Forms
Tockify
Google Calendar for WordPress
Google Sheets and Google Docs
Social Pilot (Used for Twitter)

### Relevant Links
techmonthchicago.com

### Where we meet
Announced nightly when break out groups are announced.

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
@TechMonthChicago Looks like this group is no longer active. Closing for now. Feel free to reopen if you want to start it back up again!
