### ISSUE TITLE
City Scrapers

### ISSUE THREAD

**Issue by pjsier** [chihacknight/breakout-groups#181]
### About the group
Local government bodies hold thousands of public meetings every day—but the vast majority receive no media coverage and produce minimal records. [City Bureau](https://citybureau.org/) is working to scrape, standardize and share meeting details and documents to make government more accessible and transparent. See our [City Scrapers website](https://cityscrapers.org/) for more information

### Group leaders
Darryl Holliday, Pat Sier

### Who we're looking for
Anyone with experience in or interest in learning Python, or people interested in researching public agencies

### Tools
Python and the [Scrapy](https://scrapy.org/) library for web scraping

### Relevant Links
* Repo: [City-Bureau/city-scrapers](https://github.com/city-bureau/city-scrapers)
* [Issues and scrapers we're looking for help on](https://github.com/city-bureau/city-scrapers/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
* Project site: https://cityscrapers.org/
* [City Scrapers Slack sign up form](https://airtable.com/shrsdRcYVzp019U22)

### Where we meet
Cafeteria

**Comment by derekeder** [comment]
@pjsier is this group still active at Chi Hack Night?

**Comment by pjsier** [comment]
We haven't met in a while, so this is fine to close for now. Thanks for checking!
