### ISSUE TITLE
Transit Talk

### ISSUE THREAD

**Issue by SorenSpicknall** [chihacknight/breakout-groups#182]
## About the group

Transit Talk is a platform that democratizes the flow of information about issues that riders encounter on public transit. Based on Ruby on Rails and open GTFS data, our team is building an app that can be adapted to thousands of train, bus, trolley, boat, and other types of transit lines around the world, allowing riders to tailor their trips based on reports from other users about cleanliness, delays, crime, and more. Transit Talk seeks to empower transit users to better their experience and pressure transit administrators to address repetitive issues in a public, data-backed fashion, making all its data available to those seeking to push change forward at the local level.

Some old discussion related to this group is in the closed Issue #93.

We have a channel in the ChiHackNight Slack, **#transit-talk**.
## Group leaders

Megan Krout, Jannie Lung, Scott Rubin, Soren Spicknall, and Sage Voorhees
## Who we're looking for

Ruby on Rails programmers, mapping and transit data enthusiasts, community outreach experts, and anybody who believes in what we're doing!
## Tools

Ruby on Rails
GTFS Data
MySQL
HTML, CSS, and a dash of jQuery
## Relevant Links

The site and all published work lives on Heroku at the moment, at [transit-talk.herokuapp.com](http://transit-talk.herokuapp.com/). Note that this does not always reflect most recent changes and is also a deployed version of the modular Caravan system with data loaded in for the CTA.

All repository files can be found at [CaravanTransit/Transit-Talk](https://github.com/CaravanTransit/Transit-Talk) on GitHub.
## Where we meet

The back right corner of the atrium (where the main presentation is)

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
