### ISSUE TITLE
Hospital Cancer Surgery Project

### ISSUE THREAD

**Issue by aander8** [chihacknight/breakout-groups#184]
### About the group
The Cancer Surgery Volumes Project aims to aggregate all publicly reported data about cancer surgery volumes into 1 user-friendly and easily searchable database website.  There is a substantial body of evidence showing that better patient outcomes (survival, complications, etc) are associated with hospitals performing a higher number of cancer surgeries.  Currently, California and Pennsylvania publish this data, but not enough people are aware.  We want to create a patient-friendly, searchable online database and influence other states and hospitals to publish their cancer surgery volumes.

### Group leaders
Adam Andersen, adamandersen@gmail.com
Serg Masis, smasis@hawk.iit.edu

### Who we're looking for
Developers, data heads, designers, and people interested in healthcare.

### Tools
Tableau, R, etc.  Haven't decided on how to build the site and app.

### Relevant Links
https://github.com/best-chicago-hospitals

### Where we meet
Usually 1 of the smaller breakout spaces.

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
@aander8 Looks like this group is no longer active. Closing for now. Feel free to reopen if you want to start it back up again!
