### ISSUE TITLE
Survey of Cybersecurity 

### ISSUE THREAD

**Issue by GitRichar** [chihacknight/breakout-groups#188]
### About the group
Discuss and trade information about topics in cybersecurity.

### Group leaders
Richard Stern

### Who we're looking for
Anyone interested in observing, contributing, or otherwise participating in a mutual tutorial-level discussion of cybersecurity.

### Tools
We are guided by articles, security websites, blogs, and web resources.

### Relevant Links
[Public-Interest Tech](https://public-interest-tech.com/)
[Electronic Frontier Foundation](https://www.eff.org/)
[Freedom of the Press Foundation](https://freedom.press/)

### Where we meet
Focus 03 (when available)

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. Coming soon!

**Comment by cjuarbe1** [comment]
Is this Group still active? I am really interested in the field and I would love to talk to people about it

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
