### ISSUE TITLE
Chicago City Council Divided Roll Call Votes

### ISSUE THREAD

**Issue by kfogel** [chihacknight/breakout-groups#189]
### About the group

This working group's goals are:

1. To present information about Chicago City Council's "Divided Roll Call" votes (non-unanimous votes, a.k.a. "non-rubber-stamp" votes :-) ) in ways that are human-friendly and in ways that are machine-friendly; and

2. To support the City Clerk's Office in eventually doing the same, by example and possibly by assistance.

The two goals above will probably involve both technical work, such as setting up a working demonstration site showing how the information could be displayed well and simultaneously made available for convenient download (in, e.g., spreadsheet form), and non-technical work, such as providing draft model procurement language that the City Clerk's Office could draw on in order to work with its current vendors to add functionality and improved navigability to its web site.

This group grew out of a discussion following [Dick Simpson's presentation of 3 Sep 2019](https://chihacknight.org/events/2019/09/03/dick-simpson.html).  It's not yet clear what the group's duration will be.  We may wrap up once the above goals are accomplished, or we may decide to continue beyond that if we've pick up other related goals along the way.

### Group leaders

As an administrative matter, [Karl Fogel](https://github.com/kfogel) created the breakout group and will do what he can to support the group's work, but he's not able to be at Hack Night as often as he'd like and hopes that others with the right desires/skills/experience will take the reins.

Others at the initial meeting included [Andrea Craft](https://github.com/GitHub-username-N/A), [Mieko Furuhashi](https://github.com/miekof), [George Lee](https://github.com/ghrlee), [Andrew Mauer-Oats](https://github.com/maueroats), [Alexis Shoemaker](https://github.com/GitHub-username-N/A), [Matt Sweeney](https://github.com/GitHub-username-N/A), [Eric Sherman](https://github.com/easherma), and [Josh Marsh](https://github.com/GitHub-username-N/A), as well as UIC Professor (and former Alderman) Dick Simpson and UIC graduate student Marco Rosaire Rossi.

### Who we're looking for

If you like to rapidly prototype useable web sites that display both raw data (e.g., aldermanic voting records) and graphical trend-over-time summaries of that data, then this is the place for you.  Or if you like devising public-sector procurement language oriented toward civic data distribution and pleasant end-user outcomes, this is also a good place for you.

### Tools

Probably standard web development tools, though still TBD.

### Relevant Links

From the City Clerk's web site:

* [City Council Meeting Reports](http://www.chicityclerk.com/legislation-records/journals-and-reports/council-meeting-reports)
* [City Council "Journals of the Proceedings"](http://www.chicityclerk.com/legislation-records/journals-and-reports/journals-proceedings)
* [Legistar search page](https://chicago.legistar.com/Legislation.aspx) for Chicago City Council (Legistar is the private-sector vendor that the City Clerk has hired to convert City Council records to digital form and present them in a publicly usable manner.  See more about Legistar below.)

Also, [DataMade](https://datamade.us/) has built [Chicago Councilmatic](https://chicago.councilmatic.org/), which has records of (among other things) City Council meetings and their outcomes.  While Councilmatic does not currently show the individual aldermanic votes for a given piece of legislation, informal conversation with DataMade indicates that they do actually get that data already by querying Legistar's APIs.  Whether or not DataMade starts publishing it on Councilmatic, the point is that that data is clearly available in a parseable format -- if they can get it from Legistar, so can anyone else, so there is no need to extract the data from the PDFs that the City Clerk currently publishes.  In other words, the data-parsing part of this group's work may be mostly already taken care of :-).

If one *were* to extract voting data from those PDFs, however, rather than do so manually it would be faster to use a PDF-parsing library such as [PDFMiner](https://github.com/euske/pdfminer), [Camelot](https://github.com/socialcopsdev/camelot/), or [PDFTabExtract](https://github.com/WZBSocialScienceCenter/pdftabextract).  The first of those can be seen in action in the [CAFR Parsing](https://github.com/opentechstrategies/cafr-parsing) project, and there is more documentation there about the general question of extracting data from PDFs in an automated way.  Again, PDF extraction may not be necessary at all given that Legistar has APIs and we already know those APIs are being used successfully by DataMade for Councilmatic.

DataMade also offers a wrapper that simplifies that Legistar APIs.  [According to Derek Eder](https://chihacknight.slack.com/archives/CMTCWN9L1/p1567565444005300): "Councilmatic uses an API that DataMade runs that you may want to use instead: https://ocd-api-documentation.readthedocs.io/en/latest/.  You can access it here: https://ocd.datamade.us/jurisdictions/".  Also, the general API scraper code for Chicago Legistar that powers Chicago Councilmatic is here: https://github.com/opencivicdata/scrapers-us-municipal/tree/master/chicago.

### Where we meet

We haven't picked a room yet.  Our first meeting was just in the chairs in the Atrium, right in front of where the presentation had just taken place.

### Slack channel

The Slack channel for this breakout group is [council-votes](https://app.slack.com/client/T04KM9VQY/CMTCWN9L1).  (To participate in that channel, you would need to [join the Chi Hack Night Slack](http://slackme.chihacknight.org/) if you haven't done so already.  Note that there is no need to join the Slack channel to participate in the breakout group.)

**Comment by derekeder** [comment]
Here is documentation on how to use the Open Civic Data API that DataMade maintains for Councilmatic to get the divided roll call vote data: https://gist.github.com/derekeder/6250077831d93727c4c0b2051bd4df52

**Comment by mattesweeney** [comment]
Here's the link to the group's gitlab repo: https://gitlab.com/ipce_uic/council_votes

Here's the link to the Shiny app: https://ipce.shinyapps.io/council_votes/

**Comment by derekeder** [comment]
Is this group still active at Chi Hack Night?

**Comment by kfogel** [comment]
To the best of my knowledge, no.  +1 to archiving it.

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
