### ISSUE TITLE
mentors4all: matching computer science experts with new CS teachers

### ISSUE THREAD

**Issue by andyras** [chihacknight/breakout-groups#19]
**About the group** The Teach Tech Taskforce seeks to improve the quality of tech/CS/IT education in Chicago by connecting our educators with resources. **mentors4all** is a CS curriculum discovery tool that allows teachers to search quickly by grade level, resources required, and educational standards.

** August 30 activities **
- Looking for rails people!
- Documentation and planning for MVP

**Group leaders** Andy Rasmussen (andyras@gmail.com), Eve Tulbert, Vinesh Kannan

**Who we're looking for** Educators and developers who care about CS education!

**Tools** Rails, Javascript

**Relevant Links**
- [github](github.com/TeachTechTaskForce/mentors4all_rails)
- [demo on Heroku](mentors4all.surge.sh)

**Where we meet** (╯°□°）╯︵ ┻━┻ Flipping Tables (right next to the main meeting space)

**Comment by andyras** [comment]
'Teach Tech Taskforce' could be a tag for this and Edumap (we are a working group with multiple projects)

**Comment by derekeder** [comment]
Please add additional details to this group following this guide! https://github.com/chihacknight/join-a-breakout#adding-your-breakout-group
