### ISSUE TITLE
Idealogs

### ISSUE THREAD

**Issue by tyfried** [chihacknight/breakout-groups#190]
### About the group

[Idealogs](https://idealogs.org) is a new open-source crowdsourcing platform for [understanding](https://idealogs.org/@0x2) controversial topics. The problem we are trying to solve is the fundamental [lack of context](https://en.wikipedia.org/wiki/Amusing_Ourselves_to_Death) in public discourse today.  Our solution is a repository of context built by a dedicated group of volunteers.  Our team is contributing content to the site in [Markdown](https://www.markdownguide.org/cheat-sheet/), as well as building the platform itself in [Django](https://www.djangoproject.com).

### Group leaders

Tyler Friedman

### Who we’re looking for

- writers with expertise on a subject that has two or more conflicting views (i.e. any subject)
- django developers
- journalists
- academics
- wikipedians
- anyone interested in learning django and/or markdown
- anyone interested in improving the state of public discourse

### Tools

- Markdown
- Django
- PostgreSQL
- HTML + CSS + jQuery

### Relevant links

The site is live at [idealogs.org](https://idealogs.org), and our code base lives [here](https://github.com/tyfried/idealogs).

### Where we meet

TBD (looking forward to our first meeting on September 24th, 2019)

### Chi Hack Night slack channel
 
[#idealogs](https://app.slack.com/client/T04KM9VQY/CNS23SUFQ)

**Comment by derekeder** [comment]
@tyfried is this project still active at Chi Hack Night?

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
