### ISSUE TITLE
Explore/discuss the future of Chicago's DoIT (Department of Innovation and Technology)

### ISSUE THREAD

**Issue by easherma** [chihacknight/breakout-groups#191]
### About the group
If you haven't heard, the Lightfoot administration [recently announced](https://www.chicagotribune.com/politics/ct-lightfoot-department-mergers-budget-20191009-umaj4l344va7paffyfx6hw6wba-story.html) that it intends to merge the city's Department of Innovation and Technology with the Department of Fleet and Facility Management. 

This breakout group is to discuss this news, learn more about what it means, and conduct some research and potential next steps if you are interested in providing feedback to the mayor and city council about this potential move. 

Note that any output from this group will not be considered representative of an opinion of Chi Hack Night as a whole, but just of the individual members of this breakout group who choose to participate. 

### Group leaders
Eric Sherman (@easherma on Slack)
Derek Eder(@derekeder on Slack)

### Who we're looking for
No coding required!

We are looking for people to help with:
* Research
* Writing
* Potential organization/advocacy work
* Being able/willing to sign up to speak during the city council's pubic comment period on October 23rd

**Comment by easherma** [comment]
It's very difficult to find any official information about this merger. It's apparently going to be considered at the City Council meeting, but its hard to find any info about it on the Agenda or Legislative docket:
https://chicityclerk.s3.amazonaws.com/s3fs-public/ChicagoCouncilAgenda_2019-10-16_updated.pdf
https://chicago.legistar.com/MeetingDetail.aspx?ID=705121&GUID=A0484F31-2678-439D-B564-22A8320A5579&Options=&Search=

**Comment by easherma** [comment]
Alternative suggested by members: F2M improvement should be a project FOR DoIT, and not require a merger.

**Comment by easherma** [comment]
Chicago did used to have an innovation fellowship office in the Mayor...but what did they accomplish?

**Comment by easherma** [comment]
Ultimate goal is to pause the merger; more time to propose.

**Comment by derekeder** [comment]
This group was active for a few weeks. Closing.
