### ISSUE TITLE
Data Science for Good: Publishing an anthology of contemporary projects

### ISSUE THREAD

**Issue by Andrewottogordon** [chihacknight/breakout-groups#192]
### About the group
The final goal of this breakout group will be to publish a book, which will be an anthology of different projects that are either recent or contemporary cases of data analytics, machine learning, and blockchain being utilized in the non-profit and social sector. 

The anthology will borrow the basic design of "Sharing Cities: Activating The Urban Commons", a book published by Shareable (there is a link to the free PDF below). Each case study will include a **Problem, Solution, Results, and Resources** section. Some of the folks at Shareable are aware of this project and have offered some preliminary support along the way, from finding case studies to publishing. 

Despite being such a hot topic, there is very little published related to DSG. The inspiration for this book came from the simple desire to see what others are doing with the technologies to make the world a better place, and seeing that there is no seminal collection of projects on the subject. It is our hope that this book will serve as guide and inspiration to readers on what is currently being done around the world. 

The number of projects that we could potentially cover is astounding. As a filter to consider, the book will have a socialist approach, meaning we will be particularly looking to document projects that are disrupting/ concerned with the ownership of different means of production

The book will be published under a creative commons license, any proceeds generated in the future will be donated to a charity organization that we will collectively decide on. There will be a free PDF available online.

### Group leaders
Rew Gordon (they/them) - Andrewottogordon@gmail.com

### Who we're looking for
We are looking for anyone who is interested in how data analytics, machine learning, artificial intelligence, and blockchain are being used to change the world for the better. As a working model, the book will break into 9 sections: 
- Housing
- Energy
- Mobility
- Land
- Food
- Waste
- Governance
- Food
- Water

If you have any background in these subjects, or are excited to do research in these fields - come one come all! We will especially appreciate people who are already engaged with projects of this nature, as the first major step will simply be finding/cataloguing perhaps around 70+ distinct projects. What this means is doing research online, contacting various organization, gaining permissions, and drafting sections.
People who have a background in Design, Writing and Publishing will obviously be helpful throughout this process. 
 
### Tools
This project will be held on Google Drive.

### Relevant Links
Here is a link to the Sharing Cities book PDF, which may be helpful to review, as it is the basic model we will be following:
https://www.shareable.net/sharing-cities/downloads/

### Where we meet
This is a collaborative volunteer project that will primarily meet as a break out group at Chi Hack Night. We will generally meet in the Cafeteria. If there is a strong enough backing, we will discuss meeting outside CHN to work together. 

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We have a newly created channel in the CHN slack titled "dsg-anthologybook"

**Comment by derekeder** [comment]
@Andrewottogordon is this group still active at Chi Hack Night?

**Comment by Andrewottogordon** [comment]
It is not

**Comment by derekeder** [comment]
Cool. closing for now
