### ISSUE TITLE
Collaborate with artists and scientists to help the next generation fight climate change.

### ISSUE THREAD

**Issue by BenWhitehouse-SkyDay** [chihacknight/breakout-groups#193]
SkyDay (skydayproject.com) is a free educational platform with the mission of inspiring the next generation to learn about how climate functions, what its vulnerabilities are and why it is so important they come together across cultures and borders to achieve positive outcomes. 
Everyone at SkyDay is a volunteer and we are non-political. 

Group leader:
SkyDay ED Ben Whitehouse
ben@skydayproject.com

Who we're looking for:
Motivated, creative front-end developers with expertise in developing responsive websites in HTML/CSS/Javascript to help us take the citizen artwork 'Sky Day Project' (skydayproject.org) to the next level.  The first challenge is to migrate Sky Day Project over to our educational platform skydayproject.com. The second will be to develop code that will allow visitors to access educational content which could be text, images, or videos and the third challenge is to allow visitors to register a group. All of this needs to work seamlessly across devices, screen sizes, and most mainstream browsers.

What is Sky Day Project? 
Inspired by Yo-Yo Ma, Sky Day Project is a web-based citizen artwork in which young people post sky photos as a visual call for climate justice. Sky Day Project lends itself well to public exhibition with previous installations at art museums, the Adler Planetarium, The Chicago Botanic Garden and  on the International Space Station with astronauts taking part (view: skydayproject.com/iss). We now want to make Sky Day Project more interactive and educational with feedback loops and content on climate. 

### Tools
Our site is hosted on the Google Cloud Platform and pulls information (including images and media files) from a database on the platform via API/JSON calls.

### Relevant Links
Sky Day Project - skydayproject.org
The SkyDay educational platform - skydayproject.com

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
