### ISSUE TITLE
Rental Market Concentration in Cook County

### ISSUE THREAD

**Issue by tnoomah** [chihacknight/breakout-groups#195]
### About the group
Competitive markets drive innovation and affordability while non-competitive markets raise prices and lower quality. Some Chicago neighborhoods have somewhat non-competitive markets. For example, four companies in Hyde Park own over 50% of the total rental stock, while in other neighborhoods like Ukrainian Village, the four largest companies control less than a tenth this amount. Why doesn't anyone stop them? At this time there is no evidence that this level of concentration harms consumers, though I (and many Hyde Park renters) think it does. I'm starting a group because I'm confident the Chi Hack community has the collective knowledge to guide further research and advocacy around this topic.

### Group leaders
Theo Noomah- tnoomah@uchicago.edu

### Who we're looking for
If you know anything about real estate, spatial data, or market/business data please add your expertise!
Do you have an idea what data source/research method would indicate that consumers are being hurt? I'd love to hear about it!
Anyone who likes mapping and visualizations

### Tools
-R
-A bit of PostgreSQL through R
-A bit of Python through R

### Relevant Links
[Data on the 180,000 rental properties in Cook County, matched up by probable owner](https://drive.google.com/file/d/1U9Dhja1Nw5uclADa3-ZRSj6vsgT1Nq2w/view?usp=sharing)
[Mini-version of the code for analyzing a single neighborhood](https://github.com/tnoomah/rental_market_concentration/blob/master/Appendix.Rmd)
[Property Tax Data (postgres database dump)
](https://drive.google.com/file/d/1Utqhb2uvVzRqEWXfpUl4G6w0SVOLcWzp/view?usp=sharing)
### Where we meet
TBD

### Chi Hack Night slack channel
 rental_market_concentration

**Comment by derekeder** [comment]
@tnoomah this is a really cool project. Have you seen the work that the DePaul Institute for Housing Studies does? 

Here's a few of their reports and tools that may be useful for you:

Examining Patterns of Concentrated Institutional Investor Purchases in Cook County: https://www.housingstudies.org/blog/examining-patterns-concentrated-institutional-inve/


2019 State of Rental Housing in Cook County:
https://www.housingstudies.org/releases/state-rental-2019/

Mapping Displacement Pressure in Chicago, 2018:
https://www.housingstudies.org/releases/mapping-displacement-pressure-chicago-project-2018/

(disclaimer: IHS is a client of my company DataMade and we helped build their data visualizations)

**Comment by tnoomah** [comment]
Hi Derek,

Thanks for sending this along! I have looked at some of the Institute for
Housing Studies' work before, I'd seen the 2019 State of Rental Housing
report, I didn't realize you did the vizzes. I hadn't seen the first
article before though and it seems really relevant and useful. I tried
following some links to their property sales clearinghouse, but I hit a 404
error, so I sent an email to see if it's still being supported. Some of the
folks who came to the session yesterday had some experience in real estate
and helped me understand all different sorts of information that is only
collected when a property is sold, so I feel like there might be something
valuable to be gained from the sales data.

**Comment by BenoitBalzac** [comment]
Happy Holidays!

So I've been looking at LA among other cities with open access data. Could somebody direct me to whether there's visualization, or at least data on insitutional ownership by geography? I'm looking for comparative cases like we last discussed, but it's not clear if these neighborhood also have the same level of owner/management concentration as HP

**Comment by tnoomah** [comment]
The most extensive institutional ownership work that I know of is this [Who Owns What](https://whoownswhat.justfix.nyc/en/) database. I learned about it from this [NYTimes article](https://www.nytimes.com/2018/12/04/nyregion/nyc-landlord-database-who-owns-what.html) which seems to suggest that the architects were more interested in identifying patterns of misbehavior in landlords rather than local market concentration.

**Comment by tnoomah** [comment]
[Meeting Notes](https://docs.google.com/document/d/1jMKWB5ONFcdwPKtzGkmbc-FZUZW1YBH4j2xctMHXeOk/edit?usp=sharing)

**Near future steps**

Scraping groups:
-- Secretary of State Registered Agents
-- Various real estate websites for rents for buildings

**Comment by stevevance** [comment]
Hi Theo, the link "Property Tax Data (postgres database dump)" is broken. 

I read your R code...it's very tidy :)

**Comment by tnoomah** [comment]
Hi Steve,

Thanks for pointing that out! I think it should be good now. I'm just sharing the file via Google Drive, so I'm also open to suggestions about better ways to share files.

I'm also glad that you've taken an interest in the project. A fair amount of my approach to the assessment data was informed by your python scraper and some of the conversation that happened on your GitHub.

**Comment by stevevance** [comment]
Tell me if you need any help getting more data or understanding the property tax classifications.

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
