### ISSUE TITLE
2120 Hindsight discussion group: imagining the future 100 years out

### ISSUE THREAD

**Issue by zero-eth** [chihacknight/breakout-groups#197]
### About the group
[2120 Hindsight](2120hindsight.com) is a webcomic that tries to imagine what an ideal, but realistic world might look like in the year 2120-- a flawed utopia, if you will.

This discussion group meets the first Tuesday of every month.

### Core values
The present is complicated and the immediate future is hard to predict. But maybe the distant future is easier to foresee?

I try to keep this core value in mind as I write the story: the ideal future is one where everyone is able to spend the most possible amount of time doing what they love, with regard for the environment and future generations. So come to this group imagining what you'd most love to do if it were possible, and let's imagine the future together!

### Format of discussion

As you might imagine with such an endeavor, there is a lot to discuss. I try to take it one step at a time as the narrative allows. I'll have a list of suggested topics ready (related to the most recent comic and/or upcoming one in development), but anyone can feel free to add an idea to the board. We'll kick off the discussion with a [Lean Coffee-style vote](http://leancoffee.org/) on what to talk about, and explore the top three issues in as much detail as we can.

### Group facilitator
[Ethan Heppner](eth@2120hindsight.com)

### Where we meet
TBD

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
