### ISSUE TITLE
Vision Zero Dashboard

### ISSUE THREAD

**Issue by geneorama** [chihacknight/breakout-groups#198]
### About the group

We are developing a dashboard that uses publicly available data to help achieve the Vision Zero Goals. Vision Zero is an international movement to eliminate traffic fatalities. We want to understand where, when, and why traffic crashes are happening, and what is effective for preventing crashes.

### Group leaders
Gene Leynes @geneorama
Sid Shah @sas1336

### Who we're looking for

We are primarily looking for people who care about transportation issues. You do not have to be a developer to contribute. We want people who are passionate about improving traffic safety.

If you understand crash data, have experience with transportation planning, or have ideas about visualizations that you would like to see, then please get in touch!

### Tools

R, Shiny, HTML, GIS

### Relevant Links

https://github.com/Chicago/vision-zero-dashboard
https://www.meetup.com/Chicago-R-User-Group/events/266146523/

### Where we meet

Normally we meet in the cafeteria.

### Chi Hack Night slack channel
https://chihacknight.slack.com/archives/CQ730U7LG

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
