### ISSUE TITLE
Dolphin Tank

### ISSUE THREAD

**Issue by kuhnbaya** [chihacknight/breakout-groups#20]
Do you have an idea for a civic app? Come to Dolphin Tank and get feedback from a group of friendly folks!

Tonight we will talk about the future of Dolphin Tank. We are looking for new leaders and new ideas. Come join us if you would like to contribute to our discussion.

**Comment by K-Wei** [comment]
Do you have an idea for a civic app or startup? Come to Dolphin Tank and get feedback from a group of friendly folks!

Just a relaxed atmosphere to chat what's the next big thing in civic tech!

**Comment by derekeder** [comment]
closing by request from @K-Wei
