### ISSUE TITLE
Tidy Tuesday

### ISSUE THREAD

**Issue by zaynaib** [chihacknight/breakout-groups#200]
Make sure to check out our [guide to starting a breakout group](https://docs.google.com/document/d/1B0AlFjXa7chUVQsQ_BPq2b3KkAWI3sM7h65RZH0NR4c/edit#)!

### About the group
Every week the R for Data Science(R4DS) Community post a raw data set to be explored. The goal of Tidy Tuesday is to gain practice on your wrangling and data visualization skills. This group will primarily focus on using R tidyverse tools but pythonistas are also welcome to join.

### Group leaders
Names and contact info for the people running this group.
Ola Giwa - [@AmazingSpeciali](https://twitter.com/AmazingSpeciali)

### Who we're looking for
All skill levels are welcome. If you have a desire to learn about R or exploratory data analysis come on over.

### Tools
R 

### Relevant Links
[Tidy Tuesday Github Repo](https://github.com/rfordatascience/tidytuesday)
[R for Data Science Textbook](https://r4ds.had.co.nz/index.html)

### Where we meet
The cafeteria

### Chi Hack Night slack channel
TBA
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
