### ISSUE TITLE
R Learning Group

### ISSUE THREAD

**Issue by jlherzberg** [chihacknight/breakout-groups#201]
Make sure to check out our [guide to starting a breakout group](https://docs.google.com/document/d/1B0AlFjXa7chUVQsQ_BPq2b3KkAWI3sM7h65RZH0NR4c/edit#)!

### About the group
We're going to learn the R programming language. 

### Group leaders
@jherzberg

### Who we're looking for
People who want to learn R. 

### Tools
Hands on Programming with R
R

### Relevant Links
https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. When you come back, please re-open or start a new one!
