### ISSUE TITLE
Chicagolaborative: A Resource for Community-based organizations during COVID and beyond

### ISSUE THREAD

**Issue by NalaBuckets** [chihacknight/breakout-groups#205]
### About the group
Chicagolaborative will provide open source data access to resources available for Chicago's youth across the City, with focus on emergency services and supports amidst the COVID-19 Crisis.

The goal of this effort is to open virtual doors across the city for community organizations so that we can mobilize not only around needs and challenges emerging as a result of the Covid-19 Crisis, but also to ensure the efforts around emerging needs in the days, weeks, and months to come. It’s also an ongoing assessment and support system to strengthen our human services infrastructure and track its recovery. 

We are looking to build an interactive map/directory and dashboard utilizing data from a (to-be-built) provider directory. Data capture elements (likely google forms) will be built into the project website. 

Help us make this a great set of tools and platform for community organizations to convene and collaborate when they can't gather in person

### Group leaders
The Thrive Data Team:
Denali Dasgupta: ddasgupta@thrivechi.org
Jessica Dargiel: jdargiel@thrivechi.og
David Krosin: dkrosin@thrivechi.org

We presented a little more about our work and how we support community based organizations at [HackNight 377 ](https://chihacknight.org/events/2019/12/10/thrive-chicago.html)

### Who we're looking for
We are looking for support from skilled programmers who can support with any of the following tasks or people who can help us develop workflows or process flows for technology that supports communities and/or anyone who can help us think about how to improve user experience for a community resource. 

**This is not a teaching group**-- we are looking for support from the coding community to build an interactive tool that we don’t have the internal skills to produce. We anticipate this will be a highly iterative process; creative problem-solving is welcome and encouraged.

Some of the things we think we might need help with are: 

**Code to update our data set and the services map** based on information entered along with process for code review and data quality

Support for our Data Team in developing **interactive maps** for community members and organizations to navigate to identify and share local resources. Right now we are thinking Shiny in R but we are open to other ideas.

Additional code/ experimentation with open-source tools such as Switchboard to **support more efficient provider outreach processes to update and maintain the provider directory**

**UX ideas and feedback**; 

### Tools
Google Sheets, Google App Scripts, HTML, Weebly, R, R Shiny

### Relevant Links
A work in progress: https://chicagolaborative.weebly.com/

### Where we meet
Remotely for now. We opened up a slack channel [here](https://join.slack.com/share/I010SU0GFCZ/9ZsvDdQgWYupu3TT7d0tYTMB/enQtMTAyNjk1MjU1OTQ0MS1jZGNiODRjNjZlZjkyY2M1ZGE5OWZkYWI4OGYzYzViMDgyY2I5NDZkODFkNGMwMDg5NWMzYWJhMDFkYzAyNmI0)

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. If/when you come back, please re-open this issue or open a new one.
