### ISSUE TITLE
Opik: charitable donations 

### ISSUE THREAD

**Issue by opik87** [chihacknight/breakout-groups#207]
Make sure to check out our [guide to starting a breakout group](https://chihacknight.org/blog/2020/02/28/so-you-want-to-start-a-breakout-group.html)!

### About the group
Opik aims to streamline individual and corporate giving in an easy way- through linking charitable donation to commercial purchases Opik strives to prove that if given a simplified process, individuals are prone to giving charitable contributions. 

### Group leaders
George Kannankeril 

### Who we're looking for
Looking for app developer, business strategists, and innovators!

### Where we meet
Virtually for now!

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. If/when you come back, please re-open this issue or open a new one.
