### ISSUE TITLE
R learning group 

### ISSUE THREAD

**Issue by NimishaS9** [chihacknight/breakout-groups#208]
Make sure to check out our [guide to starting a breakout group](https://chihacknight.org/blog/2020/02/28/so-you-want-to-start-a-breakout-group.html)!

### About the group
Just wanted to learn R language . I have no background in coding or programming 
### Group leaders
Names and contact info for the people running this group.

### Who we're looking for
Describe the kinds of people who would be good for your group. Include the skills, domain knowledge and interests that will help make your project succeed.

### Tools
Describe the tools that you are using.

### Relevant Links
Any relevant links, e.g. a github repo, a demo site

### Where we meet
Where in the Braintree office do you meet? Flipping Tables? The cafeteria?

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. If/when you come back, please re-open this issue or open a new one.
