### ISSUE TITLE
SixKeys : Virtual queues!

### ISSUE THREAD

**Issue by Francisco2727** [chihacknight/breakout-groups#209]
### About the group
DMV's, government facilities, and countless other venues have long queues. Even during a pandemic there are long queues in which most of the times, do not follow proper COVID protocols. What I've been planning to construct is a universal queue system where anyone on any mobile device may reserve their spot for a desired location-- remotely!

Here is a wireframe (basic premise) of the project: https://marvelapp.com/prototype/egd7290

### Group leaders:
Francisco Sebastian: Undergrad / Social Entrepreneur / Great at creating partnerships
I may be reached anytime on LinkedIn:  https://www.linkedin.com/in/francisco-sebastian-9b8014172/ 

### Who we're looking for:
<> Looking for extraordinary and selfless technologists!
<> Experienced and/or deep curiosity in making _web-applications_ prominent (apps are not so great, there is an overabundance of them and 98% of them are useless)!

### Tools:
We are just starting and I'm open to any ideas/tools to begin with.... everything is on the table.

### Where we meet:
100% remotely works fine, as well as from time to time in-person meetings.

### Chi Hack Night slack channel:
Soon to be posted......

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. If/when you come back, please re-open this issue or open a new one.
