### ISSUE TITLE
The Circuit: The Charges folo breakout group

### ISSUE THREAD

**Issue by deraj1013** [chihacknight/breakout-groups#210]
Make sure to check out our [guide to starting a breakout group](https://chihacknight.org/blog/2020/02/28/so-you-want-to-start-a-breakout-group.html)!

### About the group
A high level overview of your breakout group. What problem are you trying to solve? Make this simple and jargon-free. Links are good too!

### Group leaders
Jared Rutecki, Bea Malsky, (possibly) Casey Toner et al.

### Who we're looking for
Anybody who had further questions or wanted a personal walkthrough of the data. If you didn't get your question asked, we can answer it here. We can also give you a full tour of the app.

### Tools
A computer, and possibly a little tiny bit of SQL.

### Relevant Links
Any relevant links, e.g. a github repo, a demo site

### Where we meet
Where in the Braintree office do you meet? Flipping Tables? The cafeteria?

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by deraj1013** [comment]
Link https://charges.thecircuit.cc/en/

**Comment by derekeder** [comment]
This group has not been active at Chi Hack Night for several months so I'm closing this issue for now. If/when you come back, please re-open this issue or open a new one.
