### ISSUE TITLE
Abacus

### ISSUE THREAD

**Issue by Woodenrings** [chihacknight/breakout-groups#211]
Make sure to check out our [guide to starting a breakout group](https://chihacknight.org/blog/2020/02/28/so-you-want-to-start-a-breakout-group.html)!

### About the group
This group is a prototyping group aimed at building an abacus for educational standards and awarding them to students when achieved. 

### Group leaders
It's just me. Ramah Malebranche.

### Who we're looking for
We are looking for full-stack developers for apps and/or websites. Some background in education could be helpful but all are welcome. This prototype will take multiple meetings to complete and we'll meet on a weekly cadence. we can pick the evening that works for us.

### Tools
Whatever we are comfortable enough to do the job is what we will use. No steep learning curves needed.

### Relevant Links
We can share this in the meeting

### Where we meet
I'm actually not yet sure if CHN is meeting in person yet due to the pandemic. But I am happy to host a Zoom for interested parties.

### Chi Hack Night slack channel
I created a private channel on (http://slackme.chihacknight.org/) called "#abacus"
Slack me (RDJM) for entry

**Comment by derekeder** [comment]
@Woodenrings I think you came to Chi Hack Night remote a few weeks ago. Is this group still something you're working on?

**Comment by Woodenrings** [comment]
Hi Derek,

Abacus is a project I would like to pursue at Chi hack night but most likely in the Spring. Right now, I am a bit over committed to multiple projects that have presented themselves rather quickly.

If you’d like to take that down for now, that’s fine. I can remake it when I can make Tuesday nights again.

Best,
Ramah

**Comment by derekeder** [comment]
@Woodenrings sounds good. you can reopen this issue whenever you return to it.
