### ISSUE TITLE
Digital Security Breakout

### ISSUE THREAD

**Issue by BintLopez** [chihacknight/breakout-groups#213]
### About the group
This is a learning and discussion space for people interested in broadening and deepening knowledge about digital security. Goals of this group are to build capacity technically and/or as digital security trainers, provide a recurring space for folks to bring their security questions, and ultimately cultivate a strong digital security culture among community organizers.

Values:
- Consent and autonomy are key to everything
- Need to actively be anti-racist or else will perpetuate racism
- Harm reduction
- Tech should not be on a pedestal
- Anybody can learn this and become an expert
- People are the experts of their own lives and threat models
- Do not shame people... for falling for the scam, for sharing nudes, for clicking on the phishing email!!!!
- People make mistakes! And as we learn from them, become more resilient!
- Holistic security -- we as individuals can make each other more secure

### Group leaders
Nicole, Davey, Sree (all in CHN slack)

### Who we're looking for
Anybody who's interested in learning more about digital security!

### Tools
We use Cryptpad for notes (as an end-to-end encrypted alternative to Google docs) in addition to Google Docs (for slides). For our various learning pursuits, additional tech tools may or may not be required.

### Relevant Links
Cryptpad kanban dashboard https://cryptpad.fr/kanban/#/2/kanban/edit/trO5dpmeUw038XQyT6fmp91n/
Shared Cryptpad Drive https://cryptpad.fr/drive/#/2/drive/edit/KWDWxO6DzJ1bnKgUTKPAZNMD/

### Where we meet
You can find us on the **tail** of the Giant Sea Turtle (https://gather.town/app/3JdykFv5twqLZMYQ/chn-library). Wat wat turtle butt!

### Chi Hack Night slack channel
We are in the #digital-security channel in Slack

**Comment by derekeder** [comment]
this group hasn't met in a while. closing
