### ISSUE TITLE
Creating a Python & Data learning group

### ISSUE THREAD

**Issue by swatland610** [chihacknight/breakout-groups#218]
Hey y'all! 

I'd like to start my first shot at a `Python & Data `learning group for this upcoming Tuesday's open hack. (I don't need this repo by then, just wanted to start the process!) 

Here's my high level summary of how I'm hoping this work: 

**Goal**: 
Each week that this is held, attendees will leave with: 
- exposure to some basic concepts of python & data analysis
- exposure to some basic visualization tools with python
- a copy of code that they can take and explore with on their own

**Target Attendees**: 
Beginners in Programming, Data Analysis, or Experienced Programmers who want some Python experience

**Tech Requirements**: 
For the time being  only **Google Colaboratory**
- Rather than teaching folks how to install python (or jupyter) locally on their computer, I'm using Colaboratory so we can just jump right in to working with python. 
- All folks would need is a free Google Drive account (which I'm imagining many people would have). 

The biggest goal here is to not force people into installing tech (and only helping them if they ask.) 

**How I'll use this Repo**: Since everything will be in Google Colab for the time being, I'm hoping just to use this repo to organize documents, colab templates, data sources, and instructions. In the long run, it would be awesome if other python folks would be able to jump in and lead this occasionally as well. So I'd like to start organizing the docs for it. 

**General Breakout Group Schedule**:
**Learning Session**
1. Gauge where people are at in python & programming experience
2. Run through my first `intro to Python & Data`(in process!) colab template for about 20 - 30 minutes with time for questions
3. Explain whatever the sample data is & some ideas to practice visualizing and summarizing it

**Working Session**
1. Have attendees make copy of colab template to start working on it their own
2. Set general goal of having 1 different visualization or summary data in the notebook (unique = different than the examples I include)
3.  If desired, help attendees find a different data set
4. At some point, have a quick share out of what people did

**Bigger Picture**:
Based on my last breakout group, I learned that it was challenging for new folks because the data sets were too hard to pull something together in one session. So my goal is that people can leave with something after just one session. So I'm doing much of the _nitty gritty_ coding problems for them - and then they can keep it to read through later on. 

If this type of framework works, there's plenty of other tools similar to colab like Observable (Javascript) and Metabase (PostgreSQL) that could be awesome to expand to. So maybe there is a world where it could be more than just Python - but for now, let's start simple!

**Comment by AndrewKovacic** [comment]
Hey swatland610 - 

I know I'm 2 months late, but I'm interested in getting involved and learning python/collabing. 

Are you still taking on participants? Do you have any resources I can catch up with?

I have quite a bit of coding background for work - but it's all mostly in an old database language (MUMPS). I have some SQL background too. I've taken maybe 3 hours of Python courses, but haven't been able to learn it too well without a project to work on!

Thanks!

**Comment by swatland610** [comment]
hi @AndrewKovacic ! 

Sorry for the delay! I'm hoping to get this started in October - so you haven't missed out yet :) 

I'll be sure to add you to the slack channel once I'm up and running!

**Comment by AndrewKovacic** [comment]
Amazing! I'm excited to get started. Do you have a planned start date?
