### ISSUE TITLE
Guerrilla Recycling

### ISSUE THREAD

**Issue by Tellkat** [chihacknight/breakout-groups#221]
### About the group
A special project under Chicago Environmentalists group, intended to bust and call out recycling violators, provide evidence that the Chicago Recycling Ordinance needs to be strengthened, and provide further support for a standalone Department of the Environment for Chicago. The project would be linked or embedded within [ChicagoEnvironmentalists.org](url)

### Group leaders
Katherine Tellock, Co-Founder and Director, Chicago Environmentalists
ChicagoEnvironmentalists@gmail.com

### Who we're looking for
Unsure of the exact skills. I do not have a tech background- I am a data analyst and project manager, but not a coder. I am basically looking for a dashboard that can be used by project volunteers. I would like a front end with a login for volunteers to be able to assign existing addresses, allow volunteers to add new addresses, update entries, etc. I would like a back end that allows me to see what has been added to the dashboard and where everything stands, and also allows me to easily manipulate data, clean it up, or create charts as needed. Lastly, I would like there to be a map on the website that shows *some* basic details about the points being checked.

### Tools
The website is on Squarespace, but I do not know what other tools would be necessary to create this.

### Where we meet
Slack

### Chi Hack Night slack channel
#guerilla-recycling

**Comment by derekeder** [comment]
We're going to merge this in with Climate Change Hacking #215
