### ISSUE TITLE
What is your name?

### ISSUE THREAD

**Issue by rross0** [chihacknight/breakout-groups#222]
### About the group
What's in a name!? Conventions about people's names vary widely across the world. In the US, however, government forms almost always assume that your name follows a three-part naming convention, with the 'last name' being a family name. This causes lots of problems technically, and, perhaps more importantly, sends the message "This form was not designed for you."

Here are some names of people completing a US government form:
John Doe
Robert Andrew Ross
Matthew Amann IX
John Jacob Jingleheimer Schmidt
Juan Paco Pedro de la Mar
Ichiro Suzuki
Abdullah ibn Muhammad Al ash-Sheikh

Goal 1: Identify, articulate, and parameterize a large number of naming conventions in the world. Maybe start with the ones most likely to appear in the US.
Goal 2: Design at least one UI element that captures names based on their applicable pattern.
Goal 3: Build a website that asks users to input their names using the UI. If we come up with a couple of reasonable approaches, I'd like to fund a randomized trial to see which method works best. 

### Group leaders
Robert Ross @rross0 rob@trueroll.io 

### Who we're looking for
1. People with knowledge about people naming conventions across the globe
2. People with UI/UX design and/or implementation skills.
3. Anyone who is interested in contributing.

### Tools
Agnostic.

### Relevant Links
[The space provided for recording a name on a driver's license or identification card may not exceed **_31_** characters, including up to _**three**_ field delimiters](https://rules.mt.gov/gateway/ruleno.asp?RN=23.3.127)

```
>>> len("John Jacob Jingleheimer Schmidt")
31
>>> "John Jacob Jingleheimer Schmidt".count(" ")
3
```

### Where we meet
[Chi Hack Night](https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=MDYwcnUydm5nYjlnMDJ0cXJlM2hncGZzODkgcm9iQHRydWVyb2xsLmlv&tmsrc=rob%40trueroll.io)
Wednesday, March 28 · 6:00 – 8:50pm
Google Meet joining info
Video call link: https://meet.google.com/yvo-eswn-bzy
Or dial: ‪(US) +1 754-217-7747‬ PIN: ‪561 936 944‬#
More phone numbers: https://tel.meet/yvo-eswn-bzy?pin=2698994791544

### Chi Hack Night slack channel
your-name-please

### Breakout group link
See above

**Comment by rross0** [comment]
I was online for about 20 minutes, but nobody joined me 😢 . Maybe next week we'll get some collaborators.

**Comment by derekeder** [comment]
Might be good to try and start this group at our next in-person meeting on April 25. We get a lot more breakout attendees for those.

**Comment by rross0** [comment]
10-4

**Comment by derekeder** [comment]
@rross0 I haven't seen this project meet at hack night in a while. ok with you if we close this issue for now?

**Comment by rross0** [comment]
@derekeder yeh, sorry, I got sidetracked.
