### ISSUE TITLE
Chicago Farmers Market Navigator

### ISSUE THREAD

**Issue by edleranalytics** [chihacknight/breakout-groups#223]
### About the group
_(For the time being we are using a website builder to write content faster. The market season gets underway very soon, so I am working this way to build this out quickly. If you have a technical solution that is better than this option, I am welcome to take it on in this group)_

This is a group that exists because of a deep passion for local food. There is a gap in information about many of these vendors that sell at markets. They don't typically have a Google Maps listing and their selling schedule is often hard to find. The main goal now is to tell the stories of these vendors and put them on this webpage. 

**I am eager to tell the story of vendors and food producers in communities that lack traditional food reporting. These could be urban farms, a market in a food desert or even a vegan food producer making soul food!**

If you have a favorite vendor or market and want to share stories and photos, please join! 

### Group leaders
Marc Edler (edleranalytics@gmail.com)

### Who we're looking for
- Storytellers. If you have a story about local food, join us! 
- UX/UI support
- HTML and CSS support 

### Tools
Elementor
WordPress
Figma

### Relevant Links
[A pdf file from the UIUC extension system showing what produce is in season at what time](https://extension.illinois.edu/sites/default/files/cjmmwhatsinseason.pdf)

The website that is the source for all markets is here: [City of Chicago Farmers' Markets homepage](https://www.chicago.gov/city/en/depts/dca/supp_info/farmers_market.html) 

The homepage to the navigator is live: [Chicago Farmers Market Navigator](https://stirfryable.com/chicago-farmers-market-navigator/

### Chi Hack Night slack channel
The [chicagofarmersmarketnavigator slack](https://app.slack.com/client/T04KM9VQY/C04UZHJFCHK) 

### Breakout group link
[Google Meet Link](https://meet.google.com/tas-iosn-axg)

**Comment by lauriemerrell** [comment]
Closing; this group has been paused since June per their Slack channel. Can reopen if group reactivates.
