### ISSUE TITLE
Budburst: Evaluating climate change by analyzing community science data

### ISSUE THREAD

**Issue by easherma** [chihacknight/breakout-groups#226]
### About the group
[Budburst](https://budburst.org/) brings together researchers, horticulturists, and community scientists on a shared journey to uncover the stories of plants affected by human impacts on the environment. Budburst tells these stories through data collection, data sharing, education, and personal connections.

The data made by observations is publicly available. In this group we'll be exploring some ways to visualize and clean the data for analysis!

We're interested in exploring a few tasks: 

- Making an interactive web map of existing observations over time
- Helping evaluate or answer the question of if an observation is 'early' or 'late'
- Helping automate or streamline manual processes Budburst staff need to do in order to prep data for analysis
- Perform other exploratory data analysis using the Budburst team and their domain knowledge for guidance

### Group leaders
Eric Sherman
Dr. Emma Oschrin

### Who we're looking for
- Data Scientists (ETL, cleaning, but also analysis)
- GIS folks
- Web developers ( for sharing results publicly)
- People interested in submitting observations 

### Tools
- Python
- QGIS (if needed)
- anything else!

I've been using QGIS and https://kepler.gl/ for some initial mapping explorations

### Relevant Links
https://budburst.org/data

### Where we meet
At least for now we're gonna hang with the climate change folks!

**Comment by easherma** [comment]
Data quality issues, solutions: 

- flagging entries when folks manually enter species 
- app metadata like time spent on app




- filter by time, but in yearly or seasonal increments
- top 50 most observed species 
-

**Comment by easherma** [comment]
Next tasks with the Map: 
- data to group by
- phenophases during the year

layers for plant part (fruits, leaves, flowers)
- within a layer, there is 7 categories
- also within a given year, time series within a year

**Comment by easherma-truth** [comment]
All the different plant parts are each in their own layer (except for LU and LV which would be combined, ideally ) LU = leaves unfolding, LV leaves changing in fall, same layer gives an annual picture of what leaves are doing
all of those layers filtered by the same time period

**Comment by easherma-truth** [comment]
One outstanding task would be to collect other relevant geospatial layers, such as ecological grow zones

**Comment by easherma-truth** [comment]
Some additional notes from Dr. Oschrin that I haven’t translated into any discrete technical steps yet:
Look at the data from 2007 to present and see what the inter annual variation of spring leaf and/or flower phenophases are by species (eg sugar maple) or genus (eg acer species).

Phenophases to use: First Leaf or all leaves unfolded would work for leaves; first flower or middle flower would work for flowers.
Taking into account regional variability would be ideal (eg what pattern do we see in the Great Lakes region vs the southwest).

A completed version of this might look like “acer species in the Great Lakes region reached the middle flowering phenophases in mid April in 2009, 2010, 2011 but in 2012-2016 we see average middle flowering time shift to late April or early May” for example, not based on real data.

**Comment by easherma** [comment]
An update on the map side of things: kepler.gl html export works with a minor tweak mentioned here: https://github.com/keplergl/kepler.gl/issues/2202#issuecomment-1583160024

So a todo for me to is to package up the map we already explored in this fashion to share with the Budburst team. 

We also created https://github.com/chihacknight/budburst-data-analysis/tree/main and @varunbhoopalam will be doing some initial exploratory data work there

**Comment by easherma-truth** [comment]
https://github.com/chihacknight/budburst-data-analysis/blob/main/budburst_filtered_type.zip download to view a map of observations data!

**Comment by easherma** [comment]
Pausing this group for now.
