### ISSUE TITLE
Map Chicago - An interactive map to understand your representative districts

### ISSUE THREAD

**Issue by tkimia** [chihacknight/breakout-groups#228]
### About the group
Hello! I'm working on a special project for ONE Northside. They'd like to host a tool that will allow folks to see all of their representatives, as well as understand all of their representative districts (i.e. Alders, State and federal reps, police and school councils, etc).

Check it out!
https://map-chicago.pages.dev/

### Group leaders
Tomer Kimia (tomer.kimia@gmail.com or tkimia on github)

### Who we're looking for
Describe the kinds of people who would be good for your group. Include the skills, domain knowledge and interests that will help make your project succeed.

### Tools
This is a simple React App written in Typescript and created using Vite. Specifically
```
bun create vite map-chicago --template react-ts
```

Maps are rendered with Leaflet JS.

### Relevant Links
[Github Repo](https://github.com/tkimia/map-chicago)

### Chi Hack Night slack channel
The [Chi Hack Night Slack](http://slackme.chihacknight.org/) is a great place to coordinate between hack nights. We encourage you to set one up and share it here!

**Comment by derekeder** [comment]
Hi @tkimia - have you seen https://myreps.datamade.us/ ?

I'm one of the developers of it. The source code is here: https://github.com/datamade/my-reps

**Comment by tkimia** [comment]
@derekeder I did not see it! Very similar concept, though the UI is a bit different. I will likely take a lot of inspiration from the repo!

**Comment by tkimia** [comment]
Closing for now as the project is "done" for the time being
