### ISSUE TITLE
OpenGrid Development

### ISSUE THREAD

**Issue by tomschenkjr** [chihacknight/breakout-groups#23]
## About the Group

[OpenGrid](https://opengrid.io) is an open-source project led by the City of Chicago that is designed to display a massive amounts of data on a single map. Within Chicago, you can use this to display 311 complaints with crime, pot hole reports with broken street lights, and more. It, in essence, an attempt to reduce many one-off applications into a more powerful query tool to explore data around you and in your community.

More importantly, there is a real possibility to improve this platform to include more use-cases. Help us to extend this platform to visualize more data and make it useful to you.

OpenGrid is available to the public and displays [open data](https://chicago.opengrid.io). Likewise, the code is used internally to help drive operations in the City of Chicago's emergency operations center. Contribution to OpenGrid will help both the City of Chicago and the public.

Here are some ideas:

- [ ] How can we visualize transit data in OpenGrid (e.g., buses, bus passengers, taxis, traffic density)?
- [ ] Add Google Street View so people can click and see what a street looks like (e.g., do streets with a lot of potholes are on streets with a lot of other issues).
- [ ] [Adding Natural Language Processing for easier queries](https://github.com/Chicago/opengrid/wiki/Roadmap-Proposal:-Natural-Language-Processing) 
- [ ] [Show data *about* buildings and roads](https://github.com/Chicago/opengrid/wiki/Roadmap-Proposal:-Interactive-Buildings-&-Street-Objects) 
- [ ] [Integrate Census data](https://github.com/Chicago/opengrid/wiki/Roadmap-Proposal:-Pull-data-from-Census-Reporter)
- [ ] How can we better visualize data (e.g., time-series charts, etc.) in addition to the map?
- [x] [Dynamic legends!](https://github.com/Chicago/opengrid/issues/157)

## Group Leaders

@tomschenkjr -- Chief Data Officer for City of Chicago

## Who we're looking for

The software stack includes: Node.js, HTML/CSS, and Java (for heavier lifting). So, it is helpful if you know some of this, but don't need to be an expert.

We are looking for people to bring ideas on how to improve OpenGrid and some skill to try to implement those ideas. You don't need to be a pro, this is an excellent opportunity to  cut your teeth on learning new things.

You can also join the city's weekly developer calls on Friday at 1:00 pm. See the project's [wiki page](https://github.com/Chicago/opengrid/wiki) for the details.

## Test environment

The application is dependent on three items: opengrid.io, which is the HTML/CSS viewed in the browser; a service layer which had an API endpoint that opengrid queries; and [Plenario](https://plenar.io) which contains a bunch of data from the Open Data Portal.

If you only want to work on the front-end, a development instance of the service layer is available at http://opengrid-service-dev-1134290206.us-west-2.elb.amazonaws.com/opengrid-service/

## Links

- https://chicago.opengrid.io - displays data that's available from Chicago's Open Data Portal.
- https://github.com/Chicago - GitHub repo
- [Project wiki](https://github.com/Chicago/opengrid/wiki)
- [Service Layer repo - power by Plenario](https://github.com/smartchicago/opengrid-svc-plenario) - opengrid.io calls to this code to retrieve data. A [live development instance](http://opengrid-service-dev-1134290206.us-west-2.elb.amazonaws.com/opengrid-service/) is available for testing any of your changes.
- https://plenar.io - we use this to read data from the Open Data Portal (but the data source is easily configurable)
- [Developer API](http://opengrid.readthedocs.io/en/latest/OpenGrid%20API/) -  read how the UI API is designed to read from a data source (e.g., Plenario, MongoDB, etc.)

**Comment by derekeder** [comment]
Haven't met in a few weeks - closing for now
