### ISSUE TITLE
Access to Justice - No meeting tonight **so close to launch!!**

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/breakout-groups#3]
**About the group:** We are a mix of technologists, designers, and justice community stakeholders. Currently, we're focused on exploring how technology can help people on parole. We're working on a website redesign with a community partner, a hackathon, and other related projects.

**On 7/25/17:** Please [view our work in progress](http://map.reentrycolab.org/) and [provide suggestions or code fixes on GitHub](https://github.com/pjsier/reentry-resources-map).

**Tools:** Google drive to share spreadsheets and research

**Where we meet:** Mess hall or a conference room, depending on whether we have a call with our community partner.

**Comment by kwritenow** [comment]
@cathydeng I don't seem to have permission to add a tag. There is web dev work involved in this group too.

**Comment by kwritenow** [comment]
@ethanheppner @cathydeng I'd like to add a beginner-friendly tag. I'd also like permission to add tags myself. Any objections?

**Comment by ethanheppner** [comment]
@kwritenow just added you as a collaborator and I _think_ it worked.

**Comment by msmanak** [comment]
I am interested in this group but also wanted to know more about this group's goal and how I can be  a part of this.

**Comment by rohinimenezes** [comment]
I am part of a start-up at Kellogg focused on reducing recidivism and our team is keen to learn more about your project! What would be the best way to get in touch with you. My email is rohini.menezes@tiltas.co 

Thank you! 
Rohini

**Comment by stevevance** [comment]
Hey, next week we're having an open hack and demo day (April 25, 2017). I'm organizing the demonstrators. Would you like to demo your progress on Access to Justice? This is an opportunity to show what you've done so far, and make a pitch for what you want to do and attract helpers.

**Comment by easherma** [comment]
Hey all, I'd love an update on what this group is up to, especially projects around reentry!
