### ISSUE TITLE
Data Science Office Hours

### ISSUE THREAD

**Issue by zscore** [chihacknight/breakout-groups#39]
The complement of Code Clinic. This will be an informal meeting for people to get help with statistics, machine learning, data, and all the baggage that comes along with these things.

Zane Blanton is running this as a pilot to see if people like this format or not.

**Comment by sadeq786** [comment]
I'd be interested!

**Comment by lethaiq** [comment]
Hi, How can I join in the meeting?

**Comment by zscore** [comment]
Just come to a regularly scheduled Chi Hack Night or join the slack at : http://chihacknightslack.herokuapp.com/ and enter the data science channel.

**Comment by ChrisProkop** [comment]
I am interested in helping out for this, at least while I'm between projects.

**Comment by GovInTrenches** [comment]
Is this still happening? Or is it because of the holiday that there's nobody here?
