### ISSUE TITLE
Mob Programming 2 - The Divvying

### ISSUE THREAD

**Issue by FraskeyTaco** [chihacknight/breakout-groups#40]
When last we left our heroes, they were preparing to use latitude and longitude coordinates to see which Divvy stations were closest to CTA train stations. Armed with nothing more than a computer, the attached python notebook,
[divvy data.zip](https://github.com/chihacknight/breakout-groups/files/483605/divvy.data.zip)
 and a never-supply of pluck and moxie, this rag-tag band of misfits is looking to make their way to the Valhalla of Answerdom. And they need YOU! And probably A COMPUTER! Their quest: to see which train stations people love to Divvy to the most. Will they find out? Join us, and find out!

The AP raves: "It's Python at its Pythoniest!"
The Chicago Tribune cheers: "There are so many chairs in here!"
WBEZ cries: "Is this the rainfall group? No? Sorry."

### Group leaders
Eric Paskey

### Who we're looking for
Looking for people who like to ask great questions and aren't afraid of not knowing what the next step is. Also, a Python pro or two to shepherd us along. Also, we may need a computer.

### Tools
Python, City of Chicago's open data site

### Relevant Links
https://data.cityofchicago.org/

### Where we meet
One of the small rooms with one TV just to the right of the main meeting space.

**Comment by qholness** [comment]
Here is the notebook we were using for 9/20/2016:
[Divvy to CTA Frequency Notebook.zip](https://github.com/chihacknight/breakout-groups/files/484120/notebooks.zip)

If you don't have Python on your machine or if you're running a Windows version of Python, I highly recommend installing (replacing with if you're running Windows) [Anaconda](https://www.continuum.io/downloads). It is an installation package that install many dependent Python libraries.

If you do have Python already be sure to have the following libraries:
<ul style="list-style-type:none;">
<li>pandas</li>
<li>matplotlib </li>
<li>seaborn</li>
<li>numpy</li>
</ul>

You will also need to gather the data on your own from these sources:
[CTA Station Data](https://data.cityofchicago.org/Transportation/CTA-System-Information-List-of-L-Stops/8pix-ypme)
[Divvy Quarterly Data](https://www.divvybikes.com/data)

**Replace** the file paths in the **2nd cell** of the notebook where I initialize them and you should be able to run the entire notebook.

If you've got any question feel free to contact me here or by other means if you'd like to ask.

Happy hacking!
