### ISSUE TITLE
Whistleblowing App for Project Six

### ISSUE THREAD

**Issue by mmazanec22** [chihacknight/breakout-groups#41]
### About the group
Finishing up a Rails app-- need help vetting for security

**Comment by derekeder** [comment]
@mmazanec22 when you get a moment, could you update this description with:

About the group
Group leaders
Who we're looking for
Tools
Relevant Links
Where we meet

**Comment by mmazanec22** [comment]
@derekeder this was a one-time thing.  We're implementing what we learned from the excellent folks at CHN and (finally) making the handoff, hopefully tomorrow.  Thanks for the support though!

**Comment by derekeder** [comment]
Cool!
