### ISSUE TITLE
Manatee Tank!

### ISSUE THREAD

**Issue by K-Wei** [chihacknight/breakout-groups#43]
### About the group

A space for anyone to come discuss their ideas and receive feedback in a friendly environment!

Want to talk about civic app/startup ideas, user experience feedback, or something new? Come hang out in a relaxed atmosphere to chat about civic tech!
### Group leaders

Kevin W, (v-kewei at microsoft.com) but always looking for new facilitators to jump in!

Usually meets on the last Tuesday of every month, but will take requests for other weeks!
### Who we're looking for

We welcome anyone who is curious or interested in discussing their thoughts in civic tech. Very beginner friendly!
### Tools

**Imagination**, and probably **whiteboards** too.
### Where we meet

Depends on the size, usually one of the focus rooms or out in the open area.
### Past Discussions

9/20/16 - How to host a hack night for high school students (featuring Teach Tech Task Force!)
8/30/16 - A tool that matches location-based tax dollars to certain outcomes (graduation rate, jobs, etc.)
  in specific regions

**Comment by K-Wei** [comment]
## 9/27/16 - Public beta of Chicago's new websites! (Featuring Tom Schenk, Chief Data Officer of Chicago!)

Tonight we'll be discussing and providing feedback for the new data portal design and dev.cityofchicago.org. Do you want to help the best open data policies in the world stay on top? Come help Tom Schenk, @chicagocdo, do some user-testing on a newly redesigned Chicago data portal!

Link here:

Very beginner friendly!

Some specific UX questions to address:

- does listing all the categories help discovery?

- We are also including some links to apps using open data and blog updates about the data portal so is this helpful or just clutter?

**Comment by K-Wei** [comment]
## 9/27/16 - Public beta of Chicago's new websites! (Featuring Tom Schenk, Chief Data Officer of Chicago!)

Tonight we'll be discussing and providing feedback for the new data portal design and dev.cityofchicago.org. Do you want to help the best open data policies in the world stay on top? Come help Tom Schenk, @chicagocdo, do some user-testing on a newly redesigned Chicago data portal!

Very beginner friendly!

Some specific UX questions to address:

- Does listing all the categories help discovery?

- We are also including some links to apps using open data and blog updates about the data portal so is this helpful or just clutter?

**Comment by tomschenkjr** [comment]
http://dev.cityofchicago.org.s3-website-us-east-1.amazonaws.com

**Comment by K-Wei** [comment]
# Quick Pitch! (Side Project Encyclopedia)

Tonight we'll be having a quick pitch session, where people are invited to talk for 1 minute about a problem they're passionate about (civic tech or non civic tech) and a solution about it! 

The goal is to gather a group of ideas for future ChiHackNighters (and others!) so that people can find side-project inspirations and/or things to discuss.
