### ISSUE TITLE
TheGamma: Tools for open data-driven storytelling

### ISSUE THREAD

**Issue by tpetricek** [chihacknight/breakout-groups#46]
As suggested by @derekeder, I'd like to propose a one-off breakout group for October 11. I'm visiting Chicago for a few days from the UK (@alan-turing-institute). I'm interested in making data-driven reporting and storytelling more open and transparent and would love to discuss some ideas that I've been exploring with @the-gamma. 

### About the group

The goal of the group is to share ideas on how to make data-driven stories and reports more open, transparent and reproducible. A typical way of producing stories or reports involves a number of manual steps – the author might download data using a web browser, filter it using a spreadsheet application, produce a chart and embed the result in an article as an image. Such reports have a number of issues:

 1. They are error-prone (it is easy to make mistakes when processing data by hand)
 2. They are not transparent (readers cannot verify what data is used and how)
 3. They limit further exploration (readers cannot modify the article to explore other aspects of the data)

Those issues arise from one key problem: the link between the article and the original data source is lost during the process. 

On October 11, I would like to briefly share some of my ideas on how this can be fixed with better programming tools - and demo [Visualization of Olympic Medals](http://tomasp.net/blog/2016/thegamma-olympic-medalists/) project and then get everyone's thoughts on the issue and perhaps use the prototype to visualize some interesting Chi Hack data sets!

### Group leaders
Tomas Petricek (tomas@tomasp.net, [@tomaspetricek](http://twitter.com/tomaspetricek) on Twitter)

### Who we're looking for
Anyone who is interested in transparent data analysis is welcome!

 - Do you have some interesting data that we could explore & visualize using the prototype?
 - If you're interested in functional programming, we can talk about the F# bits.

### Tools
The demo uses F# and JavaScript, but any tool that can build a REST API can be used for providing data.

### Relevant Links
 - [Visualizing Olympic Medalists](http://rio2016.thegamma.net/) - demo site built using the project
 - [Article about the visualization](http://tomasp.net/blog/2016/thegamma-olympic-medalists/) providing background and more details
 - [Computation + Journalism 2015 paper](http://thegamma.net/files/cj2015.pdf) (PDF) with more background and motivation for this

### Where we meet
TBD

**Comment by tpetricek** [comment]
@derekeder Thanks for providing the space for doing this, it was great to visit Chi Hack Night! 😺

**Comment by derekeder** [comment]
Thank you Tomas for participating! It was good to meet you!
