### ISSUE TITLE
UChicago Police Department – Data Analysis 

### ISSUE THREAD

**Issue by julieteldred** [chihacknight/breakout-groups#47]
### About the group

Some context: The University of Chicago Police Department (UCPD) is one of the [largest private police forces in the world](http://www.vice.com/read/why-does-a-campus-police-department-have-jurisdiction-over-65000-chicago-residents-1112), and has a jurisdiction that stretches [well beyond the boundaries](https://d3qi0qp55mx5f5.cloudfront.net/safety-security/uploads/files/Extended_Patrol_Map.pdf) of the UChicago campus core. Over the past decade, [numerous Black students and residents](https://www.chicagomaroon.com/2014/10/31/students-recount-racial-bias-of-ucpd/) of surrounding communities have accused the UCPD of racially-biased policing, but since the UCPD is not accountable to FOIA, they had no way of proving this outside of anecdotal evidence. However, due to pressure from student and community activist groups like the [Campaign for Equitable Policing (CEP)](https://www.facebook.com/equitablepolicing/), the UCPD finally [agreed to start releasing data in June 2015](https://www.chicagomaroon.com/2015/04/14/ucpd-to-make-public-information-on-traffic-stops-field-stops-and-arrests/) on the Traffic Stops and Field Reports made by their officers. 

This data is accessible on their data portal; however, they only show 5 rows at a time. What I have done is gone through each page, and copy-pasted each row into a spreadsheet, which I subsequently geocoded using ArcGIS. I first started compiling this data in December 2015, and have updated it every few months since; you can view the geocoded shapefile on [map #14 of my Story Map](http://tinyurl.com/uchicagomap).

This data has many implications - for the UCPD, for the University of Chicago, and even for the city as a whole. That's where you all come in! I would love to see what kinds of insights fellow civic hackers can glean from this data, and more broadly, raise awareness to the biased policing practices of the UCPD - a private police force not accountable to FOIA or its constituents. 
### Group leaders

[Juliet Eldred](http://julieteldred.com)//[Twitter](http://twitter.com/julieteldred)//email: eldredj@uchicago.edu
If anyone has specific knowledge of the UCPD or related issues, let me know if you'd be interested in being a group leader! 
### Who we're looking for

Data analysts, coders, GIS folks, really anyone who finds these topics interesting 
### Tools

Excel, ArcGIS/QGIS, and more! 
### Relevant Links

[The data set on my GitHub page](https://github.com/julieteldred/UCPD-data)
[UCPD Data Portal](http://safety-security.uchicago.edu/police/data_information/)
[My Story Map on UChicago's land use and expansion](http://tinyurl.com/uchicagomap)
### Where we meet

Specific location TBA; we'll probably meet in the back of the atrium

**Comment by julieteldred** [comment]
Here's a cute little data visualization I made using CARTO, of UCPD traffic stops by race over time 

<iframe width="100%" height="520" frameborder="0" src="https://julieteldred.carto.com/viz/195c1bd0-8fcc-11e6-82e1-0e8c56e2ffdb/embed_map" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

**Comment by derekeder** [comment]
@julieteldred this may be of use to you: https://github.com/datamade/illinois-ucr

It's a cross-walk of UCR codes used by police forces in IL. UChicago is in there

**Comment by derekeder** [comment]
Closing for now. This group hasn't met in a while
