### ISSUE TITLE
Legislative Agenda Alerts app - not meeting today (11/29)

### ISSUE THREAD

**Issue by FraskeyTaco** [chihacknight/breakout-groups#55]
### About the group
Brainstorming and dreaming session. Legislative Agenda Alerts would be a program that monitors proposed legislation at all levels and alerts app users when action is needed. This is in response to John Oliver's story about NRA organization. While the purpose of this app would be to directly oppose the NRA's efforts to block any and all gun control legislation, it could certainly be used for other agenda items. 

### Group leaders
Eric Paskey
eric.paskey@gmail.com

### Who we're looking for
Creative thinkers to imagine what the app could do, and developers with ideas about how to bring these ideas to fruition.

### Tools
Currently none. Just gathering ideas.

### Relevant Links
https://github.com/FraskeyTaco/Legislative-Agenda-App/issues
https://www.youtube.com/watch?v=EtTHzegMWA0

### Where we meet
Any unclaimed area with a whiteboard and a marker.

**Comment by jonkeane** [comment]
First, it was great meeting everyone. 

The sunlight labs devloped [a tool](https://github.com/sunlightlabs/scout) that accomplishes some of what we were talking about last night. A longer introduction is available [on their blog](http://sunlightfoundation.com/2012/06/11/scout-sunlights-new-custom-alert-service/). It's not running anymore after sunlight labs shut down, but the code is all open source and might serve as a good starting point or reference for how they accomplished what they did.

**Comment by FraskeyTaco** [comment]
I've added a link to a new repository for this idea. Feel free to post your thoughts there. Check under "Relevant Links".

**Comment by stevevance** [comment]
Another one of Sunlight's apps is [OpenStates](http://openstates.org) (currently in read-only mode until it can transition to a new supporter). It will notify you of proposed legislation in the house of your choice based on keywords. 

In what jurisdiction will the legislative alerts app work first?

At a Latin@ Techies Hackathon on Saturday, there was a group that wanted to try and use Chicago Councilmatic to alert subscribers to legislation and meetings about housing issues. I don't think resources from the Hackathon have been uploaded yet.

**Comment by FraskeyTaco** [comment]
Consensus seemed to be that we start "small" and just stick with the City of Chicago.

**Comment by derekeder** [comment]
DataMade has built maintains Chicago Councilmatic that focuses on the Chicago City Council: https://chicago.councilmatic.org/

We are actually working on an email alerting feature right now for NYC Councilmatic and will bring the updates into Chicago after. Should be deployed in the next few weeks. You can track our progress here: https://github.com/datamade/nyc-councilmatic/issues/160

**Comment by derekeder** [comment]
closing for now as this group hasn't met in a few weeks.
