### ISSUE TITLE
Dear Dialogue

### ISSUE THREAD

**Issue by sylphiae** [chihacknight/breakout-groups#56]
### About the group
This idea was inspired by Letters for Black Lives at lettersforblacklives.com. This is intended to help make a similar process of writing letters to family and friends easier for different groups and different issues in the wake of Trump's election. In the age of Facebook and Twitter, sending a letter is so much more meaningful and is a direct way of letting your loved ones know how you have personally been affected by the election and its aftermath. The goal of these letters is to spread awareness and open up dialogues on a wide range of topics that concern you. 

### Group leaders
Bonnie Fan (bonnie.y.fan@gmail.com), Nell Taylor (nell@readwritelibrary.org), Jenny Tong (j.tong89@gmail.com), Chevy Williams (chevy@metrixmaven.com)

### Who we're looking for
We would like more developer experience. However, anyone with an interest can join. Please join us by joining the Google Group at https://groups.google.com/forum/#!forum/dear-dialogue and sharing your ideas with us. 

### Tools
TBD

### Relevant Links
https://medium.com/dear-dialogue
 lettersforblacklives.com

### Where we meet
TBD. Tuesdays at ChiHackNight Braintree office.

**Comment by derekeder** [comment]
this group hasn't met in several weeks. closing for now
