### ISSUE TITLE
Subscription to Good

### ISSUE THREAD

**Issue by bonfirefan** [chihacknight/breakout-groups#57]
### About the group
Like your Netflix subscription, for public good.
Originally conceived as a **self sustaining** fund to raise money for causes and groups in need of extra resources: refugees, Muslims, LGBTQ, immigrants, healthcare recipients, victims of racial violence and discrimination, Planned Parenthood, other women's organizations, environmentalists. Made self sustaining through a monthly subscription model, distributive in some sort of popular vote. Something longer term than a one-time act of giving.

### Group leaders
Bonnie Fan (bonnie.y.fan@gmail.com)

### Who we're looking for
We need you if you're fond of research, familiar with social causes and nonprofit fundraising, and/or familiar with payment processing methods. Web development definitely too.

### Tools
TBD

### Relevant Links
TBD

### Where we meet
We'll settle in the back corner of the common meeting room in Braintree for now.

**Comment by derekeder** [comment]
This is a really cool idea @bonfirefan! You should reach out to some of the folks at Braintree to help out. They are a payment processing company after all ;)

**Comment by micada** [comment]
In!

**Comment by Vwampage** [comment]
In to help out.

**Comment by kexline4710** [comment]
@bonfirefan Happy to help figure out the payment processing piece.

**Comment by bonfirefan** [comment]
Hey all - since we didn't have the chance to meet properly and discuss, I've created a Google doc with needs and discussion points for now. Feel free to contribute and note your contributions if you're comfortable.

https://docs.google.com/document/d/1mZhDPG5tURMJV96q93H3-kUlnWIMh2KWti7WFPoC1_4/edit

**Comment by stevevance** [comment]
Public Good is another local company and their mission is to make it easier for non-profits to raise money. I have used their product extensively now, to raise money for Streetsblog Chicago. 

They already have groupings of organizations by topic so if you're so inclined to donate to "public transportation" groups [you'll get a list of them](https://publicgood.com/discover/public-transportation-systems-2). They don't have a way to select a bunch and donate money to the bunch and have PG divvy the donation.

**Comment by derekeder** [comment]
A friend of mine made something similar. Worth noting: https://www.twoforliberty.com/

**Comment by derekeder** [comment]
this group hasn't met in several weeks. closing for now
