### ISSUE TITLE
Latinx Techies Hack Group

### ISSUE THREAD

**Issue by KaraAJC** [chihacknight/breakout-groups#58]
### About the group
The Latinx Techies is an initiative of online magazine Gozamos. We seek to empower Latinos in the latest tech tools to grow personally and professionally and leverage these skills to empower our communities and inspire the next generation of Latinx techies. This group will allow for the creation and continuation of projects surrounding latinx communities in Chicago and tech solutions to address community needs and issues. 

### Group leaders
[Luz Chavez](mailto:latinotechies@gmail.com)
[Kara Carrell](https://github.com/KaraAJC)

### Who we're looking for
We'd like to have latinx and allied communities who are interested in building up projects that were created from our first two hackathons, and are willing to further capacity build with our teams. 

### Tools
Tools are varied, but databases are heavily being used. 

### Relevant Links
- [Latinx Techies](http://latinotechies.com/about/)
- [2016 Hackathon github](https://github.com/latinotechies)

### Where we meet
To Be Determined

**Comment by derekeder** [comment]
@KaraAJC thanks for starting this group! FYI there is no Chi Hack Night tonight due to the Thanksgiving holiday: https://twitter.com/chihacknight/status/801087318228512768

**Comment by KaraAJC** [comment]
No Worries, we're letting everyone know to come next Tuesday. let me know if there's anything else to prep luz & I or the attendees!

**Comment by luzcb** [comment]
Hey all! We're now on the ChiHackNight slack channel. Check out our thread #latinxtechies

**Comment by eabedrapo** [comment]
Hi! I'm Elisa!

**Comment by luzcb** [comment]
New to the breakout group? Here's how to get started: http://latinotechies.com/hack/

**Comment by derekeder** [comment]
Replaced with #83
