### ISSUE TITLE
Digitial Security 101 (aka CryptoParty)

### ISSUE THREAD

**Issue by derekeder** [chihacknight/breakout-groups#59]
### About the group
This is a workshop for anyone looking to protect their online activities, communications and information. 

You'll learn to: 
* use secure messaging services like [Signal](http://whispersystems.org/) and [Semaphor](https://spideroak.com/solutions/semaphor)
* encrypt your devices
* browse the internet anonymously with [Tor](https://www.torproject.org/projects/torbrowser.html.en)
* use a password manager & two-factor authentication

### Group leaders
Derek Eder, Chi Hack Night organizer

### Tools
Bring your computer and/or phone. We'll be installing software and walking through some hands-on demonstrations.

### Relevant Links
We'll be using this guide: [Better living through online security & encryption](https://docs.google.com/document/d/1xOJu-BrRmEg8NYbfPslwz-MRPnrvlB07c-Z_WrcPF8I/edit#heading=h.p3mouzojch11)

### Where we meet
Either in the front of the main auditorium or at the back couches in the cafeteria

**Comment by mateoclarke** [comment]
Oh I would love if we could replicate this in ATX

**Comment by derekeder** [comment]
@mateoclarke  Looks like there is (or was at one point) a CryptoParty group in ATX: 

https://twitter.com/atxcrypto
https://cryptopartyatx.org/?page=0&os=osx&js=auto-yes

More Crypto Parties here: https://www.cryptoparty.in/location

**Comment by Ken-Dallmeyer** [comment]
Good discussion and important information for cleaning up our own on-line life.  Good tips on implementing security procedures in our daily lives with emphasis on ease of use.  You attracted some people with proper backgrounds. 

I have a commitment for next Tuesday (with Center for Neighborhood Technology) so I will not be at Hacknight.  I would like to help in non-technical ways.

Ken

**Comment by natalieleroy** [comment]
Hi Derek, is this still located in the Main Room?

**Comment by derekeder** [comment]
@natalieleroy depending on our size, we either meet in the front of the main auditorium or at the back couches in the cafeteria. I'll update the description with this.

**Comment by derekeder** [comment]
Closing for now as we don't have anyone to run this for the time being
