### ISSUE TITLE
[please close me for a while] Chicago Nursing Home Search

### ISSUE THREAD

**Issue by ziegegeist** [chihacknight/breakout-groups#6]
**About the group** The main goal of this project is to create a tool to help people and their families choose the best long term care option available. Another goal to is to make the residents of Chicago and surrounding areas aware of the differences in nursing home quality and to advocate for improvements. [chicagonursinghomesearch.com](http://chicagonursinghomesearch.com)

**Group leaders** Joel Inwood, ziegegeist@gmail.com

**Who we're looking for** Anyone who wants to give us design or usability feedback is welcome. We also need folks who can help out or offer advice on making a database. 

**Where we meet** Either in one of the free rooms or in the main audience area

**Comment by ziegegeist** [comment]
Unclose Sésame!

**Comment by derekeder** [comment]
closing until @ziegegeist returns

**Comment by Ken-Dallmeyer** [comment]
Joel,
I sent the link to Carol, my wife, at Advocate Lutheran General Hospital, where she is a nurse navigator.  She has a network of professionals who need to help individuals and families find care facilities before patients can be discharged.  I think that this will help get the word out
