### ISSUE TITLE
Deportation/Immigration/Refugee Task Force

### ISSUE THREAD

**Issue by yjkogan** [chihacknight/breakout-groups#62]
### About the group
Our goal is to work on projects that will help people immigrants, refugees, and people who are being deported or are at risk of deportation. Primarily, we want to be a resource for existing organizations that are working on these issues.

**UPDATE:** We've moved to being at ChiHackNight every other week, choosing to work from some other locations on off weeks (TBD exactly where). Check our (hopefully) [up to date calendar](https://calendar.google.com/calendar/embed?src=5gn3ram5pjb3hlibver41fq3rc%40group.calendar.google.com&ctz=America/Chicago) for where we will be!

Up to date details about the group can be found here: https://github.com/chi-immigration-task-force/getting-started. We also use a github organization to manage the various projects going on as part of the group, which you can see at the link above!

### Group leaders
Yonatan Kogan (I'm yjkogan on slack or you can email me at yonatan (at) yonatankogan.com)

### Who we're looking for
Anyone!

### Tools
TBD!

### Relevant Links
Stilling filling these in, so let me know if there are other organizations we should be looking at
[Illinois Coalition For Immigrant and Refugee Rights](http://www.icirr.org/)
[National Immigrant Justice Center](http://www.immigrantjustice.org/)
[Migration Policy Institute](http://www.migrationpolicy.org/)
[RefugeeOne](http://www.refugeeone.org/)
[Free legal services for Chicago immigration court](https://www.justice.gov/sites/default/files/eoir/legacy/2014/07/11/freelglchtIL.pdf)
[Justice Dept Self-help materials](https://www.justice.gov/eoir/self-help-materials)
[Los ostros Dreamers](https://www.facebook.com/groups/397027733676345/)
[Literacy Works Chicago](http://www.litworks.org/about-us/)
[Centro Romero](http://www.centroromero.org/)
[Prolonged Detention Stories](https://www.prolongeddetentionstories.org/#the-brief)
[Shriver Center](http://povertylaw.org/students/immigrants)
[Heartland Alliance](https://www.heartlandalliance.org/programs/justice/)
[endisolation.org](http://www.endisolation.org/)
[First Defense Legal Aid](https://www.first-defense.org/)

### Where we meet
In the Cafeteria

**Comment by mtzaldo** [comment]
There's a mexican group called "Los otros Dreamers". The group was created by young people that were deported to México and they are looking to share legal information, job opportunities and validate their US studies/education diplomas in México.  This is the facebook link for the group [Los Otros Dreamers](https://www.facebook.com/groups/397027733676345/)

**Comment by sylphiae** [comment]
I would love to take part in this group. I'm part of a slack group called dacastories, which was trying to build a website to highlight DACA stories. The NYT and Senator Dick Durbin have also called for DACA stories.

**Comment by yjkogan** [comment]
Added both notes to the description!

@mtzaldo do you think there's anything we could do to help that group? Would you be up for facilitating a conversation with them one week?

@sylphiae Helping with a DACA stories website sounds like a great idea!

**Comment by mtzaldo** [comment]
@yjkogan I don't know anyone from the group. I posted this issue on the fb group to see if someone is interested, but I can help trying to contact someone from them. Do you have any particular scope for what you want to accomplish? So I can contact them and bridge this project scope and the group needs.

**Comment by yjkogan** [comment]
@mtzaldo I'd just be interested in chatting with someone about what we could potentially do to be helpful to them or things they wish they'd known prior to being deported. I'm also happy to reach out directly so you don't have to be a middle-person haha. Btw, will you be at the next hack night?

**Comment by mtzaldo** [comment]
@yjkogan No, I don't live closer to Chicago.

**Comment by yjkogan** [comment]
@mtzaldo Aw, we'll if you're ever around you should totally come by!

I think the first thing we're going to try working on a website that will enable people to more easily discover what public benefits they're eligible for. Do you think that's something Los Otros Dreamers would have input on? I'm not sure there's a ton of overlap but I'd love to get them involved in whatever we work on next!

**Comment by guillermokrh** [comment]
Hi @yjkogan, how active is this group at ChiHackNight?  I have a project related to immigration and deportation that I need help on, and I'm thinking of bringing it to ChiHackNight.  Let me know if you all are looking for additional projects.  Thanks!

**Comment by sylphiae** [comment]
@guillermokrh This group is very active. I don't want to speak for @yjkogan but we are happy to hear any new ideas. Perhaps you could join our Slack channel in the ChiHackNight slack titled #immigrationtaskforce?

**Comment by yjkogan** [comment]
Hey @guillermokrh, we meet pretty much every week! We're always interested in new projects, so come swing by! You can also follow up with me over email if you'd like, or post a description of the project here -> https://github.com/chi-immigration-task-force/getting-started!

**Comment by aidenkent13** [comment]
Hey @yjkogan this sounds super cool! Has your team developed anything that's already being used by folks and has gotten feedback?

**Comment by yjkogan** [comment]
@aidenkent13 We're pretty much just starting on an app for ICIRR. We had the framework for an iOS app and should have an Android one soon I hope. Do you have experience with user testing in particular?

**Comment by whoknowsjw** [comment]
I'm a member of 1871 and came across this initiative they are starting, and thought of your group. I'll let you be the judge of whether enough synergy exists to make contact. Please let me know if you'd like help reaching out to anyone. https://www.roadtostatus.com/1871-benefits 

Cheer,

James

**Comment by yjkogan** [comment]
@whoknowsjw thanks for sharing! Since it looks like they're for-profit, I'm not sure if there's much volunteer work that makes sense but we may be able to share context and contacts!

**Comment by derekeder** [comment]
This group hasn't met in a while, but you're presenting soon! Should we close this issue for now?

**Comment by yjkogan** [comment]
Yep, I think that's fine. I think I'll be winding the group down after this project launches in any case :).
