### ISSUE TITLE
How Renewable is My State?

### ISSUE THREAD

**Issue by brendanscully64** [chihacknight/breakout-groups#63]
"Climate change is the single greatest threat to a sustainable future. But, at the same time, addressing the climate challenge presents a golden opportunity to promote prosperity, security and a brighter future for all."

Ban Ki-moon
Secretary General, United Nations

### About the group
This group aims to compile energy consumption data from all 50 states and put together a visualization to easily access and understand that data. We are looking at energy consumption data broken down by:
 - state
 - energy source
 - renewable/non-renewable

### Group leaders
Brendan Scully - brendanscully64@gmail.com

### Who we're looking for
We are looking for anyone with an interest in or experience with:
 - renewable energy
 - data visualization
 - story telling

### Where we meet
Varies by date, will be announced at the meeting.

**Comment by ApurvaNaik** [comment]
I'm interested in contributing! I'm good at researching. I'm comfortable with making visualizations in R. Beginner level skills in Python pertaining to web-scraping

**Comment by brendanscully64** [comment]
Hi Apurva,

Thanks for your email, we're always looking for people willing to
contribute! What is your email and I will add you to our running email
thread? That should give you a good idea of progress made so far, and
things you can do to contribute.

Thanks,

Brendan

**Comment by ApurvaNaik** [comment]
Hello Brendan,

Please add me to the group via apurva.ict@gmail.com. Will you be working on this tomorrow at the hack night?

Regards,
Apurva

**Comment by hangtwenty** [comment]
I have not attended the meetup yet, but if I can join the mailing list I would love to. My email address is visible from my profile (don't want to paste it here again, as I sometimes remove it from my profile when the recruiter spam gets bad)

**Comment by brendanscully64** [comment]
Hi Michael,

Sure thing, added you to the mailing list!

Brendan

**Comment by megwalters** [comment]
I know I'm a little late to the game here, but I'm interested in joining this group.  My main experience with data visualization is via Python with matplotlib and Bokeh.  E-mail is megwalterss@gmail.com.

**Comment by brendanscully64** [comment]
Hi Meg,

Sounds great! I'll add you to the email list, looking forward to meeting
you soon.

Thanks,

Brendan

**Comment by zslutzky** [comment]
Hey group,

https://www.discover.com/home-loans/calculate-appliance-energy-cost-by-state/  something to peruse! Can be inspiration for us (since it compares your energy use to the average person/household per state) or can be used as a resource for the user...! 

Brendan etc, can I be added to the thread as well to get the data and google drive files?  thanks so much! zslutzky430@gmail.com. 

 See everyone next week! 

-Zoe (the person who came in late!)

**Comment by stevevance** [comment]
Every year, utility companies in Illinois are required to publish a recap of their electricity generation sources, and how much they used from each. This is even mailed to consumers. 

While looking for their stats (which I haven't found yet), I found [this information](http://www.eia.gov/electricity/monthly/), per state, on the Energy Information Administration's website.

**Comment by brendanscully64** [comment]
Zoe, thanks for the link! Added you to the email list.

Steven, great find. EIA.gov is currently the source of the data we're
using. Specifically, their State Energy Data System (SEDS) page:
www.eia.gov/state/seds/

**Comment by stevevance** [comment]
@brendanscully64 Jeeze, the planned release date for 2015 data about nuclear usage is 04/14/2017.

**Comment by reconmaster** [comment]
I'm in. Please include me. I've got a bone to pick with NC.

**Comment by easherma** [comment]
Check out https://github.com/chihacknight/How-Renewable-Is-My-State/ for dev updates

**Comment by aidenkent13** [comment]
Hey @brendanscully64 this groups sounds super cool. Have you folks developed anything that's being used by people and has received feedback?

**Comment by Velfi** [comment]
[The site is up](http://howrenewableismystate.com/)

**Comment by Velfi** [comment]
Due to lack of interest, I'm putting the group on ice. The website will remain up @ http://howrenewableismystate.com
For any questions / comments, message me on the chi hack night slack (@zelda_h) or email me at zelda.hessler@gmail.com
