### ISSUE TITLE
User Experience (UX) Office Hours

### ISSUE THREAD

**Issue by matiaskitty** [chihacknight/breakout-groups#66]
### About the group
Do you need help defining or refining a goal or goals for an app, website, or other thing you're making? Do you need planning user research activities? Do you already have something made but need feedback on its usability? Come on down to UX Office Hours.

### Group leaders
Claire Micklin
slack @clairemicklin
Twitter: @clairemicklin

### Who we're looking for

Anyone who 
- has an idea for a project
- needs help defining or refining focus for a project
- needs feedback on usability
- wants to learn more about user-centered design
 
### Tools
My experience as a UX designer. A computer always helps. 

### Relevant Links
Coming soon!

### Where we meet
We meet in the cafeteria.

**Comment by everyone-else** [comment]
Claire, I hope to see you tomorrow. We are www.crkiosk.org. - Terry
