### ISSUE TITLE
Community Connection Survey

### ISSUE THREAD

**Issue by mmazanec22** [chihacknight/breakout-groups#67]
### About the group
We've noticed that civic hacking spaces have a lot of brilliant technologists looking for ways to contribute and community organizations have a lot of technology needs.  But currently, there is no good mechanism to connect tech volunteers to community organizations that are not already part of the civic tech space.  We're interested in surveying the technologists at Chi Hack Night to better understand what tech folks are looking for in terms of volunteering and community engagement.

### Group leaders
Jillian Somera
Ben Newman
Nick Gorajski
Melanie Mazanec

### Who we're looking for
For December 13th, we'd love to talk to everyone who could possible give us some feedback on this survey.  This includes technologists, nonprofit professionals, community members, and everyone else.

### Tools
Only Google Forms so far, although it is likely we will eventually end up making a Rails app.

### Relevant Links
Here is the survey:  https://goo.gl/forms/IsotDFD06RJOupIn1
As of 12/13/16 we're NOT accepting responses-- only feedback on whether this is a well-constructed survey that will yield the kind of information we're seeking.

### Where we meet
Wherever we can find some space!

**Comment by derekeder** [comment]
is this group meeting tonight? if not, I'll close it for now.

**Comment by mmazanec22** [comment]
Not meeting tonight!  Thanks for asking
