### ISSUE TITLE
Product Office Hours

### ISSUE THREAD

**Issue by sgeofrank** [chihacknight/breakout-groups#68]
### About the group
Helping define a vision for your product. Product people worry about everything, who will use your product? Why will they use it? How will they use it? When will they use it? All of this helps build a more usable, valuable product and will increase user adoption. There's a lot of tricks of the trade and I'd love to talk about them.

### Group leaders
Sam Frank, product owner and OpinionLab, former entrepreneur, CSPO and techie.

### Who we're looking for
Beginners or people stuck with deciding what to do next with their tool. Facing tradeoff problems? Have poor user adoption? Worried about the future of your tool? Let's talk about it!

### Tools
The power of communication!

### Relevant Links
https://www.youtube.com/watch?v=502ILHjX9EE

### Where we meet
I'm in the back of the main room, we'll figure it out.

**Comment by derekeder** [comment]
This group hasn't met in a while. Closing for now
