### ISSUE TITLE
Safety & privacy in online activism

### ISSUE THREAD

**Issue by Polisurgist** [chihacknight/breakout-groups#74]
### About the group
These days, activists have a wealth of options for speaking out & taking action electronically. But they also have learned the hard way to protect personal data. This discussion group focuses on maintaining a balance between action and healthy skepticism in this space.

### Group leaders
Rich Ranallo: zincoxide@gmail.com
...and hopefully some others soon?

### Who we're looking for
This is a discussion primarily for activists who have used online organizing tools, with a few techies who have built or developed them. But this is not primarily a technical discussion, so participants from every walk of life are welcome.

### Tools
A whiteboard, probably.

### Where we meet
TBD

**Comment by Polisurgist** [comment]
## Agenda

Obviously we all love activist tech; it amplifies the people's voices and influences elected officials for important causes. Since the 2016 presidential campaign especially, activist tech has gained a lot of visibility. What's also become more visible since then is our need to be careful about what we share about ourselves online. In the past week specifically, a number of digital tools have found themselves in the center of mini-controversies.

* "Text COUNT ME to 89800": http://www.snopes.com/text-count-me-to-89800/
* SwingLeft: https://www.dailykos.com/story/2017/01/23/1623982/-Swing-Left-Is-Not-To-Be-Trusted-As-A-Progressive-Resource

This leaves us with a potentially dangerous dilemma: we want to take action, we want to use these tools and we want to encourage creators to continue building them. But it isn't always clear that the tools we see getting viral attention actually do what they are trying (or claiming) to do, or how much data we're giving in order to use them, who is building them, who is funding them and what their ultimate goal is.

### Questions

* What are the threat models to look for? (aka, what are the potential dangers about an unfamiliar tool?)
* What red flags can you look out for?
* What is a productive way to question/push back on something suspicious?

**Comment by derekeder** [comment]
@Polisurgist meeting this week?

**Comment by Polisurgist** [comment]
Closing it for the time being. I'm only a maybe for being able to make it tomorrow. I'll reopen if I do make it in.
