### ISSUE TITLE
Connect with your representatives

### ISSUE THREAD

**Issue by alison985** [chihacknight/breakout-groups#75]
### About the group
Collect dates of elected officials meetings and town halls. Where are the easy opportunities to show up and make your voice heard?

### Group leaders
Alison (Github: @alison985, Twitter: @alison985)

### Who we're looking for
Anyone who is a general user of the internet and Google doc/spreadsheet/calendar products is good for this group. It's great for people who aren't sure where to begin but who want to be helpful first thing. Anyone who has in depth experience or wants to learn Google Calendar API would be an added bonus!

### Tools
* Google spreadsheets
* Google Calendar
* Wiki (media wiki)

### Relevant Links
* resistancemanual.org

### Where we meet
TBD

**Comment by alison985** [comment]
Slack room named: #connect

**Comment by stevevance** [comment]
Have you found some existing resources yet?

Right now my strategy is to subscribe to e-newsletters from a bunch of different alders, which is annoying, and ineffective. Some alders who have newsletters don't even announce the events they plan to attend!

**Comment by derekeder** [comment]
Is this group meeting this week?

**Comment by alison985** [comment]
No, there's a better resource already existing: http://bit.ly/TownHallProject2018 This group is closed.
