### ISSUE TITLE
Blockchain Technology & Cryptocurrencies

### ISSUE THREAD

**Issue by GeorgeChikovani** [chihacknight/breakout-groups#76]
### About the group
Blockchain technology is the most important invention in computing in a generation because, for the first time in human history, we have at our disposal a truly native digital medium for peer-to-peer value exchange. Blockchain, a vast global platform based on a distributed ledger, establishes the rules in the form of computations and heavy duty encryption that enable two or more parties to transact or do business without needing a third party to establish trust.

Rather than relying on a bank, government or other intermediary to create trust, the blockchain ensures it through mass collaboration and clever code. Trust is built into the system, which is why we call blockchain the Trust Protocol.

Taken one step further, the blockchain also acts as a ledger of accounts, a database, a notary, a sentry, and clearing house, all by consensus. We believe it is the second generation of the Internet and holds the potential to rewire the economic power grid and shake up the old order of things for the better.

Did I mention Bitcoin? yeah, the system of Bitcoin is entirely based on the blockchain.

### Group leaders
George Chikovani
george@idf.solutions

### Who we're looking for
We are looking for anyone interested in decentralized peer-to-peer systems and cryptocurrency.

### Relevant Links
https://en.wikipedia.org/wiki/Blockchain_(database)
http://www.forbes.com/sites/bernardmarr/2017/01/24/a-complete-beginners-guide-to-blockchain/#4c353cf366a6
http://www.forbes.com/sites/bernardmarr/2016/05/27/how-blockchain-technology-could-change-the-world/#3f75bc1d49e0
http://business.nasdaq.com/Docs/Blockchain%20Report%20March%202016_tcm5044-26461.pdf

### Where we meet
We meet at the main event room.

**Comment by bluebackground** [comment]
When is the next meet up for this group?

**Comment by GiviChikovani** [comment]
Tuesday, February 21. See you at ChiHack Night.
**https://chihacknight.org/**

**Comment by GiviChikovani** [comment]
How Blockchain Technology Could Change The World?

http://www.forbes.com/sites/bernardmarr/2017/01/24/a-complete-beginners-guide-to-blockchain/#4c353cf366a6

**Comment by sebastiankelle** [comment]
Hi guys. It was great to meet you! Here is the link to the UK's initiative to use blockchain technology in the educational context. http://blockchain.open.ac.uk/
I know the guys working on this and can act as proxy if we need something from them.

**Comment by GiviChikovani** [comment]
Thanks for sharing!

**Comment by themantalope** [comment]
Will the blockchain group be meeting tonight?

**Comment by GiviChikovani** [comment]
Yes, we will be meeting today evening!

**Comment by mishakogan** [comment]
Will there be a session on the 20th of June?

**Comment by GeorgeChikovani** [comment]
@mishakogan,

Yes, there will be.

**Comment by kellygross** [comment]
Sorry - new here and to Chi Hack night.  So, do you guys break out into this working group every time Chi Hack night meets (eg. every Tu) - just after the main presentation?  And if so, generally how long are the main presentations?  Are there any evenings specifically for blockchain?  Thank you!

**Comment by derekeder** [comment]
As long as this issue is open, that means this group is planning to meet during breakout groups next Tuesday.

Presentations usually wrap up around 7:15-7:30p and we have the Braintree space until 9:30p

**Comment by kellygross** [comment]
Thank you!

**Comment by derekeder** [comment]
hi @GeorgeChikovani - is this breakout group still active & meeting at Chi Hack Night?

**Comment by GeorgeChikovani** [comment]
> When is the next meet up for this group?

**Comment by GeorgeChikovani** [comment]
> > When is the next meet up for this group?

**Comment by emilyannesmith** [comment]
Hi, is this breakout group still active at the hack nights?

**Comment by derekeder** [comment]
Looks like this group is no longer active. Closing for now.
