### ISSUE TITLE
Reducing Recidivism 

### ISSUE THREAD

**Issue by rohinimenezes** [chihacknight/breakout-groups#77]
### About the group
We are a start-up coming out of the Kellogg School of Management focused on reducing recidivism and creating a social network for returning citizens. 

### Group leaders
Tiffany Smith - Founder/CEO - tsmith2017@kellogg.northwestern.edu
Rohini Menezes - Team Member - rmenezes2017@kellogg.northwestern.edu 

### Who we're looking for
Developers, Hackers, Creatives - anyone looking to change the world! 
Legal/policy experts in the criminal justice space 

### Where we meet
Mix of Evanston and Downtown

**Comment by derekeder** [comment]
This group hasn't met in a while - closing for now
