### ISSUE TITLE
WasteFoe - tackling food waste with tech

### ISSUE THREAD

**Issue by WasteFoe** [chihacknight/breakout-groups#79]
### About the group
The problem we're trying to solve is the important issue of Food Waste. Although there are some solutions for waste in restaurants and supermarkets, there isn't a good solution for solving the issue in our own homes. That's where we will have an impact! 

### Group leaders
Jorge Medina Zambrano
847-630-8824
jhmzambrano@gmail.com

### Who we're looking for
We're looking for designers, prototypists, engineers, and anyone interested in combining approaches in order to simplify this very complex problem. 

### Tools

-HTML5 (used PhoneGap for some of the development)
-Ruby
-React Native 
-Open

### Relevant Links
Link for latest Android version:
https://www.dropbox.com/s/sqvm9qkazb0dews/android-release.apk?dl=0

### Where we meet
Still figuring out where to have a regular meeting place...

**Comment by WasteFoe** [comment]
Thanks everyone who came by to talk and contribute! I'll be uploading some documents so you guys can have a better idea on where the project is at right now and how we can collaborate to make it better.

**Comment by WasteFoe** [comment]
[WasteFoe Presentation.pptx](https://github.com/chihacknight/breakout-groups/files/761365/WasteFoe.Presentation.pptx)

PowerPoint Presentation with some more of a summary of my initial idea. Comments welcome!

**Comment by WasteFoe** [comment]
https://www.facebook.com/wastefoe/ 

Like our page in Facebook to fuel the fire!

**Comment by derekeder** [comment]
This group hasn't met in over a month. Closing for now.

**Comment by WasteFoe** [comment]
Hi Derek,

Yeah, it's been difficult the last few weeks. Perhaps you and I could talk
a little about the project as well? I'd love to have your input.

Any progress since the recycling talk at the ELPC?

Regards,

Jorge Medina Zambrano
