### ISSUE TITLE
Police accountability

### ISSUE THREAD

**Issue by alexsoble** [chihacknight/breakout-groups#8]
__About the group__: https://github.com/invinst/shootings-data/blob/master/README.md

__Who we're looking for__: Folks interested in data and police accountability.

__Tools__: Research, Excel, R, Python, Stata

**Comment by alexsoble** [comment]
Hey all! Does @rajivsinclair have permissions to edit / update this issue? He's going to be doing more leadership of the breakout group since Jay Qi is going to have less time for leadership in the future.

**Comment by derekeder** [comment]
Haven't met in a few weeks - closing for now

**Comment by alexsoble** [comment]
OK! We did meet last week though, here's what we did: https://github.com/jayqi/mob_programming_2016-09-06/blob/master/Mob%20Programming%20-%20Sept%206%2C%202016.ipynb

We may have a special guest next week... will let you know! In that case we should definitely re-open.
