### ISSUE TITLE
Science for the People

### ISSUE THREAD

**Issue by ivanhandler** [chihacknight/breakout-groups#80]
Science for the People arose in 1969 out of the anti-war movement and lasted until 1989. With a Marxist analysis and non-hierarchical governing structure, Science for the People tackled the militarization of scientific research, the corporate control of research agendas, the political implications of sociobiology and other scientific theories, the environmental consequences of energy policy, inequalities in health care, and many other issues.

Its members opposed racism, sexism, and classism in science and above all sought to mobilize people working in scientific fields to become active in agitating for science, technology, and medicine that would serve social needs rather than military and corporate interests. They organized in universities and communities, published a magazine offering sharp political analysis, and sought meaningful scientific exchange internationally in Vietnam, China, Cuba, Nicaragua, and other countries.

Some of the issues we face today have changed in important ways, but fundamental questions of power, ideology, and democracy in science remain. The time is ripe to gather SftP veterans with other scientists, activists, students, and scholars in an exploration of what the history of SftP can teach us… and where we go from here.

### Group leaders
Ivan Handler, ivan.handler@gmail.com until younger people take over.

### Who we're looking for
Young people from all backgrounds, especially if you want to become a leader.

### Relevant Links
http://science-for-the-people.org/

### Where we meet
Cafeteria for the moment

**Comment by derekeder** [comment]
This group hasn't met in a while. Closing for now.
