### ISSUE TITLE
A Restroom finder app development 

### ISSUE THREAD

**Issue by erezile** [chihacknight/breakout-groups#81]
### About the group
The issue of finding A clean and welcoming Restroom on the go. Problems, Solutions and Mobile app development. 

### Group leaders
Erez Arbel 
312.479.5560
1@erezarbel.com

### Who we're looking for
Whoever meet the need, Mobile developers, Designers, Business and marketing fellows.

**Comment by stevevance** [comment]
Holler if you want help extracting the locations of restrooms from the vast OpenStreetMap database. People all around the world add restrooms to OSM (of different kinds and location settings) and the data is free to use. 

There are about [160,000](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets) `amenity=toilets` already mapped.

**Comment by alison985** [comment]
http://www.refugerestrooms.org/

**Comment by derekeder** [comment]
This group hasn't met in a while. Closing for now.
