### ISSUE TITLE
Fantasy Civics

### ISSUE THREAD

**Issue by vingkan** [chihacknight/breakout-groups#82]
### About the group
For a class project, a group of students at Illinois Tech is creating Fantasy Civics: a fantasy sports-style game about Chicago government! Draft city leaders, wards, and police districts onto your team and win points when they fulfill 311 requests and appear in the news.
Since this is a class project, we have to do all the engineering and planning work, but we would love to have help from ChiHackNight goers help by testing the game as it evolves and providing feedback!

### Group leaders
Vinesh Kannan - v@hawk.iit.edu
Haosheng Li - hli109@hawk.iit.edu

### Relevant Links
If you or someone you know is interested in joining one of our prototype leagues or just keeping up with the project's progress, please fill out this short form: [bit.ly/fantasycivicsform](https://bit.ly/fantasycivicsform)

### Where we meet
We'll meet somewhere in the cafeteria.

**Comment by vingkan** [comment]
For today, we will do a short breakout group: just a 15 minute session where we share our plans and get feedback from anyone interested.

**Comment by stevevance** [comment]
This game sounds great. I totally want to play it.

**Comment by vingkan** [comment]
Today we will play version 0.0.1 of Fantasy Civics! Come by to try it out and give us feedback!

**Comment by vingkan** [comment]
Today we will play a new version of the game that has packed in lots of feedback from past sessions! Come join us :)

**Comment by atenn** [comment]
Have you shared the game? I filled out the form a while back but don't think I got a link.. are you able to post it here? I spoke with you briefly about the idea of possibly using that data as a way to survey how people feel about their officials.. I think you could get some interesting insights out of it!

**Comment by vingkan** [comment]
@atenn Hi Allison, I do have your email address on the signup form! We haven't shared the game online yet because there are no directions on how to play on the website. We are always looking for people to play the game at ChiHackNight (or over a video call) so we can get feedback on how to improve it before public release.

I think the insights about how people feel about officials could be really interesting too! Could you post some examples of survey questions you think would be valuable? We can start testing them by asking them to people who play the demo version of the game at our next meeting (4/25).

The signup link is here if you know anyone else who'd be interested: bit.ly/fantasycivicsform

If any of your colleagues/friends can't make it to a CHN, we could set up a time to play the game over video call and get feedback!

**Comment by vingkan** [comment]
I haven't been able to sit down and go through the Open Civic Data API to collect sample data for a game, but when I do I'll set it up so people can play around with new methods of scoring the game!

**Comment by vingkan** [comment]
**Updates**
* [Notes from last week's discussion about how to change the game scoring.](https://docs.google.com/document/d/1RqIpOmsdSj4QqnO9JLqPU4nvJmFZemzo6E6H6TrEjdM/edit?usp=sharing)
* Data from the Open Civic Data API is now integrated into the project! [This script](https://github.com/GeliClub/fantasycivics/blob/master/database/scraper.js) pulls, flattens, and saves data from a city council meeting so the game can access it more quickly. I have only saved data from the April meeting.
* There is now a [Fantasy Civics Scoring Simulator](https://geliclub.github.io/fantasycivics/scoring) to test out and compare scoring systems. For this prototype, scoring systems can only be defined in JavaScript.\*

\* Note: _I chose this so that I could implement scoring methods quickly and see how they play out on real data. If others want to propose a scoring system, they can explain it and I (or another JS developer) can quickly code it up so the group can spend time discussing the meaning of the scores and not the implementation._

**To-Do's**
* Run script to save data from May City Council meeting.
* Discuss what needs to be explained about each alder's score.
* Rewrite the scoring module so that it can "explain" how an alder's score was calculated.
* Slim down gameplay to match playtesters' feedback.
* Launch!
* Document the fields of the flattened OCD data.
* Design a way for players to create and test their own scoring systems without coding.
* Add pictures of the alders to the players file.
* Add coordinates of the ward offices to the players file.

**Next Breakout Group Meeting**
Come join us to experiment with new scoring systems and see how they would turn out on real data! You don't need to be a developer to design a scoring system.

**Comment by vingkan** [comment]
Great to meet you today, @jackhowa !

**Comment by vingkan** [comment]
The new version of Fantasy Civics is up and running at: https://fantasycivics.github.io

Improvements made based on previous user testing include:
* Mobile-friendly layout
* Updated landing page and instructions
* Replace "bench" on roster with "positions" (team captain, councilperson, rodent warrior...)
* Add button to share roster by tweet
* Clarify projected total score vs total score from previous month
* Store data from OCD API in Firebase for faster loading times

Now that the site is mobile-friendly (add to your homescreen!), we're ready to launch and get public feedback. At our next breakout meeting, we will start working on ways to launch. Some cool ideas from past sessions:
* Contact journalists and have them play a game with each other
* Play an alderman draft at ChiHackNight
* Let people submit their rosters to a leaderboard
* Write a sports-style blog post about which aldermen to "Sit and Start"
* Do something in conjunction with NFL opening night

**Comment by vingkan** [comment]
New ideas the group brainstormed today:
- Start company competitions
- Have a trophy or a prize for the league
- Play a game on a college campus
- Buzzfeed-style quiz to pick your team
- Make a Facebook group for Fantasy Civics (plus Facebook events)
- Promote to people in government agencies
- Promote to groups like YGL (Young Government Leaders)
- Email social science/humanities professors to present or play the game with their class
- Make promotional graphics that are map-based
- Host a big draft event in November after elections (maybe host at ChiHackNight?)
- Go visit other meetups/eventbrite events similar to ChiHackNight
- Record a short video with screenshots to play the game (Jared can voiceover)
- Livestream event to promote Fantasy Civics (overlay a speech with sports ticker)
- Highlights Reel: create a short video with clips of public aldermen footage
- Sports-style commentary/analysis of Chicago ward news (YouTube Channel?)

**Comment by vingkan** [comment]
- Incorporate snippets from the Daily Line emails
- Contact the Daily Line to promote Fantasy Civics
- (from earlier) Give aldermen a "sticker" for their weekly emails with their FC score
- Connect game to Twitter feeds of aldermen
- Create basic league page (default to publicly available)
- How can you draw the thread between what affects citizens and what happens in the game?

**Comment by derekeder** [comment]
is this breakout group still active? if not, let's close it for now

**Comment by vingkan** [comment]
Closing for now. Hopefully temporary!
