### ISSUE TITLE
Illinois Legislation Working Group, helping constituents make their voice heard beyond witness slips

### ISSUE THREAD

**Issue by RobinChristine** [chihacknight/breakout-groups#87]
### About the group
It's state legislation but with a usable interface.  Search for an issue you care about, find out about a law that will affect it, understand where it's, and who to talk to in a single click.

### Founders 
Eric Gosh
Natalie LeRoy
Ty Cobb
Jonathon Rogoff

### Who we're looking for
User testers that want to jump in and fix a problem.

### Tools
Ruby
React

### Relevant Links
https://legislated.org/
https://staging.legislated.org/
https://marvelapp.com/6i1afh1

### Where we meet
Tuesdays - Brain Tree Flipping Tables
Every other Thursday - Andersonville

**Comment by justgosh** [comment]
We are looking for someone comfortable with scraping a website, writing a technical nontechnical letter that a politician would be willing to sign onto.  We are also looking for someone that can mock up a site to demonstrate a finished and polished product.

**Comment by saduros** [comment]
glad to see the work continues. Were I not tied up with family issues,
letters to politicians is something I do.

Sally Duros
Independent Journalist | Digital Communications

www.Sally Duros.com <http://www.sallyduros.com> | 312. 282. 8680 (cell) | 773.
769. 6070


<http://aboutme.google.com/?referer=gplus>   <http://twitter.com/saduros>
<http://www.linkedin.com/in/sallyduros>
<http://www.facebook.com/sallyduros>   <http://www.sallyduros.com>
<https://instagram.com/saduros/>   <http://pinterest.com/saduros/>

**Comment by justgosh** [comment]
https://github.com/surrealdetective/witnessslips

**Comment by justgosh** [comment]
Robin can you assign me to an admin role on this so we can update it weekly?

**Comment by derekeder** [comment]
@justgosh just added you as a collaborator in this repo. once you accept the invite you should be able to assign yourself

**Comment by RobinChristine** [comment]
lmk if Derek took care of this

**Comment by justgosh** [comment]
Done and working!
Thanks folks

**Comment by justgosh** [comment]
https://github.com/legislated/legislated-web

**Comment by derekeder** [comment]
hi @RobinChristine - is this breakout group still active & meeting at Chi Hack Night?

**Comment by derekeder** [comment]
closing for now. feel free to reopen if you start this back up!
