### ISSUE TITLE
How can a Rideshare Solve Social/Civic/Environmental Issues

### ISSUE THREAD

**Issue by scutter84** [chihacknight/breakout-groups#89]
### About the group
G-Ride is the first green rideshare company that only utilizes eco-friendly cars and is an [L3C](https://en.wikipedia.org/wiki/L3C), a hybrid form of a non-profit and for-profit business. We also have superior driver treatment by having equity options, residual income, tip options and an appointed board seat for the drivers as well. Our goal is to make rideshare open source and work on solving as many social and environmental issues as possible.

### Group leaders
Stephen M. Cutter Jr.
Jai Joseph
Brian Boros
Melany Diaz
Arjun Velagapudi

### Who we're looking for
Initially we will have a brain storming session this Tuesday 2/28/17 to figure out what issues we want to address.

We are looking for people well versed in data analytics, environmental studies, programming, community building, urban agriculture, sustainability and Revolutionaries!

### Tools
We are still defining the tools!

### Relevant Links
www.gogride.com 
FB - gogride7
Twitter- gogride7
Instagram- gogride7

### Where we meet
Our first meeting will be in the cafeteria.

**Comment by scutter84** [comment]
Check out this video!
[G-Ridevideo2.docx](https://github.com/chihacknight/breakout-groups/files/804452/G-Ridevideo2.docx)

**Comment by derekeder** [comment]
This group hasn't met in 3 weeks. Closing for now until they come back.

**Comment by scutter84** [comment]
Hi Derek,

I have been herr every week since I started.

Thanks,

**Comment by derekeder** [comment]
Oh sorry - didn't see you. Are you still doing this group?

**Comment by derekeder** [comment]
I've been informed that this group is not actively collaborating on a project but are instead recruiting for an organization. You're welcome to network for this purpose at Chi Hack Night, but it is not an appropriate use for our breakout group structure. Closing this.
