### ISSUE TITLE
Learning about SDR - Not meeting tonight.

### ISSUE THREAD

**Issue by chibill** [chihacknight/breakout-groups#96]
### About the group
To help inform others about SDRs (Software Defined Radios) possible uses in Civic Tech. And also its explain some information about SDRs in general. 

This is more of a learning group. As we don't really have a main goal.

### Group leaders
William Gaylord - chibill
### Who we're looking for
Anyone interested in SDR. So basically anyone.

### Tools
SDR  and RTLSDR software. 

### Relevant Links
http://www.rtl-sdr.com/ (informative and also have links to get a SDR)
### Where we meet
The cafeteria? Depending on the amount of people.

**Comment by derekeder** [comment]
Is this group still meeting?

**Comment by chibill** [comment]
I hope to try an meet tomorrow. Last week I was pretty ill.

**Comment by derekeder** [comment]
Ok - just checking!

**Comment by chibill** [comment]
Might start this back up later.
