### ISSUE TITLE
Am I Secure Yet? 

### ISSUE THREAD

**Issue by JackHowa** [chihacknight/breakout-groups#98]
### About the group
So, you know [Digital Security 101](https://github.com/chihacknight/breakout-groups/issues/59)? We want to practice what we've learned. This is like the Lab class. Plus, we want to build-out a security checklist for all of y'all. It would be a simple resource based on @derekeder's [research](https://bit.ly/cryptochecklist).

### Group leaders
@jackhowa - jackhowa@protonmail.com

@nunulu - latarifena@protonmail.com

### Who we're looking for
We're looking for law-abiding and/or curious people. We're looking for people who have gone through the Digital Security 101 seminar. 

We want experienced writers and editors to publicize and translate security news. It's a plus if you have front-end development experience, using bootstrap and javascript, to design that slick guide Am I Secure Yet. 

### Tools
We want to make a Bootstrap website with a checklist that can save the state of the user. The checklist will be based on https://bit.ly/cryptochecklist. 

### Relevant Links
https://bit.ly/cryptochecklist 

[r/privacy](https://www.reddit.com/r/privacy/)

### Where we meet
The couches in the back of the cafeteria.

**Comment by derekeder** [comment]
@JackHowa is this still being worked on?

**Comment by JackHowa** [comment]
Yep, Jack Sparrow has the website. And we're working on collaborating.

**Comment by derekeder** [comment]
Closing this, as the group hasn't met at hack night in a while
